VMEC: read_wout_mod Module Reference
read_wout_mod Module Reference
Reading of wout VMEC output file.
Data Types
interface read_wout_file
Functions/Subroutines
subroutine readw_and_open (file_or_extension, ierr, iopen)
subroutine compute_currents (ierror)
subroutine read_wout_deallocate
subroutine tosuvspace (s_in, u_in, v_in, gsqrt, bsupu, bsupv, jsupu, jsupv, lam)
subroutine loadrzl
Variables
character(len= *), parameter vn_version = 'version_'
character(len= *), parameter vn_extension = 'input_extension'
character(len= *), parameter vn_mgrid = 'mgrid_file'
character(len= *), parameter vn_magen = 'wb'
character(len= *), parameter vn_therm = 'wp'
character(len= *), parameter vn_gam = 'gamma'
character(len= *), parameter vn_maxr = 'rmax_surf'
character(len= *), parameter vn_minr = 'rmin_surf'
character(len= *), parameter vn_maxz = 'zmax_surf'
character(len= *), parameter vn_fp = 'nfp'
character(len= *), parameter vn_radnod = 'ns'
character(len= *), parameter vn_polmod = 'mpol'
character(len= *), parameter vn_tormod = 'ntor'
character(len= *), parameter vn_maxmod = 'mnmax'
character(len= *), parameter vn_maxit = 'niter'
character(len= *), parameter vn_asym = 'lasym'
character(len= *), parameter vn_free = 'lfreeb'
character(len= *), parameter vn_error = 'ier_flag'
character(len= *), parameter vn_aspect = 'aspect'
character(len= *), parameter vn_maxmod_nyq = 'mnmax_nyq'
character(len= *), parameter vn_beta = 'betatotal'
character(len= *), parameter vn_pbeta = 'betapol'
character(len= *), parameter vn_tbeta = 'betator'
character(len= *), parameter vn_abeta = 'betaxis'
character(len= *), parameter vn_b0 = 'b0'
character(len= *), parameter vn_rbt0 = 'rbtor0'
character(len= *), parameter vn_rbt1 = 'rbtor'
character(len= *), parameter vn_sgs = 'signgs'
character(len= *), parameter vn_lar = 'IonLarmor'
character(len= *), parameter vn_modb = 'volavgB'
character(len= *), parameter vn_ctor = 'ctor'
character(len= *), parameter vn_amin = 'Aminor_p'
character(len= *), parameter vn_rmaj = 'Rmajor_p'
character(len= *), parameter vn_vol = 'volume_p'
character(len= *), parameter vn_am = 'am'
character(len= *), parameter vn_ai = 'ai'
character(len= *), parameter vn_ac = 'ac'
character(len= *), parameter vn_ah = 'hot particle fraction'
character(len= *), parameter vn_atuname = 'T-perp/T-par'
character(len= *), parameter vn_pmass_type = 'pmass_type'
character(len= *), parameter vn_piota_type = 'piota_type'
character(len= *), parameter vn_pcurr_type = 'pcurr_type'
character(len= *), parameter vn_am_aux_s = 'am_aux_s'
character(len= *), parameter vn_am_aux_f = 'am_aux_f'
character(len= *), parameter vn_ai_aux_s = 'ai_aux_s'
character(len= *), parameter vn_ai_aux_f = 'ai_aux_f'
character(len= *), parameter vn_ac_aux_s = 'ac_aux_s'
character(len= *), parameter vn_ac_aux_f = 'ac_aux_f'
character(len= *), parameter vn_mse = 'imse'
character(len= *), parameter vn_thom = 'itse'
character(len= *), parameter vn_pmod = 'xm'
character(len= *), parameter vn_tmod = 'xn'
character(len= *), parameter vn_pmod_nyq = 'xm_nyq'
character(len= *), parameter vn_tmod_nyq = 'xn_nyq'
character(len= *), parameter vn_racc = 'raxis_cc'
character(len= *), parameter vn_zacs = 'zaxis_cs'
character(len= *), parameter vn_racs = 'raxis_cs'
character(len= *), parameter vn_zacc = 'zaxis_cc'
character(len= *), parameter vn_iotaf = 'iotaf'
character(len= *), parameter vn_qfact ='q-factor'
character(len= *), parameter vn_chi ='chi'
character(len= *), parameter vn_chipf ='chipf'
character(len= *), parameter vn_presf = 'presf'
character(len= *), parameter vn_phi = 'phi'
character(len= *), parameter vn_phipf = 'phipf'
character(len= *), parameter vn_jcuru = 'jcuru'
character(len= *), parameter vn_jcurv = 'jcurv'
character(len= *), parameter vn_iotah = 'iotas'
character(len= *), parameter vn_mass = 'mass'
character(len= *), parameter vn_presh = 'pres'
character(len= *), parameter vn_betah = 'beta_vol'
character(len= *), parameter vn_buco = 'buco'
character(len= *), parameter vn_bvco = 'bvco'
character(len= *), parameter vn_vp = 'vp'
character(len= *), parameter vn_specw = 'specw'
character(len= *), parameter vn_phip = 'phips'
character(len= *), parameter vn_jdotb = 'jdotb'
character(len= *), parameter vn_overr = 'over_r'
character(len= *), parameter vn_bgrv = 'bdotgradv'
character(len= *), parameter vn_merc = 'DMerc'
character(len= *), parameter vn_mshear = 'DShear'
character(len= *), parameter vn_mwell = 'DWell'
character(len= *), parameter vn_mcurr = 'DCurr'
character(len= *), parameter vn_mgeo = 'DGeod'
character(len= *), parameter vn_equif = 'equif'
character(len= *), parameter vn_fsq = 'fsqt'
character(len= *), parameter vn_wdot = 'wdot'
character(len= *), parameter vn_ftolv = 'ftolv'
character(len= *), parameter vn_fsql = 'fsql'
character(len= *), parameter vn_fsqr = 'fsqr'
character(len= *), parameter vn_fsqz = 'fsqz'
character(len= *), parameter vn_extcur = 'extcur'
character(len= *), parameter vn_curlab = 'curlabel'
character(len= *), parameter vn_rmnc = 'rmnc'
character(len= *), parameter vn_zmns = 'zmns'
character(len= *), parameter vn_lmns = 'lmns'
character(len= *), parameter vn_gmnc = 'gmnc'
character(len= *), parameter vn_bmnc = 'bmnc'
character(len= *), parameter vn_bsubumnc = 'bsubumnc'
character(len= *), parameter vn_bsubvmnc = 'bsubvmnc'
character(len= *), parameter vn_bsubsmns = 'bsubsmns'
character(len= *), parameter vn_bsupumnc = 'bsupumnc'
character(len= *), parameter vn_bsupvmnc = 'bsupvmnc'
character(len= *), parameter vn_rmns = 'rmns'
character(len= *), parameter vn_zmnc = 'zmnc'
character(len= *), parameter vn_lmnc = 'lmnc'
character(len= *), parameter vn_gmns = 'gmns'
character(len= *), parameter vn_bmns = 'bmns'
character(len= *), parameter vn_bsubumns = 'bsubumns'
character(len= *), parameter vn_bsubvmns = 'bsubvmns'
character(len= *), parameter vn_bsubsmnc = 'bsubsmnc'
character(len= *), parameter vn_bsupumns = 'bsupumns'
character(len= *), parameter vn_bsupvmns = 'bsupvmns'
character(len= *), parameter vn_bsubumnc_sur = 'bsubumnc_sur'
character(len= *), parameter vn_bsubvmnc_sur = 'bsubvmnc_sur'
character(len= *), parameter vn_bsupumnc_sur = 'bsupumnc_sur'
character(len= *), parameter vn_bsupvmnc_sur = 'bsupvmnc_sur'
character(len= *), parameter vn_bsubumns_sur = 'bsubumns_sur'
character(len= *), parameter vn_bsubvmns_sur = 'bsubvmns_sur'
character(len= *), parameter vn_bsupumns_sur = 'bsupumns_sur'
character(len= *), parameter vn_bsupvmns_sur = 'bsupvmns_sur'
character(len= *), parameter vn_rbc = 'rbc'
character(len= *), parameter vn_zbs = 'zbs'
character(len= *), parameter vn_rbs = 'rbs'
character(len= *), parameter vn_zbc = 'zbc'
character(len= *), parameter vn_potvac = 'potvac'
character(len= *), parameter ln_version = 'VMEC Version'
character(len= *), parameter ln_extension = 'Input file extension'
character(len= *), parameter ln_mgrid = 'MGRID file'
character(len= *), parameter ln_magen = 'Magnetic Energy'
character(len= *), parameter ln_therm = 'Thermal Energy'
character(len= *), parameter ln_gam = 'Gamma'
character(len= *), parameter ln_maxr = 'Maximum R'
character(len= *), parameter ln_minr = 'Minimum R'
character(len= *), parameter ln_maxz = 'Maximum Z'
character(len= *), parameter ln_fp = 'Field Periods'
character(len= *), parameter ln_radnod = 'Radial nodes'
character(len= *), parameter ln_polmod = 'Poloidal modes'
character(len= *), parameter ln_tormod = 'Toroidal modes'
character(len= *), parameter ln_maxmod = 'Fourier modes'
character(len= *), parameter ln_maxmod_nyq = 'Fourier modes (Nyquist)'
character(len= *), parameter ln_maxit = 'Max iterations'
character(len= *), parameter ln_asym = 'Asymmetry'
character(len= *), parameter ln_recon = 'Reconstruction'
character(len= *), parameter ln_free = 'Free boundary'
character(len= *), parameter ln_error = 'Error flag'
character(len= *), parameter ln_aspect = 'Aspect ratio'
character(len= *), parameter ln_beta = 'Total beta'
character(len= *), parameter ln_pbeta = 'Poloidal beta'
character(len= *), parameter ln_tbeta = 'Toroidal beta'
character(len= *), parameter ln_abeta = 'Beta axis'
character(len= *), parameter ln_b0 = 'RB-t over R axis'
character(len= *), parameter ln_rbt0 = 'RB-t axis'
character(len= *), parameter ln_rbt1 = 'RB-t edge'
character(len= *), parameter ln_sgs = 'Sign jacobian'
character(len= *), parameter ln_lar = 'Ion Larmor radius'
character(len= *), parameter ln_modb = 'avg mod B'
character(len= *), parameter ln_ctor = 'Toroidal current'
character(len= *), parameter ln_amin = 'minor radius'
character(len= *), parameter ln_rmaj = 'major radius'
character(len= *), parameter ln_vol = 'Plasma volume'
character(len= *), parameter ln_mse = 'Number of MSE points'
character(len= *), parameter ln_thom = 'Number of Thompson scattering points'
character(len= *), parameter ln_am = 'Specification parameters for mass(s)'
character(len= *), parameter ln_ac = 'Specification parameters for <J>(s)'
character(len= *), parameter ln_ai = 'Specification parameters for iota(s)'
character(len= *), parameter ln_pmass_type = 'Profile type specifier for mass(s)'
character(len= *), parameter ln_pcurr_type = 'Profile type specifier for <J>(s)'
character(len= *), parameter ln_piota_type = 'Profile type specifier for iota(s)'
character(len= *), parameter ln_am_aux_s = 'Auxiliary-s parameters for mass(s)'
character(len= *), parameter ln_am_aux_f = 'Auxiliary-f parameters for mass(s)'
character(len= *), parameter ln_ac_aux_s = 'Auxiliary-s parameters for <J>(s)'
character(len= *), parameter ln_ac_aux_f = 'Auxiliary-f parameters for <J>(s)'
character(len= *), parameter ln_ai_aux_s = 'Auxiliary-s parameters for iota(s)'
character(len= *), parameter ln_ai_aux_f = 'Auxiliary-f parameters for iota(s)'
character(len= *), parameter ln_pmod = 'Poloidal mode numbers'
character(len= *), parameter ln_tmod = 'Toroidal mode numbers'
character(len= *), parameter ln_pmod_nyq = 'Poloidal mode numbers (Nyquist)'
character(len= *), parameter ln_tmod_nyq = 'Toroidal mode numbers (Nyquist)'
character(len= *), parameter ln_racc = 'raxis (cosnv)'
character(len= *), parameter ln_racs = 'raxis (sinnv)'
character(len= *), parameter ln_zacs = 'zaxis (sinnv)'
character(len= *), parameter ln_zacc = 'zaxis (cosnv)'
character(len= *), parameter ln_iotaf = 'iota on full mesh'
character(len= *), parameter ln_qfact = 'q-factor on full mesh'
character(len= *), parameter ln_presf = 'pressure on full mesh'
character(len= *), parameter ln_phi = 'Toroidal flux on full mesh'
character(len= *), parameter ln_phipf = 'd(phi)/ds: Toroidal flux deriv on full mesh'
character(len= *), parameter ln_chi = 'Poloidal flux on full mesh'
character(len= *), parameter ln_chipf = 'd(chi)/ds: Poroidal flux deriv on full mesh'
character(len= *), parameter ln_jcuru = 'j dot gradu full'
character(len= *), parameter ln_jcurv = 'j dot gradv full'
character(len= *), parameter ln_iotah = 'iota half'
character(len= *), parameter ln_mass = 'mass half'
character(len= *), parameter ln_presh = 'pressure half'
character(len= *), parameter ln_betah = 'beta half'
character(len= *), parameter ln_buco = 'bsubu half'
character(len= *), parameter ln_bvco = 'bsubv half'
character(len= *), parameter ln_vp = 'volume deriv half'
character(len= *), parameter ln_specw = 'Spectral width half'
character(len= *), parameter ln_phip = 'tor flux deriv over 2pi half'
character(len= *), parameter ln_jdotb = 'J dot B'
character(len= *), parameter ln_bgrv = 'B dot grad v'
character(len= *), parameter ln_merc = 'Mercier criterion'
character(len= *), parameter ln_mshear = 'Shear Mercier'
character(len= *), parameter ln_mwell = 'Well Mercier'
character(len= *), parameter ln_mcurr = 'Current Mercier'
character(len= *), parameter ln_mgeo = 'Geodesic Mercier'
character(len= *), parameter ln_equif ='Average force balance'
character(len= *), parameter ln_fsq = 'Residual decay'
character(len= *), parameter ln_wdot = 'Wdot decay'
character(len= *), parameter ln_extcur = 'External coil currents'
character(len= *), parameter ln_fsqr = 'Residual decay - radial'
character(len= *), parameter ln_fsqz = 'Residual decay - vertical'
character(len= *), parameter ln_fsql = 'Residual decay - hoop'
character(len= *), parameter ln_ftolv = 'Residual decay - requested'
character(len= *), parameter ln_curlab = 'External current names'
character(len= *), parameter ln_rmnc = 'cosmn component of cylindrical R, full mesh'
character(len= *), parameter ln_zmns = 'sinmn component of cylindrical Z, full mesh'
character(len= *), parameter ln_lmns = 'sinmn component of lambda, half mesh'
character(len= *), parameter ln_gmnc = 'cosmn component of jacobian, half mesh'
character(len= *), parameter ln_bmnc = 'cosmn component of mod-B, half mesh'
character(len= *), parameter ln_bsubumnc = 'cosmn covariant u-component of B, half mesh'
character(len= *), parameter ln_bsubvmnc = 'cosmn covariant v-component of B, half mesh'
character(len= *), parameter ln_bsubsmns = 'sinmn covariant s-component of B, full mesh'
character(len= *), parameter ln_bsubumnc_sur = 'cosmn bsubu of B, surface'
character(len= *), parameter ln_bsubvmnc_sur = 'cosmn bsubv of B, surface'
character(len= *), parameter ln_bsupumnc_sur = 'cosmn bsupu of B, surface'
character(len= *), parameter ln_bsupvmnc_sur = 'cosmn bsupv of B, surface'
character(len= *), parameter ln_bsupumnc = 'BSUPUmnc half'
character(len= *), parameter ln_bsupvmnc = 'BSUPVmnc half'
character(len= *), parameter ln_rmns = 'sinmn component of cylindrical R, full mesh'
character(len= *), parameter ln_zmnc = 'cosmn component of cylindrical Z, full mesh'
character(len= *), parameter ln_lmnc = 'cosmn component of lambda, half mesh'
character(len= *), parameter ln_gmns = 'sinmn component of jacobian, half mesh'
character(len= *), parameter ln_bmns = 'sinmn component of mod-B, half mesh'
character(len= *), parameter ln_bsubumns = 'sinmn covariant u-component of B, half mesh'
character(len= *), parameter ln_bsubvmns = 'sinmn covariant v-component of B, half mesh'
character(len= *), parameter ln_bsubsmnc = 'cosmn covariant s-component of B, full mesh'
character(len= *), parameter ln_bsubumns_sur = 'sinmn bsubu of B, surface'
character(len= *), parameter ln_bsubvmns_sur = 'sinmn bsubv of B, surface'
character(len= *), parameter ln_bsupumns_sur = 'sinmn bsupu of B, surface'
character(len= *), parameter ln_bsupvmns_sur = 'sinmn bsupv of B, surface'
character(len= *), parameter ln_bsupumns = 'BSUPUmns half'
character(len= *), parameter ln_bsupvmns = 'BSUPVmns half'
character(len= *), parameter ln_rbc = 'Initial boundary R cos(mu-nv) coefficients'
character(len= *), parameter ln_zbs = 'Initial boundary Z sin(mu-nv) coefficients'
character(len= *), parameter ln_rbs = 'Initial boundary R sin(mu-nv) coefficients'
character(len= *), parameter ln_zbc = 'Initial boundary Z cos(mu-nv) coefficients'
character(len= *), parameter ln_potvac = 'Vacuum Potential on Boundary'
integer nfp
integer ns
integer mpol
integer ntor
integer mnmax
integer mnmax_nyq
integer niter
integer iasym
integer ierr_vmec
integer imse
integer itse
integer isnodes
integer ipnodes
integer imatch_phiedge
integer isigng
integer mnyq
integer nnyq
integer ntmax
real(rprec) wb
real(rprec) wp
real(rprec) gamma
real(rprec) pfac
real(rprec) rmax_surf
real(rprec) rmin_surf
real(rprec) zmax_surf
real(rprec) aspect
real(rprec) betatot
real(rprec) betapol
real(rprec) betator
real(rprec) betaxis
real(rprec) b0
real(rprec) tswgt
real(rprec) msewgt
real(rprec) flmwgt
real(rprec) bcwgt
real(rprec) phidiam
real(rprec) version_
real(rprec) delphid
real(rprec) ionlarmor
real(rprec) volavgb
real(rprec) fsql
real(rprec) fsqr
real(rprec) fsqz
real(rprec) ftolv
real(rprec) aminor
real(rprec) rmajor
real(rprec) volume
real(rprec) rbtor
real(rprec) rbtor0
real(rprec) itor
real(rprec) machsq
real(rprec), dimension(:,:,:,:), allocatable rzl_local
real(rprec), dimension(:,:), allocatable rmnc
real(rprec), dimension(:,:), allocatable zmns
real(rprec), dimension(:,:), allocatable lmns
real(rprec), dimension(:,:), allocatable rmns
real(rprec), dimension(:,:), allocatable zmnc
real(rprec), dimension(:,:), allocatable lmnc
real(rprec), dimension(:,:), allocatable bmnc
real(rprec), dimension(:,:), allocatable gmnc
real(rprec), dimension(:,:), allocatable bsubumnc
real(rprec), dimension(:,:), allocatable bsubvmnc
real(rprec), dimension(:,:), allocatable bsubsmns
real(rprec), dimension(:,:), allocatable bsupumnc
real(rprec), dimension(:,:), allocatable bsupvmnc
real(rprec), dimension(:,:), allocatable currvmnc
real(rprec), dimension(:,:), allocatable currumnc
real(rprec), dimension(:,:), allocatable bbc
real(rprec), dimension(:,:), allocatable raxis
real(rprec), dimension(:,:), allocatable zaxis
real(rprec), dimension(:,:), allocatable bmns
real(rprec), dimension(:,:), allocatable gmns
real(rprec), dimension(:,:), allocatable bsubumns
real(rprec), dimension(:,:), allocatable bsubvmns
real(rprec), dimension(:,:), allocatable bsubsmnc
real(rprec), dimension(:,:), allocatable bsupumns
real(rprec), dimension(:,:), allocatable bsupvmns
real(rprec), dimension(:,:), allocatable currumns
real(rprec), dimension(:,:), allocatable currvmns
real(rprec), dimension(:), allocatable iotas
real(rprec), dimension(:), allocatable iotaf
real(rprec), dimension(:), allocatable presf
real(rprec), dimension(:), allocatable phipf
real(rprec), dimension(:), allocatable mass
real(rprec), dimension(:), allocatable pres
real(rprec), dimension(:), allocatable beta_vol
real(rprec), dimension(:), allocatable xm
real(rprec), dimension(:), allocatable xn
real(rprec), dimension(:), allocatable qfact
real(rprec), dimension(:), allocatable chipf
real(rprec), dimension(:), allocatable phi
real(rprec), dimension(:), allocatable chi
real(rprec), dimension(:), allocatable xm_nyq
real(rprec), dimension(:), allocatable xn_nyq
real(rprec), dimension(:), allocatable phip
real(rprec), dimension(:), allocatable buco
real(rprec), dimension(:), allocatable bvco
real(rprec), dimension(:), allocatable vp
real(rprec), dimension(:), allocatable overr
real(rprec), dimension(:), allocatable jcuru
real(rprec), dimension(:), allocatable jcurv
real(rprec), dimension(:), allocatable specw
real(rprec), dimension(:), allocatable jdotb
real(rprec), dimension(:), allocatable bdotgradv
real(rprec), dimension(:), allocatable fsqt
real(rprec), dimension(:), allocatable wdot
real(rprec), dimension(:), allocatable am
real(rprec), dimension(:), allocatable ac
real(rprec), dimension(:), allocatable ai
real(rprec), dimension(:), allocatable am_aux_s
real(rprec), dimension(:), allocatable am_aux_f
real(rprec), dimension(:), allocatable ac_aux_s
real(rprec), dimension(:), allocatable ac_aux_f
real(rprec), dimension(:), allocatable ai_aux_s
real(rprec), dimension(:), allocatable ai_aux_f
real(rprec), dimension(:), allocatable dmerc
real(rprec), dimension(:), allocatable dshear
real(rprec), dimension(:), allocatable dwell
real(rprec), dimension(:), allocatable dcurr
real(rprec), dimension(:), allocatable dgeod
real(rprec), dimension(:), allocatable equif
real(rprec), dimension(:), allocatable extcur
real(rprec), dimension(:), allocatable sknots
real(rprec), dimension(:), allocatable ystark
real(rprec), dimension(:), allocatable y2stark
real(rprec), dimension(:), allocatable pknots
real(rprec), dimension(:), allocatable ythom
real(rprec), dimension(:), allocatable y2thom
real(rprec), dimension(:), allocatable anglemse
real(rprec), dimension(:), allocatable rmid
real(rprec), dimension(:), allocatable qmid
real(rprec), dimension(:), allocatable shear
real(rprec), dimension(:), allocatable presmid
real(rprec), dimension(:), allocatable alfa
real(rprec), dimension(:), allocatable curmid
real(rprec), dimension(:), allocatable rstark
real(rprec), dimension(:), allocatable qmeas
real(rprec), dimension(:), allocatable datastark
real(rprec), dimension(:), allocatable rthom
real(rprec), dimension(:), allocatable datathom
real(rprec), dimension(:), allocatable dsiobt
real(rprec), dimension(:), allocatable potvac
logical lasym
logical lthreed
logical lwout_opened =.false.
character mgrid_file
character input_extension
character pmass_type
character pcurr_type
character piota_type
Detailed Description
Reading of wout VMEC output file.
Function/Subroutine Documentation
compute_currents()
subroutine read_wout_mod::compute_currents (integer, intent(out) ierror)
Definition at line 680 of file read_wout_mod.f.
References bsubsmnc, bsubsmns, bsubumnc, bsubumns, bsubvmnc, bsubvmns, currumnc, currumns, currvmnc, currvmns, lasym, mnmax_nyq, stel_constants::mu0, xm_nyq, and xn_nyq.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
loadrzl()
subroutine read_wout_mod::loadrzl
Definition at line 1072 of file read_wout_mod.f.
References chi, iotaf, lasym, lthreed, mnmax, mpol, nfp, ns, ntmax, ntor, phipf, rmnc, rmns, rzl_local, xm, xn, zmnc, and zmns.
read_wout_deallocate()
subroutine read_wout_mod::read_wout_deallocate
Definition at line 780 of file read_wout_mod.f.
References ac, ac_aux_f, ac_aux_s, ai, ai_aux_f, ai_aux_s, am, am_aux_f, am_aux_s, bdotgradv, beta_vol, bmnc, bmns, bsubsmnc, bsubsmns, bsubumnc, bsubumns, bsubvmnc, bsubvmns, bsupumnc, bsupumns, bsupvmnc, bsupvmns, buco, bvco, chi, chipf, mgrid_mod::curlabel, currumnc, currumns, currvmnc, currvmns, dcurr, dgeod, dmerc, dshear, dwell, equif, extcur, fsqt, gmnc, gmns, iotaf, iotas, jcuru, jcurv, jdotb, lmnc, lmns, lwout_opened, mass, overr, phi, phip, phipf, potvac, pres, presf, raxis, rmnc, rmns, rzl_local, specw, vp, wdot, xm, xm_nyq, xn, xn_nyq, zaxis, zmnc, and zmns.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
readw_and_open()
subroutine read_wout_mod::readw_and_open (character(len=*), intent(in) file_or_extension, integer, intent(out) ierr, integer, optional iopen)
Definition at line 249 of file read_wout_mod.f.
tosuvspace()
subroutine read_wout_mod::tosuvspace (real(rprec), intent(in) s_in, real(rprec), intent(in) u_in, real(rprec), intent(in) v_in, real(rprec), intent(out), optional gsqrt, real(rprec), intent(out), optional bsupu, real(rprec), intent(out), optional bsupv, real(rprec), intent(out), optional jsupu, real(rprec), intent(out), optional jsupv, real(rprec), intent(out), optional lam)
Definition at line 826 of file read_wout_mod.f.
References bsupumnc, bsupumns, bsupvmnc, bsupvmns, currumnc, currumns, currvmnc, currvmns, gmnc, gmns, lasym, lmnc, lmns, lwout_opened, mnmax_nyq, nfp, nnyq, ns, stel_constants::one, xm_nyq, xn_nyq, and stel_constants::zero.
Variable Documentation
ac
real(rprec), dimension(:), allocatable read_wout_mod::ac
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ac_aux_f
real(rprec), dimension(:), allocatable read_wout_mod::ac_aux_f
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ac_aux_s
real(rprec), dimension(:), allocatable read_wout_mod::ac_aux_s
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ai
real(rprec), dimension(:), allocatable read_wout_mod::ai
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ai_aux_f
real(rprec), dimension(:), allocatable read_wout_mod::ai_aux_f
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ai_aux_s
real(rprec), dimension(:), allocatable read_wout_mod::ai_aux_s
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
alfa
real(rprec), dimension(:), allocatable read_wout_mod::alfa
Definition at line 219 of file read_wout_mod.f.
am
real(rprec), dimension(:), allocatable read_wout_mod::am
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
am_aux_f
real(rprec), dimension(:), allocatable read_wout_mod::am_aux_f
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
am_aux_s
real(rprec), dimension(:), allocatable read_wout_mod::am_aux_s
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
aminor
real(rprec) read_wout_mod::aminor
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
anglemse
real(rprec), dimension(:), allocatable read_wout_mod::anglemse
Definition at line 219 of file read_wout_mod.f.
aspect
real(rprec) read_wout_mod::aspect
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
b0
real(rprec) read_wout_mod::b0
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
bbc
real(rprec), dimension(:,:), allocatable read_wout_mod::bbc
Definition at line 212 of file read_wout_mod.f.
bcwgt
real(rprec) read_wout_mod::bcwgt
Definition at line 204 of file read_wout_mod.f.
bdotgradv
real(rprec), dimension(:), allocatable read_wout_mod::bdotgradv
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
beta_vol
real(rprec), dimension(:), allocatable read_wout_mod::beta_vol
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
betapol
real(rprec) read_wout_mod::betapol
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
betator
real(rprec) read_wout_mod::betator
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
betatot
real(rprec) read_wout_mod::betatot
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
betaxis
real(rprec) read_wout_mod::betaxis
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
bmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bmns
real(rprec), dimension(:,:), allocatable read_wout_mod::bmns
Definition at line 216 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubsmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubsmnc
Definition at line 216 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubsmns
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubsmns
Definition at line 212 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubumnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubumnc
Definition at line 212 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubumns
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubumns
Definition at line 216 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubvmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubvmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsubvmns
real(rprec), dimension(:,:), allocatable read_wout_mod::bsubvmns
Definition at line 216 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bsupumnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bsupumnc
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
bsupumns
real(rprec), dimension(:,:), allocatable read_wout_mod::bsupumns
Definition at line 216 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
bsupvmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::bsupvmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
bsupvmns
real(rprec), dimension(:,:), allocatable read_wout_mod::bsupvmns
Definition at line 216 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
buco
real(rprec), dimension(:), allocatable read_wout_mod::buco
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
bvco
real(rprec), dimension(:), allocatable read_wout_mod::bvco
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
chi
real(rprec), dimension(:), allocatable read_wout_mod::chi
Definition at line 219 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
chipf
real(rprec), dimension(:), allocatable read_wout_mod::chipf
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
curmid
real(rprec), dimension(:), allocatable read_wout_mod::curmid
Definition at line 219 of file read_wout_mod.f.
currumnc
real(rprec), dimension(:,:), allocatable read_wout_mod::currumnc
Definition at line 212 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and tosuvspace().
currumns
real(rprec), dimension(:,:), allocatable read_wout_mod::currumns
Definition at line 216 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and tosuvspace().
currvmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::currvmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and tosuvspace().
currvmns
real(rprec), dimension(:,:), allocatable read_wout_mod::currvmns
Definition at line 216 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), and tosuvspace().
datastark
real(rprec), dimension(:), allocatable read_wout_mod::datastark
Definition at line 219 of file read_wout_mod.f.
datathom
real(rprec), dimension(:), allocatable read_wout_mod::datathom
Definition at line 219 of file read_wout_mod.f.
dcurr
real(rprec), dimension(:), allocatable read_wout_mod::dcurr
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
delphid
real(rprec) read_wout_mod::delphid
Definition at line 204 of file read_wout_mod.f.
dgeod
real(rprec), dimension(:), allocatable read_wout_mod::dgeod
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
dmerc
real(rprec), dimension(:), allocatable read_wout_mod::dmerc
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
dshear
real(rprec), dimension(:), allocatable read_wout_mod::dshear
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
dsiobt
real(rprec), dimension(:), allocatable read_wout_mod::dsiobt
Definition at line 219 of file read_wout_mod.f.
dwell
real(rprec), dimension(:), allocatable read_wout_mod::dwell
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
equif
real(rprec), dimension(:), allocatable read_wout_mod::equif
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
extcur
real(rprec), dimension(:), allocatable read_wout_mod::extcur
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
flmwgt
real(rprec) read_wout_mod::flmwgt
Definition at line 204 of file read_wout_mod.f.
fsql
real(rprec) read_wout_mod::fsql
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
fsqr
real(rprec) read_wout_mod::fsqr
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
fsqt
real(rprec), dimension(:), allocatable read_wout_mod::fsqt
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
fsqz
real(rprec) read_wout_mod::fsqz
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
ftolv
real(rprec) read_wout_mod::ftolv
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
gamma
real(rprec) read_wout_mod::gamma
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
gmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::gmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
gmns
real(rprec), dimension(:,:), allocatable read_wout_mod::gmns
Definition at line 216 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
iasym
integer read_wout_mod::iasym
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
ierr_vmec
integer read_wout_mod::ierr_vmec
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
imatch_phiedge
integer read_wout_mod::imatch_phiedge
Definition at line 201 of file read_wout_mod.f.
imse
integer read_wout_mod::imse
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
input_extension
character read_wout_mod::input_extension
Definition at line 231 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
ionlarmor
real(rprec) read_wout_mod::ionlarmor
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
iotaf
real(rprec), dimension(:), allocatable read_wout_mod::iotaf
Definition at line 219 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
iotas
real(rprec), dimension(:), allocatable read_wout_mod::iotas
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
ipnodes
integer read_wout_mod::ipnodes
Definition at line 201 of file read_wout_mod.f.
isigng
integer read_wout_mod::isigng
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
isnodes
integer read_wout_mod::isnodes
Definition at line 201 of file read_wout_mod.f.
itor
real(rprec) read_wout_mod::itor
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
itse
integer read_wout_mod::itse
Definition at line 201 of file read_wout_mod.f.
jcuru
real(rprec), dimension(:), allocatable read_wout_mod::jcuru
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
jcurv
real(rprec), dimension(:), allocatable read_wout_mod::jcurv
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
jdotb
real(rprec), dimension(:), allocatable read_wout_mod::jdotb
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
lasym
logical read_wout_mod::lasym
Definition at line 230 of file read_wout_mod.f.
Referenced by compute_currents(), loadrzl(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
lmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::lmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
lmns
real(rprec), dimension(:,:), allocatable read_wout_mod::lmns
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
ln_abeta
character(len=*), parameter read_wout_mod::ln_abeta = 'Beta axis'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ac
character(len=*), parameter read_wout_mod::ln_ac = 'Specification parameters for <J>(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ac_aux_f
character(len=*), parameter read_wout_mod::ln_ac_aux_f = 'Auxiliary-f parameters for <J>(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ac_aux_s
character(len=*), parameter read_wout_mod::ln_ac_aux_s = 'Auxiliary-s parameters for <J>(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ai
character(len=*), parameter read_wout_mod::ln_ai = 'Specification parameters for iota(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ai_aux_f
character(len=*), parameter read_wout_mod::ln_ai_aux_f = 'Auxiliary-f parameters for iota(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ai_aux_s
character(len=*), parameter read_wout_mod::ln_ai_aux_s = 'Auxiliary-s parameters for iota(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_am
character(len=*), parameter read_wout_mod::ln_am = 'Specification parameters for mass(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_am_aux_f
character(len=*), parameter read_wout_mod::ln_am_aux_f = 'Auxiliary-f parameters for mass(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_am_aux_s
character(len=*), parameter read_wout_mod::ln_am_aux_s = 'Auxiliary-s parameters for mass(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_amin
character(len=*), parameter read_wout_mod::ln_amin = 'minor radius'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_aspect
character(len=*), parameter read_wout_mod::ln_aspect = 'Aspect ratio'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_asym
character(len=*), parameter read_wout_mod::ln_asym = 'Asymmetry'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_b0
character(len=*), parameter read_wout_mod::ln_b0 = 'RB-t over R axis'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_beta
character(len=*), parameter read_wout_mod::ln_beta = 'Total beta'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_betah
character(len=*), parameter read_wout_mod::ln_betah = 'beta half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bgrv
character(len=*), parameter read_wout_mod::ln_bgrv = 'B dot grad v'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bmnc
character(len=*), parameter read_wout_mod::ln_bmnc = 'cosmn component of mod-B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bmns
character(len=*), parameter read_wout_mod::ln_bmns = 'sinmn component of mod-B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubsmnc
character(len=*), parameter read_wout_mod::ln_bsubsmnc = 'cosmn covariant s-component of B, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubsmns
character(len=*), parameter read_wout_mod::ln_bsubsmns = 'sinmn covariant s-component of B, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubumnc
character(len=*), parameter read_wout_mod::ln_bsubumnc = 'cosmn covariant u-component of B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubumnc_sur
character(len=*), parameter read_wout_mod::ln_bsubumnc_sur = 'cosmn bsubu of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsubumns
character(len=*), parameter read_wout_mod::ln_bsubumns = 'sinmn covariant u-component of B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubumns_sur
character(len=*), parameter read_wout_mod::ln_bsubumns_sur = 'sinmn bsubu of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsubvmnc
character(len=*), parameter read_wout_mod::ln_bsubvmnc = 'cosmn covariant v-component of B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubvmnc_sur
character(len=*), parameter read_wout_mod::ln_bsubvmnc_sur = 'cosmn bsubv of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsubvmns
character(len=*), parameter read_wout_mod::ln_bsubvmns = 'sinmn covariant v-component of B, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsubvmns_sur
character(len=*), parameter read_wout_mod::ln_bsubvmns_sur = 'sinmn bsubv of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsupumnc
character(len=*), parameter read_wout_mod::ln_bsupumnc = 'BSUPUmnc half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsupumnc_sur
character(len=*), parameter read_wout_mod::ln_bsupumnc_sur = 'cosmn bsupu of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsupumns
character(len=*), parameter read_wout_mod::ln_bsupumns = 'BSUPUmns half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsupumns_sur
character(len=*), parameter read_wout_mod::ln_bsupumns_sur = 'sinmn bsupu of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsupvmnc
character(len=*), parameter read_wout_mod::ln_bsupvmnc = 'BSUPVmnc half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsupvmnc_sur
character(len=*), parameter read_wout_mod::ln_bsupvmnc_sur = 'cosmn bsupv of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_bsupvmns
character(len=*), parameter read_wout_mod::ln_bsupvmns = 'BSUPVmns half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bsupvmns_sur
character(len=*), parameter read_wout_mod::ln_bsupvmns_sur = 'sinmn bsupv of B, surface'
Definition at line 94 of file read_wout_mod.f.
ln_buco
character(len=*), parameter read_wout_mod::ln_buco = 'bsubu half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_bvco
character(len=*), parameter read_wout_mod::ln_bvco = 'bsubv half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_chi
character(len=*), parameter read_wout_mod::ln_chi = 'Poloidal flux on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_chipf
character(len=*), parameter read_wout_mod::ln_chipf = 'd(chi)/ds: Poroidal flux deriv on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_ctor
character(len=*), parameter read_wout_mod::ln_ctor = 'Toroidal current'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_curlab
character(len=*), parameter read_wout_mod::ln_curlab = 'External current names'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_equif
character(len=*), parameter read_wout_mod::ln_equif ='Average force balance'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_error
character(len=*), parameter read_wout_mod::ln_error = 'Error flag'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_extcur
character(len=*), parameter read_wout_mod::ln_extcur = 'External coil currents'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_extension
character(len=*), parameter read_wout_mod::ln_extension = 'Input file extension'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_fp
character(len=*), parameter read_wout_mod::ln_fp = 'Field Periods'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_free
character(len=*), parameter read_wout_mod::ln_free = 'Free boundary'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_fsq
character(len=*), parameter read_wout_mod::ln_fsq = 'Residual decay'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_fsql
character(len=*), parameter read_wout_mod::ln_fsql = 'Residual decay - hoop'
Definition at line 94 of file read_wout_mod.f.
ln_fsqr
character(len=*), parameter read_wout_mod::ln_fsqr = 'Residual decay - radial'
Definition at line 94 of file read_wout_mod.f.
ln_fsqz
character(len=*), parameter read_wout_mod::ln_fsqz = 'Residual decay - vertical'
Definition at line 94 of file read_wout_mod.f.
ln_ftolv
character(len=*), parameter read_wout_mod::ln_ftolv = 'Residual decay - requested'
Definition at line 94 of file read_wout_mod.f.
ln_gam
character(len=*), parameter read_wout_mod::ln_gam = 'Gamma'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_gmnc
character(len=*), parameter read_wout_mod::ln_gmnc = 'cosmn component of jacobian, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_gmns
character(len=*), parameter read_wout_mod::ln_gmns = 'sinmn component of jacobian, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_iotaf
character(len=*), parameter read_wout_mod::ln_iotaf = 'iota on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_iotah
character(len=*), parameter read_wout_mod::ln_iotah = 'iota half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_jcuru
character(len=*), parameter read_wout_mod::ln_jcuru = 'j dot gradu full'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_jcurv
character(len=*), parameter read_wout_mod::ln_jcurv = 'j dot gradv full'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_jdotb
character(len=*), parameter read_wout_mod::ln_jdotb = 'J dot B'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_lar
character(len=*), parameter read_wout_mod::ln_lar = 'Ion Larmor radius'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_lmnc
character(len=*), parameter read_wout_mod::ln_lmnc = 'cosmn component of lambda, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_lmns
character(len=*), parameter read_wout_mod::ln_lmns = 'sinmn component of lambda, half mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_magen
character(len=*), parameter read_wout_mod::ln_magen = 'Magnetic Energy'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mass
character(len=*), parameter read_wout_mod::ln_mass = 'mass half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_maxit
character(len=*), parameter read_wout_mod::ln_maxit = 'Max iterations'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_maxmod
character(len=*), parameter read_wout_mod::ln_maxmod = 'Fourier modes'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_maxmod_nyq
character(len=*), parameter read_wout_mod::ln_maxmod_nyq = 'Fourier modes (Nyquist)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_maxr
character(len=*), parameter read_wout_mod::ln_maxr = 'Maximum R'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_maxz
character(len=*), parameter read_wout_mod::ln_maxz = 'Maximum Z'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mcurr
character(len=*), parameter read_wout_mod::ln_mcurr = 'Current Mercier'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_merc
character(len=*), parameter read_wout_mod::ln_merc = 'Mercier criterion'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mgeo
character(len=*), parameter read_wout_mod::ln_mgeo = 'Geodesic Mercier'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mgrid
character(len=*), parameter read_wout_mod::ln_mgrid = 'MGRID file'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_minr
character(len=*), parameter read_wout_mod::ln_minr = 'Minimum R'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_modb
character(len=*), parameter read_wout_mod::ln_modb = 'avg mod B'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mse
character(len=*), parameter read_wout_mod::ln_mse = 'Number of MSE points'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mshear
character(len=*), parameter read_wout_mod::ln_mshear = 'Shear Mercier'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_mwell
character(len=*), parameter read_wout_mod::ln_mwell = 'Well Mercier'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_pbeta
character(len=*), parameter read_wout_mod::ln_pbeta = 'Poloidal beta'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_pcurr_type
character(len=*), parameter read_wout_mod::ln_pcurr_type = 'Profile type specifier for <J>(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_phi
character(len=*), parameter read_wout_mod::ln_phi = 'Toroidal flux on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_phip
character(len=*), parameter read_wout_mod::ln_phip = 'tor flux deriv over 2pi half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_phipf
character(len=*), parameter read_wout_mod::ln_phipf = 'd(phi)/ds: Toroidal flux deriv on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_piota_type
character(len=*), parameter read_wout_mod::ln_piota_type = 'Profile type specifier for iota(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_pmass_type
character(len=*), parameter read_wout_mod::ln_pmass_type = 'Profile type specifier for mass(s)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_pmod
character(len=*), parameter read_wout_mod::ln_pmod = 'Poloidal mode numbers'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_pmod_nyq
character(len=*), parameter read_wout_mod::ln_pmod_nyq = 'Poloidal mode numbers (Nyquist)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_polmod
character(len=*), parameter read_wout_mod::ln_polmod = 'Poloidal modes'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_potvac
character(len=*), parameter read_wout_mod::ln_potvac = 'Vacuum Potential on Boundary'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_presf
character(len=*), parameter read_wout_mod::ln_presf = 'pressure on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_presh
character(len=*), parameter read_wout_mod::ln_presh = 'pressure half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_qfact
character(len=*), parameter read_wout_mod::ln_qfact = 'q-factor on full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_racc
character(len=*), parameter read_wout_mod::ln_racc = 'raxis (cosnv)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_racs
character(len=*), parameter read_wout_mod::ln_racs = 'raxis (sinnv)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_radnod
character(len=*), parameter read_wout_mod::ln_radnod = 'Radial nodes'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rbc
character(len=*), parameter read_wout_mod::ln_rbc = 'Initial boundary R cos(mu-nv) coefficients'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rbs
character(len=*), parameter read_wout_mod::ln_rbs = 'Initial boundary R sin(mu-nv) coefficients'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rbt0
character(len=*), parameter read_wout_mod::ln_rbt0 = 'RB-t axis'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rbt1
character(len=*), parameter read_wout_mod::ln_rbt1 = 'RB-t edge'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_recon
character(len=*), parameter read_wout_mod::ln_recon = 'Reconstruction'
Definition at line 94 of file read_wout_mod.f.
ln_rmaj
character(len=*), parameter read_wout_mod::ln_rmaj = 'major radius'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rmnc
character(len=*), parameter read_wout_mod::ln_rmnc = 'cosmn component of cylindrical R, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_rmns
character(len=*), parameter read_wout_mod::ln_rmns = 'sinmn component of cylindrical R, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_sgs
character(len=*), parameter read_wout_mod::ln_sgs = 'Sign jacobian'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_specw
character(len=*), parameter read_wout_mod::ln_specw = 'Spectral width half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_tbeta
character(len=*), parameter read_wout_mod::ln_tbeta = 'Toroidal beta'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_therm
character(len=*), parameter read_wout_mod::ln_therm = 'Thermal Energy'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_thom
character(len=*), parameter read_wout_mod::ln_thom = 'Number of Thompson scattering points'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_tmod
character(len=*), parameter read_wout_mod::ln_tmod = 'Toroidal mode numbers'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_tmod_nyq
character(len=*), parameter read_wout_mod::ln_tmod_nyq = 'Toroidal mode numbers (Nyquist)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_tormod
character(len=*), parameter read_wout_mod::ln_tormod = 'Toroidal modes'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_version
character(len=*), parameter read_wout_mod::ln_version = 'VMEC Version'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_vol
character(len=*), parameter read_wout_mod::ln_vol = 'Plasma volume'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_vp
character(len=*), parameter read_wout_mod::ln_vp = 'volume deriv half'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_wdot
character(len=*), parameter read_wout_mod::ln_wdot = 'Wdot decay'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zacc
character(len=*), parameter read_wout_mod::ln_zacc = 'zaxis (cosnv)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zacs
character(len=*), parameter read_wout_mod::ln_zacs = 'zaxis (sinnv)'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zbc
character(len=*), parameter read_wout_mod::ln_zbc = 'Initial boundary Z cos(mu-nv) coefficients'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zbs
character(len=*), parameter read_wout_mod::ln_zbs = 'Initial boundary Z sin(mu-nv) coefficients'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zmnc
character(len=*), parameter read_wout_mod::ln_zmnc = 'cosmn component of cylindrical Z, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
ln_zmns
character(len=*), parameter read_wout_mod::ln_zmns = 'sinmn component of cylindrical Z, full mesh'
Definition at line 94 of file read_wout_mod.f.
Referenced by wrout().
lthreed
logical read_wout_mod::lthreed
Definition at line 230 of file read_wout_mod.f.
Referenced by loadrzl(), and read_wout_mod::read_wout_file::readw_and_open().
lwout_opened
logical read_wout_mod::lwout_opened =.false.
Definition at line 230 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
machsq
real(rprec) read_wout_mod::machsq
Definition at line 204 of file read_wout_mod.f.
mass
real(rprec), dimension(:), allocatable read_wout_mod::mass
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
mgrid_file
character read_wout_mod::mgrid_file
Definition at line 231 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
mnmax
integer read_wout_mod::mnmax
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_mod::read_wout_file::readw_and_open(), and wrout().
mnmax_nyq
integer read_wout_mod::mnmax_nyq
Definition at line 201 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_mod::read_wout_file::readw_and_open(), tosuvspace(), and wrout().
mnyq
integer read_wout_mod::mnyq
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
mpol
integer read_wout_mod::mpol
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl(), and read_wout_mod::read_wout_file::readw_and_open().
msewgt
real(rprec) read_wout_mod::msewgt
Definition at line 204 of file read_wout_mod.f.
nfp
integer read_wout_mod::nfp
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
niter
integer read_wout_mod::niter
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
nnyq
integer read_wout_mod::nnyq
Definition at line 201 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
ns
integer read_wout_mod::ns
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
ntmax
integer read_wout_mod::ntmax
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl().
ntor
integer read_wout_mod::ntor
Definition at line 201 of file read_wout_mod.f.
Referenced by loadrzl(), and read_wout_mod::read_wout_file::readw_and_open().
overr
real(rprec), dimension(:), allocatable read_wout_mod::overr
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
pcurr_type
character read_wout_mod::pcurr_type
Definition at line 232 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
pfac
real(rprec) read_wout_mod::pfac
Definition at line 204 of file read_wout_mod.f.
phi
real(rprec), dimension(:), allocatable read_wout_mod::phi
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
phidiam
real(rprec) read_wout_mod::phidiam
Definition at line 204 of file read_wout_mod.f.
phip
real(rprec), dimension(:), allocatable read_wout_mod::phip
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
phipf
real(rprec), dimension(:), allocatable read_wout_mod::phipf
Definition at line 219 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
piota_type
character read_wout_mod::piota_type
Definition at line 232 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
pknots
real(rprec), dimension(:), allocatable read_wout_mod::pknots
Definition at line 219 of file read_wout_mod.f.
pmass_type
character read_wout_mod::pmass_type
Definition at line 232 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
potvac
real(rprec), dimension(:), allocatable read_wout_mod::potvac
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
pres
real(rprec), dimension(:), allocatable read_wout_mod::pres
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
presf
real(rprec), dimension(:), allocatable read_wout_mod::presf
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
presmid
real(rprec), dimension(:), allocatable read_wout_mod::presmid
Definition at line 219 of file read_wout_mod.f.
qfact
real(rprec), dimension(:), allocatable read_wout_mod::qfact
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
qmeas
real(rprec), dimension(:), allocatable read_wout_mod::qmeas
Definition at line 219 of file read_wout_mod.f.
qmid
real(rprec), dimension(:), allocatable read_wout_mod::qmid
Definition at line 219 of file read_wout_mod.f.
raxis
real(rprec), dimension(:,:), allocatable read_wout_mod::raxis
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
rbtor
real(rprec) read_wout_mod::rbtor
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
rbtor0
real(rprec) read_wout_mod::rbtor0
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
rmajor
real(rprec) read_wout_mod::rmajor
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
rmax_surf
real(rprec) read_wout_mod::rmax_surf
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
rmid
real(rprec), dimension(:), allocatable read_wout_mod::rmid
Definition at line 219 of file read_wout_mod.f.
rmin_surf
real(rprec) read_wout_mod::rmin_surf
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
rmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::rmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
rmns
real(rprec), dimension(:,:), allocatable read_wout_mod::rmns
Definition at line 212 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
rstark
real(rprec), dimension(:), allocatable read_wout_mod::rstark
Definition at line 219 of file read_wout_mod.f.
rthom
real(rprec), dimension(:), allocatable read_wout_mod::rthom
Definition at line 219 of file read_wout_mod.f.
rzl_local
real(rprec), dimension(:,:,:,:), allocatable read_wout_mod::rzl_local
Definition at line 211 of file read_wout_mod.f.
Referenced by loadrzl(), and read_wout_deallocate().
shear
real(rprec), dimension(:), allocatable read_wout_mod::shear
Definition at line 219 of file read_wout_mod.f.
sknots
real(rprec), dimension(:), allocatable read_wout_mod::sknots
Definition at line 219 of file read_wout_mod.f.
specw
real(rprec), dimension(:), allocatable read_wout_mod::specw
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
tswgt
real(rprec) read_wout_mod::tswgt
Definition at line 204 of file read_wout_mod.f.
version_
real(rprec) read_wout_mod::version_
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
vn_abeta
character(len=*), parameter read_wout_mod::vn_abeta = 'betaxis'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ac
character(len=*), parameter read_wout_mod::vn_ac = 'ac'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ac_aux_f
character(len=*), parameter read_wout_mod::vn_ac_aux_f = 'ac_aux_f'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ac_aux_s
character(len=*), parameter read_wout_mod::vn_ac_aux_s = 'ac_aux_s'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ah
character(len=*), parameter read_wout_mod::vn_ah = 'hot particle fraction'
Definition at line 32 of file read_wout_mod.f.
vn_ai
character(len=*), parameter read_wout_mod::vn_ai = 'ai'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ai_aux_f
character(len=*), parameter read_wout_mod::vn_ai_aux_f = 'ai_aux_f'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ai_aux_s
character(len=*), parameter read_wout_mod::vn_ai_aux_s = 'ai_aux_s'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_am
character(len=*), parameter read_wout_mod::vn_am = 'am'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_am_aux_f
character(len=*), parameter read_wout_mod::vn_am_aux_f = 'am_aux_f'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_am_aux_s
character(len=*), parameter read_wout_mod::vn_am_aux_s = 'am_aux_s'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_amin
character(len=*), parameter read_wout_mod::vn_amin = 'Aminor_p'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_aspect
character(len=*), parameter read_wout_mod::vn_aspect = 'aspect'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_asym
character(len=*), parameter read_wout_mod::vn_asym = 'lasym'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_atuname
character(len=*), parameter read_wout_mod::vn_atuname = 'T-perp/T-par'
Definition at line 32 of file read_wout_mod.f.
vn_b0
character(len=*), parameter read_wout_mod::vn_b0 = 'b0'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_beta
character(len=*), parameter read_wout_mod::vn_beta = 'betatotal'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_betah
character(len=*), parameter read_wout_mod::vn_betah = 'beta_vol'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bgrv
character(len=*), parameter read_wout_mod::vn_bgrv = 'bdotgradv'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bmnc
character(len=*), parameter read_wout_mod::vn_bmnc = 'bmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bmns
character(len=*), parameter read_wout_mod::vn_bmns = 'bmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubsmnc
character(len=*), parameter read_wout_mod::vn_bsubsmnc = 'bsubsmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubsmns
character(len=*), parameter read_wout_mod::vn_bsubsmns = 'bsubsmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubumnc
character(len=*), parameter read_wout_mod::vn_bsubumnc = 'bsubumnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubumnc_sur
character(len=*), parameter read_wout_mod::vn_bsubumnc_sur = 'bsubumnc_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsubumns
character(len=*), parameter read_wout_mod::vn_bsubumns = 'bsubumns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubumns_sur
character(len=*), parameter read_wout_mod::vn_bsubumns_sur = 'bsubumns_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsubvmnc
character(len=*), parameter read_wout_mod::vn_bsubvmnc = 'bsubvmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubvmnc_sur
character(len=*), parameter read_wout_mod::vn_bsubvmnc_sur = 'bsubvmnc_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsubvmns
character(len=*), parameter read_wout_mod::vn_bsubvmns = 'bsubvmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsubvmns_sur
character(len=*), parameter read_wout_mod::vn_bsubvmns_sur = 'bsubvmns_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsupumnc
character(len=*), parameter read_wout_mod::vn_bsupumnc = 'bsupumnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsupumnc_sur
character(len=*), parameter read_wout_mod::vn_bsupumnc_sur = 'bsupumnc_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsupumns
character(len=*), parameter read_wout_mod::vn_bsupumns = 'bsupumns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsupumns_sur
character(len=*), parameter read_wout_mod::vn_bsupumns_sur = 'bsupumns_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsupvmnc
character(len=*), parameter read_wout_mod::vn_bsupvmnc = 'bsupvmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsupvmnc_sur
character(len=*), parameter read_wout_mod::vn_bsupvmnc_sur = 'bsupvmnc_sur'
Definition at line 32 of file read_wout_mod.f.
vn_bsupvmns
character(len=*), parameter read_wout_mod::vn_bsupvmns = 'bsupvmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bsupvmns_sur
character(len=*), parameter read_wout_mod::vn_bsupvmns_sur = 'bsupvmns_sur'
Definition at line 32 of file read_wout_mod.f.
vn_buco
character(len=*), parameter read_wout_mod::vn_buco = 'buco'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_bvco
character(len=*), parameter read_wout_mod::vn_bvco = 'bvco'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_chi
character(len=*), parameter read_wout_mod::vn_chi ='chi'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_chipf
character(len=*), parameter read_wout_mod::vn_chipf ='chipf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ctor
character(len=*), parameter read_wout_mod::vn_ctor = 'ctor'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_curlab
character(len=*), parameter read_wout_mod::vn_curlab = 'curlabel'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_equif
character(len=*), parameter read_wout_mod::vn_equif = 'equif'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_error
character(len=*), parameter read_wout_mod::vn_error = 'ier_flag'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_extcur
character(len=*), parameter read_wout_mod::vn_extcur = 'extcur'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_extension
character(len=*), parameter read_wout_mod::vn_extension = 'input_extension'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_fp
character(len=*), parameter read_wout_mod::vn_fp = 'nfp'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_free
character(len=*), parameter read_wout_mod::vn_free = 'lfreeb'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_fsq
character(len=*), parameter read_wout_mod::vn_fsq = 'fsqt'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_fsql
character(len=*), parameter read_wout_mod::vn_fsql = 'fsql'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_fsqr
character(len=*), parameter read_wout_mod::vn_fsqr = 'fsqr'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_fsqz
character(len=*), parameter read_wout_mod::vn_fsqz = 'fsqz'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_ftolv
character(len=*), parameter read_wout_mod::vn_ftolv = 'ftolv'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_gam
character(len=*), parameter read_wout_mod::vn_gam = 'gamma'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_gmnc
character(len=*), parameter read_wout_mod::vn_gmnc = 'gmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_gmns
character(len=*), parameter read_wout_mod::vn_gmns = 'gmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_iotaf
character(len=*), parameter read_wout_mod::vn_iotaf = 'iotaf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_iotah
character(len=*), parameter read_wout_mod::vn_iotah = 'iotas'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_jcuru
character(len=*), parameter read_wout_mod::vn_jcuru = 'jcuru'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_jcurv
character(len=*), parameter read_wout_mod::vn_jcurv = 'jcurv'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_jdotb
character(len=*), parameter read_wout_mod::vn_jdotb = 'jdotb'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_lar
character(len=*), parameter read_wout_mod::vn_lar = 'IonLarmor'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_lmnc
character(len=*), parameter read_wout_mod::vn_lmnc = 'lmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_lmns
character(len=*), parameter read_wout_mod::vn_lmns = 'lmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_magen
character(len=*), parameter read_wout_mod::vn_magen = 'wb'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mass
character(len=*), parameter read_wout_mod::vn_mass = 'mass'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_maxit
character(len=*), parameter read_wout_mod::vn_maxit = 'niter'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_maxmod
character(len=*), parameter read_wout_mod::vn_maxmod = 'mnmax'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_maxmod_nyq
character(len=*), parameter read_wout_mod::vn_maxmod_nyq = 'mnmax_nyq'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_maxr
character(len=*), parameter read_wout_mod::vn_maxr = 'rmax_surf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_maxz
character(len=*), parameter read_wout_mod::vn_maxz = 'zmax_surf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mcurr
character(len=*), parameter read_wout_mod::vn_mcurr = 'DCurr'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_merc
character(len=*), parameter read_wout_mod::vn_merc = 'DMerc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mgeo
character(len=*), parameter read_wout_mod::vn_mgeo = 'DGeod'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mgrid
character(len=*), parameter read_wout_mod::vn_mgrid = 'mgrid_file'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_minr
character(len=*), parameter read_wout_mod::vn_minr = 'rmin_surf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_modb
character(len=*), parameter read_wout_mod::vn_modb = 'volavgB'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mse
character(len=*), parameter read_wout_mod::vn_mse = 'imse'
Definition at line 32 of file read_wout_mod.f.
vn_mshear
character(len=*), parameter read_wout_mod::vn_mshear = 'DShear'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_mwell
character(len=*), parameter read_wout_mod::vn_mwell = 'DWell'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_overr
character(len=*), parameter read_wout_mod::vn_overr = 'over_r'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_pbeta
character(len=*), parameter read_wout_mod::vn_pbeta = 'betapol'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_pcurr_type
character(len=*), parameter read_wout_mod::vn_pcurr_type = 'pcurr_type'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_phi
character(len=*), parameter read_wout_mod::vn_phi = 'phi'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_phip
character(len=*), parameter read_wout_mod::vn_phip = 'phips'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_phipf
character(len=*), parameter read_wout_mod::vn_phipf = 'phipf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_piota_type
character(len=*), parameter read_wout_mod::vn_piota_type = 'piota_type'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_pmass_type
character(len=*), parameter read_wout_mod::vn_pmass_type = 'pmass_type'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_pmod
character(len=*), parameter read_wout_mod::vn_pmod = 'xm'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_pmod_nyq
character(len=*), parameter read_wout_mod::vn_pmod_nyq = 'xm_nyq'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_polmod
character(len=*), parameter read_wout_mod::vn_polmod = 'mpol'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_potvac
character(len=*), parameter read_wout_mod::vn_potvac = 'potvac'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_presf
character(len=*), parameter read_wout_mod::vn_presf = 'presf'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_presh
character(len=*), parameter read_wout_mod::vn_presh = 'pres'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_qfact
character(len=*), parameter read_wout_mod::vn_qfact ='q-factor'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_racc
character(len=*), parameter read_wout_mod::vn_racc = 'raxis_cc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_racs
character(len=*), parameter read_wout_mod::vn_racs = 'raxis_cs'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_radnod
character(len=*), parameter read_wout_mod::vn_radnod = 'ns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_rbc
character(len=*), parameter read_wout_mod::vn_rbc = 'rbc'
Definition at line 32 of file read_wout_mod.f.
Referenced by wrout().
vn_rbs
character(len=*), parameter read_wout_mod::vn_rbs = 'rbs'
Definition at line 32 of file read_wout_mod.f.
Referenced by wrout().
vn_rbt0
character(len=*), parameter read_wout_mod::vn_rbt0 = 'rbtor0'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_rbt1
character(len=*), parameter read_wout_mod::vn_rbt1 = 'rbtor'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_rmaj
character(len=*), parameter read_wout_mod::vn_rmaj = 'Rmajor_p'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_rmnc
character(len=*), parameter read_wout_mod::vn_rmnc = 'rmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_rmns
character(len=*), parameter read_wout_mod::vn_rmns = 'rmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_sgs
character(len=*), parameter read_wout_mod::vn_sgs = 'signgs'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_specw
character(len=*), parameter read_wout_mod::vn_specw = 'specw'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_tbeta
character(len=*), parameter read_wout_mod::vn_tbeta = 'betator'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_therm
character(len=*), parameter read_wout_mod::vn_therm = 'wp'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_thom
character(len=*), parameter read_wout_mod::vn_thom = 'itse'
Definition at line 32 of file read_wout_mod.f.
vn_tmod
character(len=*), parameter read_wout_mod::vn_tmod = 'xn'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_tmod_nyq
character(len=*), parameter read_wout_mod::vn_tmod_nyq = 'xn_nyq'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_tormod
character(len=*), parameter read_wout_mod::vn_tormod = 'ntor'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_version
character(len=*), parameter read_wout_mod::vn_version = 'version_'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_vol
character(len=*), parameter read_wout_mod::vn_vol = 'volume_p'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_vp
character(len=*), parameter read_wout_mod::vn_vp = 'vp'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_wdot
character(len=*), parameter read_wout_mod::vn_wdot = 'wdot'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_zacc
character(len=*), parameter read_wout_mod::vn_zacc = 'zaxis_cc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_zacs
character(len=*), parameter read_wout_mod::vn_zacs = 'zaxis_cs'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_zbc
character(len=*), parameter read_wout_mod::vn_zbc = 'zbc'
Definition at line 32 of file read_wout_mod.f.
Referenced by wrout().
vn_zbs
character(len=*), parameter read_wout_mod::vn_zbs = 'zbs'
Definition at line 32 of file read_wout_mod.f.
Referenced by wrout().
vn_zmnc
character(len=*), parameter read_wout_mod::vn_zmnc = 'zmnc'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
vn_zmns
character(len=*), parameter read_wout_mod::vn_zmns = 'zmns'
Definition at line 32 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open(), and wrout().
volavgb
real(rprec) read_wout_mod::volavgb
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
volume
real(rprec) read_wout_mod::volume
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
vp
real(rprec), dimension(:), allocatable read_wout_mod::vp
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
wb
real(rprec) read_wout_mod::wb
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
wdot
real(rprec), dimension(:), allocatable read_wout_mod::wdot
Definition at line 219 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
wp
real(rprec) read_wout_mod::wp
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
xm
real(rprec), dimension(:), allocatable read_wout_mod::xm
Definition at line 219 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
xm_nyq
real(rprec), dimension(:), allocatable read_wout_mod::xm_nyq
Definition at line 219 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
xn
real(rprec), dimension(:), allocatable read_wout_mod::xn
Definition at line 219 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
xn_nyq
real(rprec), dimension(:), allocatable read_wout_mod::xn_nyq
Definition at line 219 of file read_wout_mod.f.
Referenced by compute_currents(), read_wout_deallocate(), read_wout_mod::read_wout_file::readw_and_open(), and tosuvspace().
y2stark
real(rprec), dimension(:), allocatable read_wout_mod::y2stark
Definition at line 219 of file read_wout_mod.f.
y2thom
real(rprec), dimension(:), allocatable read_wout_mod::y2thom
Definition at line 219 of file read_wout_mod.f.
ystark
real(rprec), dimension(:), allocatable read_wout_mod::ystark
Definition at line 219 of file read_wout_mod.f.
ythom
real(rprec), dimension(:), allocatable read_wout_mod::ythom
Definition at line 219 of file read_wout_mod.f.
zaxis
real(rprec), dimension(:,:), allocatable read_wout_mod::zaxis
Definition at line 212 of file read_wout_mod.f.
Referenced by read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
zmax_surf
real(rprec) read_wout_mod::zmax_surf
Definition at line 204 of file read_wout_mod.f.
Referenced by read_wout_mod::read_wout_file::readw_and_open().
zmnc
real(rprec), dimension(:,:), allocatable read_wout_mod::zmnc
Definition at line 212 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().
zmns
real(rprec), dimension(:,:), allocatable read_wout_mod::zmns
Definition at line 212 of file read_wout_mod.f.
Referenced by loadrzl(), read_wout_deallocate(), and read_wout_mod::read_wout_file::readw_and_open().