VMEC: src/mercier.f90 File Reference
mercier.f90 File Reference
Evaluate the Mercier stability criterion.
Functions/Subroutines
subroutine mercier (gsqrt, bsq, bdotj, iotas, wint, r1, rt, rz, zt, zz, bsubu, vp, phips, pres, ns, nznt)
Evaluate the Mercier stability criterion.
Detailed Description
Evaluate the Mercier stability criterion.
Definition in file mercier.f90.
Function/Subroutine Documentation
mercier()
subroutine mercier (real(rprec), dimension(ns,nznt), intent(in) gsqrt, real(rprec), dimension(ns,nznt), intent(in) bsq, real(rprec), dimension(ns,nznt), intent(inout) bdotj, real(rprec), dimension(ns), intent(in) iotas, real(rprec), dimension(ns*nznt), intent(in) wint, real(rprec), dimension(ns,nznt,0:1), intent(in) r1, real(rprec), dimension(ns,nznt,0:1), intent(in) rt, real(rprec), dimension(ns,nznt,0:1), intent(in) rz, real(rprec), dimension(ns,nznt,0:1), intent(in) zt, real(rprec), dimension(ns,nznt,0:1), intent(in) zz, real(rprec), dimension(ns*nznt), intent(in) bsubu, real(rprec), dimension(ns), intent(in) vp, real(rprec), dimension(ns), intent(in) phips, real(rprec), dimension(ns), intent(in) pres, integer, intent(in) ns, integer, intent(in) nznt)
Evaluate the Mercier stability criterion.
Parameters
gsqrt Jacobian \(\sqrt{g}\)
bsq modulus of magnetic field \(|\mathbf{B}|\)
bdotj parallel current density \(\mathbf{B} \cdot \mathbf{j}\); mu0 * bdotk from jxbforce
iotas rotational transform profile
wint normalization constant for flux-surface integrals
r1 \(R\)
rt \(\partial R / \partial \theta\)
rz \(\partial R / \partial \zeta\)
zt \(\partial Z / \partial \theta\)
zz \(\partial Z / \partial \zeta\)
bsubu contravariant component of magnetic field \(B^\zeta\)
vp radial profile of specific volume \(\partial V / \partial s\)
phips radial derivative of enclosed toroidal magnetic flux
pres pressure profile
ns number of flux surfaces
nznt number of grid points per flux surface
Definition at line 22 of file mercier.f90.
References vmercier::dcurr, vmercier::dgeod, vmercier::dmerc, stel_kinds::dp, vmercier::dshear, vmercier::dwell, vmec_input::input_extension, vparams::nmercier0, vmec_dim::nrzt, vmec_dim::ntheta3, vmec_input::nzeta, dbgout::open_dbg_context(), and safe_open_mod::safe_open().
Referenced by jxbforce().