VMEC: vacmod Module Reference
vacmod Module Reference
Functions/Subroutines
subroutine allocate_nestor
subroutine free_mem_nestor
Variables
real(rprec), parameter p5 = cp5
real(rprec), parameter two = c2p0
real(rprec) bsubvvac
real(rprec) pi2
real(rprec) pi3
real(rprec) pi4
real(rprec) alp
real(rprec) alu
real(rprec) alv
real(rprec) alvp
real(rprec) onp
real(rprec) onp2
logical precal_done
real(rprec), dimension(:), allocatable, target potvac
real(rprec), dimension(:), allocatable m_map_wrt
real(rprec), dimension(:), allocatable n_map_wrt
real(rprec), dimension(:), allocatable bvecsav
real(rprec), dimension(:), allocatable amatsav
real(rprec), dimension(:), allocatable bexni
real(rprec), dimension(:), allocatable brv
real(rprec), dimension(:), allocatable bphiv
real(rprec), dimension(:), allocatable bzv
real(rprec), dimension(:), allocatable bsqvac
real(rprec), dimension(:), allocatable r1b
real(rprec), dimension(:), allocatable rub
real(rprec), dimension(:), allocatable rvb
real(rprec), dimension(:), allocatable z1b
real(rprec), dimension(:), allocatable zub
real(rprec), dimension(:), allocatable zvb
real(rprec), dimension(:), allocatable bexu
real(rprec), dimension(:), allocatable bexv
real(rprec), dimension(:), allocatable bexn
real(rprec), dimension(:), allocatable auu
real(rprec), dimension(:), allocatable auv
real(rprec), dimension(:), allocatable avv
real(rprec), dimension(:), allocatable snr
real(rprec), dimension(:), allocatable snv
real(rprec), dimension(:), allocatable snz
real(rprec), dimension(:), allocatable drv
real(rprec), dimension(:), allocatable guu_b
real(rprec), dimension(:), allocatable guv_b
real(rprec), dimension(:), allocatable gvv_b
real(rprec), dimension(:), allocatable rzb2
real(rprec), dimension(:), allocatable rcosuv
real(rprec), dimension(:), allocatable rsinuv
real(rprec), dimension(:), allocatable raxis_nestor
real(rprec), dimension(:), allocatable zaxis_nestor
real(rprec), dimension(:), allocatable bsubu
real(rprec), dimension(:), allocatable bsubv
real(rprec), dimension(:), allocatable potu
real(rprec), dimension(:), allocatable potv
real(rprec), dimension(:), allocatable amatrix
real(rprec), dimension(:), allocatable ruu
real(rprec), dimension(:), allocatable ruv
real(rprec), dimension(:), allocatable rvv
real(rprec), dimension(:), allocatable zuu
real(rprec), dimension(:), allocatable zuv
real(rprec), dimension(:), allocatable zvv
real(rprec), dimension(:), allocatable brad
real(rprec), dimension(:), allocatable bphi
real(rprec), dimension(:), allocatable bz
real(rprec), dimension(:,:), allocatable xpts
real(rprec), dimension(:), allocatable grpmn
real(rprec), dimension(:), allocatable grpmn_m_map_wrt
real(rprec), dimension(:), allocatable grpmn_n_map_wrt
real(rprec), dimension(:), allocatable gstore
real(rprec), dimension(:,:), allocatable green
real(rprec), dimension(:,:), allocatable greenp
real(rprec), dimension(:), allocatable r0p
real(rprec), dimension(:), allocatable r1p
real(rprec), dimension(:), allocatable r0m
real(rprec), dimension(:), allocatable r1m
real(rprec), dimension(:), allocatable sqrtc
real(rprec), dimension(:), allocatable sqrta
real(rprec), dimension(:), allocatable tlp2
real(rprec), dimension(:), allocatable tlp1
real(rprec), dimension(:), allocatable tlp
real(rprec), dimension(:), allocatable tlm2
real(rprec), dimension(:), allocatable tlm1
real(rprec), dimension(:), allocatable tlm
real(rprec), dimension(:), allocatable adp
real(rprec), dimension(:), allocatable adm
real(rprec), dimension(:), allocatable cma
real(rprec), dimension(:), allocatable ra1p
real(rprec), dimension(:), allocatable ra1m
real(rprec), dimension(:), allocatable slm
real(rprec), dimension(:), allocatable slp
real(rprec), dimension(:), allocatable tlpm
real(rprec), dimension(:), allocatable slpm
real(rprec), dimension(:), allocatable delt1u
real(rprec), dimension(:), allocatable azp1u
real(rprec), dimension(:), allocatable azm1u
real(rprec), dimension(:), allocatable cma11u
real(rprec), dimension(:), allocatable sqad1u
real(rprec), dimension(:), allocatable sqad2u
real(rprec), dimension(:,:), allocatable all_tlp
real(rprec), dimension(:,:), allocatable all_tlm
real(rprec), dimension(:,:), allocatable all_slp
real(rprec), dimension(:,:), allocatable all_slm
real(rprec), dimension(:), allocatable gsave
real(rprec), dimension(:), allocatable ga1
real(rprec), dimension(:), allocatable ga2
real(rprec), dimension(:), allocatable dsave
real(rprec), dimension(:,:,:), allocatable g1
real(rprec), dimension(:,:,:), allocatable g2
real(rprec), dimension(:,:,:), allocatable bcos
real(rprec), dimension(:,:,:), allocatable bsin
real(rprec), dimension(:,:,:), allocatable source
real(rprec), dimension(:,:,:,:), allocatable actemp
real(rprec), dimension(:,:,:,:), allocatable astemp
Function/Subroutine Documentation
allocate_nestor()
subroutine vacmod::allocate_nestor
Definition at line 161 of file vacmod.f90.
References actemp, adm, adp, all_slm, all_slp, all_tlm, all_tlp, amatrix, amatsav, astemp, auu, auv, avv, azm1u, azp1u, bcos, bexn, bexni, bexu, bexv, bphi, bphiv, brad, brv, bsin, bsqvac, bsubu, bsubv, bvecsav, bz, bzv, cma, cma11u, vac_persistent::cmns, vac_persistent::cosper, vac_persistent::cosu, vac_persistent::cosu1, vac_persistent::cosui, vac_persistent::cosuv, vac_persistent::cosv, vac_persistent::cosv1, vac_persistent::csign, delt1u, drv, dsave, g1, g2, ga1, ga2, green, greenp, grpmn, grpmn_m_map_wrt, grpmn_n_map_wrt, gsave, gstore, guu_b, guv_b, gvv_b, vac_persistent::imirr, m_map_wrt, vacmod0::mf, vacmod0::mnpd, vacmod0::mnpd2, n_map_wrt, vacmod0::ndim, vacmod0::nf, vacmod0::nu, vacmod0::nu2, vacmod0::nu3, vacmod0::nuv, vacmod0::nuv2, vacmod0::nuv_tan, vacmod0::nv, vacmod0::nvp, vacmod0::nvper, potu, potv, potvac, precal_done, r0m, r0p, r1b, r1m, r1p, ra1m, ra1p, raxis_nestor, rcosuv, rsinuv, rub, ruu, ruv, rvb, rvv, rzb2, vac_persistent::sinper, vac_persistent::sinu, vac_persistent::sinu1, vac_persistent::sinui, vac_persistent::sinuv, vac_persistent::sinv, vac_persistent::sinv1, slm, slp, slpm, snr, snv, snz, source, sqad1u, sqad2u, sqrta, sqrtc, vac_persistent::tanu, vac_persistent::tanu_1d, vac_persistent::tanv, vac_persistent::tanv_1d, tlm, tlm1, tlm2, tlp, tlp1, tlp2, tlpm, vac_persistent::xmpot, vac_persistent::xnpot, xpts, z1b, zaxis_nestor, zub, zuu, zuv, zvb, and zvv.
Referenced by allocate_nunv(), and nestor().
free_mem_nestor()
subroutine vacmod::free_mem_nestor
Definition at line 282 of file vacmod.f90.
References actemp, adm, adp, amatrix, amatsav, astemp, auu, auv, avv, azm1u, azp1u, bcos, bexn, bexni, bexu, bexv, bphi, bphiv, brad, brv, bsin, bsqvac, bsubu, bsubv, bvecsav, bz, bzv, cma, cma11u, vac_persistent::cmns, vac_persistent::cosper, vac_persistent::cosu, vac_persistent::cosu1, vac_persistent::cosui, vac_persistent::cosuv, vac_persistent::cosv, vac_persistent::cosv1, vac_persistent::csign, delt1u, drv, dsave, g1, g2, ga1, ga2, green, greenp, grpmn, grpmn_m_map_wrt, grpmn_n_map_wrt, gsave, gstore, guu_b, guv_b, gvv_b, vac_persistent::imirr, m_map_wrt, n_map_wrt, potu, potv, potvac, r0m, r0p, r1b, r1m, r1p, ra1m, ra1p, raxis_nestor, rcosuv, rsinuv, rub, ruu, ruv, rvb, rvv, rzb2, vac_persistent::sinper, vac_persistent::sinu, vac_persistent::sinu1, vac_persistent::sinui, vac_persistent::sinuv, vac_persistent::sinv, vac_persistent::sinv1, slm, slp, slpm, snr, snv, snz, source, sqad1u, sqad2u, sqrta, sqrtc, vac_persistent::tanu, vac_persistent::tanu_1d, vac_persistent::tanv, vac_persistent::tanv_1d, tlm, tlm1, tlm2, tlp, tlp1, tlp2, tlpm, vac_persistent::xmpot, vac_persistent::xnpot, xpts, z1b, zaxis_nestor, zub, zuu, zuv, zvb, and zvv.
Referenced by free_mem_nunv(), and nestor().
Variable Documentation
actemp
real(rprec), dimension(:,:,:,:), allocatable vacmod::actemp
Definition at line 156 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), and free_mem_nestor().
adm
real(rprec), dimension(:), allocatable vacmod::adm
Definition at line 121 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
adp
real(rprec), dimension(:), allocatable vacmod::adp
Definition at line 120 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
all_slm
real(rprec), dimension(:,:), allocatable vacmod::all_slm
Definition at line 139 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and nestor_io::write_nestor_outputs().
all_slp
real(rprec), dimension(:,:), allocatable vacmod::all_slp
Definition at line 138 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and nestor_io::write_nestor_outputs().
all_tlm
real(rprec), dimension(:,:), allocatable vacmod::all_tlm
Definition at line 137 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and nestor_io::write_nestor_outputs().
all_tlp
real(rprec), dimension(:,:), allocatable vacmod::all_tlp
Definition at line 136 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and nestor_io::write_nestor_outputs().
alp
real(rprec) vacmod::alp
Definition at line 17 of file vacmod.f90.
Referenced by precal().
alu
real(rprec) vacmod::alu
Definition at line 18 of file vacmod.f90.
Referenced by precal().
alv
real(rprec) vacmod::alv
Definition at line 19 of file vacmod.f90.
Referenced by precal().
alvp
real(rprec) vacmod::alvp
Definition at line 20 of file vacmod.f90.
Referenced by precal().
amatrix
real(rprec), dimension(:), allocatable vacmod::amatrix
Definition at line 80 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), free_mem_nestor(), scalpot(), vacuum(), and nestor_io::write_nestor_outputs().
amatsav
real(rprec), dimension(:), allocatable vacmod::amatsav
Definition at line 32 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), funct3d(), nestor(), read_nestor_outputs(), scalpot(), and nestor_io::write_nestor_outputs().
astemp
real(rprec), dimension(:,:,:,:), allocatable vacmod::astemp
Definition at line 157 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), and free_mem_nestor().
auu
real(rprec), dimension(:), allocatable vacmod::auu
Definition at line 53 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
auv
real(rprec), dimension(:), allocatable vacmod::auv
Definition at line 54 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
avv
real(rprec), dimension(:), allocatable vacmod::avv
Definition at line 55 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
azm1u
real(rprec), dimension(:), allocatable vacmod::azm1u
Definition at line 131 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
azp1u
real(rprec), dimension(:), allocatable vacmod::azp1u
Definition at line 130 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
bcos
real(rprec), dimension(:,:,:), allocatable vacmod::bcos
Definition at line 152 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), and free_mem_nestor().
bexn
real(rprec), dimension(:), allocatable vacmod::bexn
Definition at line 51 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
bexni
real(rprec), dimension(:), allocatable vacmod::bexni
Definition at line 34 of file vacmod.f90.
Referenced by allocate_nestor(), analysum(), analysum2(), bextern(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
bexu
real(rprec), dimension(:), allocatable vacmod::bexu
Definition at line 49 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
bexv
real(rprec), dimension(:), allocatable vacmod::bexv
Definition at line 50 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
bphi
real(rprec), dimension(:), allocatable vacmod::bphi
Definition at line 92 of file vacmod.f90.
Referenced by allocate_nestor(), becoil(), bextern(), eqfor(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
bphiv
real(rprec), dimension(:), allocatable vacmod::bphiv
Definition at line 37 of file vacmod.f90.
Referenced by allocate_nestor(), eqfor(), free_mem_nestor(), freeb_data(), read_nestor_outputs(), vacuum(), and nestor_io::write_nestor_outputs().
brad
real(rprec), dimension(:), allocatable vacmod::brad
Definition at line 91 of file vacmod.f90.
Referenced by allocate_nestor(), becoil(), bextern(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
brv
real(rprec), dimension(:), allocatable vacmod::brv
Definition at line 36 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), freeb_data(), read_nestor_outputs(), vacuum(), and nestor_io::write_nestor_outputs().
bsin
real(rprec), dimension(:,:,:), allocatable vacmod::bsin
Definition at line 153 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), and free_mem_nestor().
bsqvac
real(rprec), dimension(:), allocatable vacmod::bsqvac
Definition at line 40 of file vacmod.f90.
Referenced by allocate_nestor(), eqfor(), free_mem_nestor(), freeb_data(), funct3d(), read_nestor_outputs(), vacuum(), and nestor_io::write_nestor_outputs().
bsubu
real(rprec), dimension(:), allocatable vacmod::bsubu
Definition at line 76 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
bsubv
real(rprec), dimension(:), allocatable vacmod::bsubv
Definition at line 77 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
bsubvvac
real(rprec) vacmod::bsubvvac
Definition at line 13 of file vacmod.f90.
Referenced by eqfor(), funct3d(), nestor(), read_nestor_outputs(), vacuum(), and nestor_io::write_nestor_outputs().
bvecsav
real(rprec), dimension(:), allocatable vacmod::bvecsav
Definition at line 31 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), funct3d(), nestor(), read_nestor_outputs(), scalpot(), and nestor_io::write_nestor_outputs().
bz
real(rprec), dimension(:), allocatable vacmod::bz
Definition at line 93 of file vacmod.f90.
Referenced by allocate_nestor(), becoil(), belicu(), bextern(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
bzv
real(rprec), dimension(:), allocatable vacmod::bzv
Definition at line 38 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), freeb_data(), read_nestor_outputs(), vacuum(), and nestor_io::write_nestor_outputs().
cma
real(rprec), dimension(:), allocatable vacmod::cma
Definition at line 122 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
cma11u
real(rprec), dimension(:), allocatable vacmod::cma11u
Definition at line 132 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
delt1u
real(rprec), dimension(:), allocatable vacmod::delt1u
Definition at line 129 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
drv
real(rprec), dimension(:), allocatable vacmod::drv
Definition at line 61 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
dsave
real(rprec), dimension(:), allocatable vacmod::dsave
Definition at line 145 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), and greenf().
g1
real(rprec), dimension(:,:,:), allocatable vacmod::g1
Definition at line 148 of file vacmod.f90.
Referenced by allocate_nestor(), fourp(), and free_mem_nestor().
g2
real(rprec), dimension(:,:,:), allocatable vacmod::g2
Definition at line 149 of file vacmod.f90.
Referenced by allocate_nestor(), fourp(), and free_mem_nestor().
ga1
real(rprec), dimension(:), allocatable vacmod::ga1
Definition at line 143 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), and greenf().
ga2
real(rprec), dimension(:), allocatable vacmod::ga2
Definition at line 144 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), and greenf().
green
real(rprec), dimension(:,:), allocatable vacmod::green
Definition at line 104 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
greenp
real(rprec), dimension(:,:), allocatable vacmod::greenp
Definition at line 105 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
grpmn
real(rprec), dimension(:), allocatable vacmod::grpmn
Definition at line 99 of file vacmod.f90.
Referenced by allocate_nestor(), analysum(), analysum2(), analyt(), fouri(), fourp(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
grpmn_m_map_wrt
real(rprec), dimension(:), allocatable vacmod::grpmn_m_map_wrt
Definition at line 100 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
grpmn_n_map_wrt
real(rprec), dimension(:), allocatable vacmod::grpmn_n_map_wrt
Definition at line 101 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
gsave
real(rprec), dimension(:), allocatable vacmod::gsave
Definition at line 142 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), and greenf().
gstore
real(rprec), dimension(:), allocatable vacmod::gstore
Definition at line 103 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), scalpot(), and nestor_io::write_nestor_outputs().
guu_b
real(rprec), dimension(:), allocatable vacmod::guu_b
Definition at line 63 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
guv_b
real(rprec), dimension(:), allocatable vacmod::guv_b
Definition at line 64 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
gvv_b
real(rprec), dimension(:), allocatable vacmod::gvv_b
Definition at line 65 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), greenf(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
m_map_wrt
real(rprec), dimension(:), allocatable vacmod::m_map_wrt
Definition at line 28 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
n_map_wrt
real(rprec), dimension(:), allocatable vacmod::n_map_wrt
Definition at line 29 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
onp
real(rprec) vacmod::onp
Definition at line 21 of file vacmod.f90.
Referenced by fouri(), fourp(), precal(), and surface().
onp2
real(rprec) vacmod::onp2
Definition at line 22 of file vacmod.f90.
Referenced by precal(), and surface().
p5
real(rprec), parameter vacmod::p5 = cp5
Definition at line 10 of file vacmod.f90.
Referenced by fouri(), fourp(), precal(), surface(), vacuum(), and wrout().
pi2
real(rprec) vacmod::pi2
Definition at line 14 of file vacmod.f90.
Referenced by bextern(), fouri(), precal(), and vacuum().
pi3
real(rprec) vacmod::pi3
Definition at line 15 of file vacmod.f90.
Referenced by fouri(), and precal().
pi4
real(rprec) vacmod::pi4
Definition at line 16 of file vacmod.f90.
Referenced by precal().
potu
real(rprec), dimension(:), allocatable vacmod::potu
Definition at line 78 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
potv
real(rprec), dimension(:), allocatable vacmod::potv
Definition at line 79 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), vacuum(), and nestor_io::write_nestor_outputs().
potvac
real(rprec), dimension(:), allocatable, target vacmod::potvac
Definition at line 26 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), freeb_data(), read_nestor_outputs(), vacuum(), nestor_io::write_nestor_outputs(), and wrout().
precal_done
logical vacmod::precal_done
Definition at line 24 of file vacmod.f90.
Referenced by allocate_nestor(), precal(), and vacuum().
r0m
real(rprec), dimension(:), allocatable vacmod::r0m
Definition at line 110 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
r0p
real(rprec), dimension(:), allocatable vacmod::r0p
Definition at line 108 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
r1b
real(rprec), dimension(:), allocatable vacmod::r1b
Definition at line 42 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), greenf(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
r1m
real(rprec), dimension(:), allocatable vacmod::r1m
Definition at line 111 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
r1p
real(rprec), dimension(:), allocatable vacmod::r1p
Definition at line 109 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
ra1m
real(rprec), dimension(:), allocatable vacmod::ra1m
Definition at line 124 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
ra1p
real(rprec), dimension(:), allocatable vacmod::ra1p
Definition at line 123 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
raxis_nestor
real(rprec), dimension(:), allocatable vacmod::raxis_nestor
Definition at line 72 of file vacmod.f90.
Referenced by allocate_nestor(), belicu(), free_mem_nestor(), and vacuum().
rcosuv
real(rprec), dimension(:), allocatable vacmod::rcosuv
Definition at line 69 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
rsinuv
real(rprec), dimension(:), allocatable vacmod::rsinuv
Definition at line 70 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
rub
real(rprec), dimension(:), allocatable vacmod::rub
Definition at line 43 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
ruu
real(rprec), dimension(:), allocatable vacmod::ruu
Definition at line 83 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().
ruv
real(rprec), dimension(:), allocatable vacmod::ruv
Definition at line 84 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().
rvb
real(rprec), dimension(:), allocatable vacmod::rvb
Definition at line 44 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
rvv
real(rprec), dimension(:), allocatable vacmod::rvv
Definition at line 85 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().
rzb2
real(rprec), dimension(:), allocatable vacmod::rzb2
Definition at line 67 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
slm
real(rprec), dimension(:), allocatable vacmod::slm
Definition at line 125 of file vacmod.f90.
Referenced by allocate_nestor(), analysum2(), analyt(), and free_mem_nestor().
slp
real(rprec), dimension(:), allocatable vacmod::slp
Definition at line 126 of file vacmod.f90.
Referenced by allocate_nestor(), analysum2(), analyt(), and free_mem_nestor().
slpm
real(rprec), dimension(:), allocatable vacmod::slpm
Definition at line 128 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
snr
real(rprec), dimension(:), allocatable vacmod::snr
Definition at line 57 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
snv
real(rprec), dimension(:), allocatable vacmod::snv
Definition at line 58 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
snz
real(rprec), dimension(:), allocatable vacmod::snz
Definition at line 59 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
source
real(rprec), dimension(:,:,:), allocatable vacmod::source
Definition at line 154 of file vacmod.f90.
Referenced by allocate_nestor(), fouri(), and free_mem_nestor().
sqad1u
real(rprec), dimension(:), allocatable vacmod::sqad1u
Definition at line 133 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
sqad2u
real(rprec), dimension(:), allocatable vacmod::sqad2u
Definition at line 134 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
sqrta
real(rprec), dimension(:), allocatable vacmod::sqrta
Definition at line 113 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
sqrtc
real(rprec), dimension(:), allocatable vacmod::sqrtc
Definition at line 112 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), free_mem_nestor(), and nestor_io::write_nestor_outputs().
tlm
real(rprec), dimension(:), allocatable vacmod::tlm
Definition at line 119 of file vacmod.f90.
Referenced by allocate_nestor(), analysum2(), analyt(), and free_mem_nestor().
tlm1
real(rprec), dimension(:), allocatable vacmod::tlm1
Definition at line 118 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
tlm2
real(rprec), dimension(:), allocatable vacmod::tlm2
Definition at line 117 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
tlp
real(rprec), dimension(:), allocatable vacmod::tlp
Definition at line 116 of file vacmod.f90.
Referenced by allocate_nestor(), analysum2(), analyt(), and free_mem_nestor().
tlp1
real(rprec), dimension(:), allocatable vacmod::tlp1
Definition at line 115 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
tlp2
real(rprec), dimension(:), allocatable vacmod::tlp2
Definition at line 114 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
tlpm
real(rprec), dimension(:), allocatable vacmod::tlpm
Definition at line 127 of file vacmod.f90.
Referenced by allocate_nestor(), analyt(), and free_mem_nestor().
two
real(rprec), parameter vacmod::two = c2p0
Definition at line 11 of file vacmod.f90.
Referenced by analyt().
xpts
real(rprec), dimension(:,:), allocatable vacmod::xpts
Definition at line 96 of file vacmod.f90.
Referenced by allocate_nestor(), belicu(), and free_mem_nestor().
z1b
real(rprec), dimension(:), allocatable vacmod::z1b
Definition at line 45 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), greenf(), surface(), and nestor_io::write_nestor_outputs().
zaxis_nestor
real(rprec), dimension(:), allocatable vacmod::zaxis_nestor
Definition at line 73 of file vacmod.f90.
Referenced by allocate_nestor(), belicu(), free_mem_nestor(), and vacuum().
zub
real(rprec), dimension(:), allocatable vacmod::zub
Definition at line 46 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
zuu
real(rprec), dimension(:), allocatable vacmod::zuu
Definition at line 86 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().
zuv
real(rprec), dimension(:), allocatable vacmod::zuv
Definition at line 87 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().
zvb
real(rprec), dimension(:), allocatable vacmod::zvb
Definition at line 47 of file vacmod.f90.
Referenced by allocate_nestor(), bextern(), free_mem_nestor(), surface(), vacuum(), and nestor_io::write_nestor_outputs().
zvv
real(rprec), dimension(:), allocatable vacmod::zvv
Definition at line 88 of file vacmod.f90.
Referenced by allocate_nestor(), free_mem_nestor(), surface(), and nestor_io::write_nestor_outputs().