VMEC: vforces Module Reference
vforces Module Reference
Variables
real(rprec), dimension(:), allocatable, target armn
real(rprec), dimension(:), allocatable, target brmn
real(rprec), dimension(:), allocatable, target crmn
real(rprec), dimension(:), allocatable, target azmn
real(rprec), dimension(:), allocatable, target bzmn
real(rprec), dimension(:), allocatable, target czmn
real(rprec), dimension(:), allocatable, target blmn
real(rprec), dimension(:), allocatable, target clmn
real(rprec), dimension(:), pointer armn_e
real(rprec), dimension(:), pointer armn_o
real(rprec), dimension(:), pointer brmn_e
real(rprec), dimension(:), pointer brmn_o
real(rprec), dimension(:), pointer crmn_e
real(rprec), dimension(:), pointer crmn_o
real(rprec), dimension(:), pointer azmn_e
real(rprec), dimension(:), pointer azmn_o
real(rprec), dimension(:), pointer bzmn_e
real(rprec), dimension(:), pointer bzmn_o
real(rprec), dimension(:), pointer czmn_e
real(rprec), dimension(:), pointer czmn_o
real(rprec), dimension(:), pointer blmn_e
real(rprec), dimension(:), pointer blmn_o
real(rprec), dimension(:), pointer clmn_e
real(rprec), dimension(:), pointer clmn_o
real(rprec), dimension(:), allocatable, target brmn_con
real(rprec), dimension(:), allocatable, target bzmn_con
real(rprec), dimension(:), pointer brmn_e_con
real(rprec), dimension(:), pointer brmn_o_con
real(rprec), dimension(:), pointer bzmn_e_con
real(rprec), dimension(:), pointer bzmn_o_con
Variable Documentation
armn
real(rprec), dimension(:), allocatable, target vforces::armn
Definition at line 8 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), free_mem_funct3d(), and funct3d().
armn_e
real(rprec), dimension(:), pointer vforces::armn_e
Definition at line 19 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), jacobian(), and wrout().
armn_o
real(rprec), dimension(:), pointer vforces::armn_o
Definition at line 20 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), forces(), jacobian(), and wrout().
azmn
real(rprec), dimension(:), allocatable, target vforces::azmn
Definition at line 12 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), free_mem_funct3d(), and funct3d().
azmn_e
real(rprec), dimension(:), pointer vforces::azmn_e
Definition at line 26 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), forces(), jacobian(), and wrout().
azmn_o
real(rprec), dimension(:), pointer vforces::azmn_o
Definition at line 27 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), fileout(), forces(), and jacobian().
blmn
real(rprec), dimension(:), allocatable, target vforces::blmn
Definition at line 16 of file vforces.f90.
Referenced by allocate_funct3d(), fileout(), free_mem_funct3d(), and funct3d().
blmn_e
real(rprec), dimension(:), pointer vforces::blmn_e
Definition at line 33 of file vforces.f90.
Referenced by allocate_funct3d(), and bcovar().
blmn_o
real(rprec), dimension(:), pointer vforces::blmn_o
Definition at line 34 of file vforces.f90.
Referenced by allocate_funct3d(), and bcovar().
brmn
real(rprec), dimension(:), allocatable, target vforces::brmn
Definition at line 9 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), free_mem_funct3d(), and funct3d().
brmn_con
real(rprec), dimension(:), allocatable, target vforces::brmn_con
Definition at line 39 of file vforces.f90.
Referenced by allocate_funct3d(), free_mem_funct3d(), and funct3d().
brmn_e
real(rprec), dimension(:), pointer vforces::brmn_e
Definition at line 21 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), forces(), jacobian(), and wrout().
brmn_e_con
real(rprec), dimension(:), pointer vforces::brmn_e_con
Definition at line 41 of file vforces.f90.
Referenced by allocate_funct3d(), and forces().
brmn_o
real(rprec), dimension(:), pointer vforces::brmn_o
Definition at line 22 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), and forces().
brmn_o_con
real(rprec), dimension(:), pointer vforces::brmn_o_con
Definition at line 42 of file vforces.f90.
Referenced by allocate_funct3d(), and forces().
bzmn
real(rprec), dimension(:), allocatable, target vforces::bzmn
Definition at line 13 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), free_mem_funct3d(), and funct3d().
bzmn_con
real(rprec), dimension(:), allocatable, target vforces::bzmn_con
Definition at line 40 of file vforces.f90.
Referenced by allocate_funct3d(), free_mem_funct3d(), and funct3d().
bzmn_e
real(rprec), dimension(:), pointer vforces::bzmn_e
Definition at line 28 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), forces(), jacobian(), and wrout().
bzmn_e_con
real(rprec), dimension(:), pointer vforces::bzmn_e_con
Definition at line 43 of file vforces.f90.
Referenced by allocate_funct3d(), and forces().
bzmn_o
real(rprec), dimension(:), pointer vforces::bzmn_o
Definition at line 29 of file vforces.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), fileout(), forces(), and funct3d().
bzmn_o_con
real(rprec), dimension(:), pointer vforces::bzmn_o_con
Definition at line 44 of file vforces.f90.
Referenced by allocate_funct3d(), and forces().
clmn
real(rprec), dimension(:), allocatable, target vforces::clmn
Definition at line 17 of file vforces.f90.
Referenced by allocate_funct3d(), fileout(), free_mem_funct3d(), and funct3d().
clmn_e
real(rprec), dimension(:), pointer vforces::clmn_e
Definition at line 35 of file vforces.f90.
Referenced by allocate_funct3d(), and bcovar().
clmn_o
real(rprec), dimension(:), pointer vforces::clmn_o
Definition at line 36 of file vforces.f90.
Referenced by allocate_funct3d(), and bcovar().
crmn
real(rprec), dimension(:), allocatable, target vforces::crmn
Definition at line 10 of file vforces.f90.
Referenced by allocate_funct3d(), free_mem_funct3d(), and funct3d().
crmn_e
real(rprec), dimension(:), pointer vforces::crmn_e
Definition at line 23 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), fileout(), and forces().
crmn_o
real(rprec), dimension(:), pointer vforces::crmn_o
Definition at line 24 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), fileout(), and forces().
czmn
real(rprec), dimension(:), allocatable, target vforces::czmn
Definition at line 14 of file vforces.f90.
Referenced by allocate_funct3d(), free_mem_funct3d(), and funct3d().
czmn_e
real(rprec), dimension(:), pointer vforces::czmn_e
Definition at line 30 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), fileout(), and forces().
czmn_o
real(rprec), dimension(:), pointer vforces::czmn_o
Definition at line 31 of file vforces.f90.
Referenced by allocate_funct3d(), eqfor(), forces(), and wrout().