VMEC: src/spline_cubic_int.f File Reference
spline_cubic_int.f File Reference
Functions/Subroutines
subroutine spline_cubic_int (x, y, xx, yy, n, iflag)
subroutine spline_int (x, y, n, yp1, ypn, y2)
subroutine splint_int (xa, ya, y2a, n, x, y)
Function/Subroutine Documentation
spline_cubic_int()
subroutine spline_cubic_int (real(rprec), intent(in) x, real(rprec), intent(out) y, real(rprec), dimension(n), intent(in) xx, real(rprec), dimension(n), intent(in) yy, integer, intent(in) n, integer, intent(inout) iflag)
Definition at line 2 of file spline_cubic_int.f.
References spline_int(), and splint_int().
Referenced by pcurr().
spline_int()
subroutine spline_cubic_int::spline_int (real(rprec), dimension(n), intent(in) x, real(rprec), dimension(n), intent(in) y, integer, intent(in) n, real(rprec), intent(in) yp1, real(rprec), intent(in) ypn, real(rprec), dimension(n), intent(out) y2)
Definition at line 56 of file spline_cubic_int.f.
Referenced by spline_cubic_int().
splint_int()
subroutine spline_cubic_int::splint_int (real(rprec), dimension(n), intent(in) xa, real(rprec), dimension(n), intent(in) ya, real(rprec), dimension(n), intent(in) y2a, integer, intent(in) n, real(rprec), intent(in) x, real(rprec), intent(out) y)
Definition at line 105 of file spline_cubic_int.f.
Referenced by spline_cubic_int().