VMEC: src/allocate_ns.f90 File Reference
allocate_ns.f90 File Reference
allocate arrays depending on the number of flux surfaces ns
Functions/Subroutines
subroutine allocate_ns (linterp, neqs_old)
allocate arrays depending on the number of flux surfaces ns
Detailed Description
allocate arrays depending on the number of flux surfaces ns
Definition in file allocate_ns.f90.
Function/Subroutine Documentation
allocate_ns()
subroutine allocate_ns (logical, intent(in) linterp, integer, intent(in) neqs_old)
allocate arrays depending on the number of flux surfaces ns
Parameters
linterp interpolate from coars to finer mesh?
neqs_old previous number of degrees-of-freedom, i.e., Fourier coefficients for \(R\), \(Z\) and \(\lambda\)
Definition at line 8 of file allocate_ns.f90.
References allocate_funct3d(), vmec_main::ard, vmec_main::arm, vmec_main::azd, vmec_main::azm, vmec_main::bdamp, vmec_main::bdotb, vmec_main::bdotgradv, vmec_main::beta_vol, vmec_main::blam, vmec_main::bmax, vmec_main::bmin, vmec_main::brd, vmec_main::brm, vmec_main::buco, vmec_main::bucof, vmec_main::bvco, vmec_main::bvcof, vmec_main::bzd, vmec_main::bzm, vmec_main::chi, realspace::chip, vmec_main::chipf, vmec_main::chips, vmec_main::clam, vmec_main::crd, vmec_main::dlam, vmec_main::equif, vmec_main::faclam, fbal::frcc_fac, free_mem_ns(), fbal::fzsc_fac, xstuff::gc, vmec_main::icurv, vmec_main::iotaf, vmec_main::iotas, vmec_main::ireflect, vmec_main::jcuru, vmec_main::jcurv, vmec_main::jdotb, vmec_main::jpar2, vmec_main::jperp2, vmec_main::mass, vmec_main::neqs, vmec_params::ntmax, vmec_main::overr, vmec_main::phi, realspace::phip, vmec_main::phipf, vmec_main::phips, vmec_main::pres, vmec_main::presf, vmec_main::presgrad, vmec_main::psi, fbal::rru_fac, fbal::rzu_fac, xstuff::scalxc, realspace::shalf, vmec_main::sm, vmec_main::sp, vmec_main::specw, realspace::sqrts, vmec_main::tcon, vmec_main::vp, vmec_main::vpphi, realspace::wint, xstuff::xc, xstuff::xcdot, xstuff::xsave, xstuff::xstore, vmec_main::yellip, vmec_main::ygeo, vmec_main::yinden, vmec_main::yshift, and vmec_main::ytrian.
Referenced by initialize_radial().