VMEC: src/NESTOR/scalpot.f90 File Reference
scalpot.f90 File Reference
Compute all required terms for solving for the scalar magnetic potential.
Functions/Subroutines
subroutine scalpot (bvec, amatrix, wint, ivacskip, lasym, m_map, n_map)
Compute all required terms for solving for the scalar magnetic potential.
Detailed Description
Compute all required terms for solving for the scalar magnetic potential.
Definition in file scalpot.f90.
Function/Subroutine Documentation
scalpot()
subroutine scalpot (real(rprec), dimension(mnpd2), intent(out) bvec, real(rprec), dimension(mnpd2*mnpd2), intent(out) amatrix, real(rprec), dimension(nuv2), intent(in) wint, integer, intent(in) ivacskip, logical, intent(in) lasym, real(rprec), dimension(mnpd2), intent(out) m_map, real(rprec), dimension(mnpd2), intent(out) n_map)
Compute all required terms for solving for the scalar magnetic potential.
Parameters
bvec scalpot
amatrix
wint
ivacskip
lasym
m_map
n_map
Definition at line 13 of file scalpot.f90.
References vacmod::amatrix, vacmod::amatsav, analyt(), vacmod::bexni, vacmod::bvecsav, fouri(), fourp(), vacmod::green, greenf(), vacmod::greenp, vacmod::grpmn, vacmod::grpmn_m_map_wrt, vacmod::grpmn_n_map_wrt, vacmod::gstore, vacmod::icall, and dbgout::open_dbg_context().
Referenced by vacuum().