VMEC: dbgout Module Reference
dbgout Module Reference
Functions/Subroutines
logical function open_dbg_context (context_name, repetition, id)
check if any output is desired for the current iteration check if the given context should be openend based on input file flags check if
Variables
logical skip_dbgout_collison = .false.
Function/Subroutine Documentation
open_dbg_context()
logical function dbgout::open_dbg_context (character(len=*), intent(in) context_name, integer, intent(in), optional repetition, integer, intent(in), optional id)
check if any output is desired for the current iteration check if the given context should be openend based on input file flags check if
Parameters
context_name a string describing the subroutine from which this function is called
repetition a number to distinguish two calls to this with the same value of iter2
id a number to replace iter2 in the output filename
Returns
true: debug output should be written and file is open; false otherwise
Definition at line 16 of file dbgout.f90.
References vmec_input::dump_add_fluxes, vmec_input::dump_bcontrav, vmec_input::dump_bcov, vmec_input::dump_bcov_full, vmec_input::dump_bcovar_fileout, vmec_input::dump_bss, vmec_input::dump_calc_fbal, vmec_input::dump_constraint_force, vmec_input::dump_evolve, vmec_input::dump_fixaray, vmec_input::dump_forcenorms_tcon, vmec_input::dump_forces, vmec_input::dump_freeb_data, vmec_input::dump_fsq, vmec_input::dump_fsq1, vmec_input::dump_funct3d_geometry, vmec_input::dump_guess_axis, vmec_input::dump_interp, vmec_input::dump_jacobian, vmec_input::dump_jxbforce_bsub_lowpass, vmec_input::dump_jxbout, vmec_input::dump_lambda_forces, vmec_input::dump_lamcal, vmec_input::dump_lulv_comb, vmec_input::dump_mercier, vmec_input::dump_metric, vmec_input::dump_multigrid_result, vmec_input::dump_phys_gc, vmec_input::dump_precondn, vmec_input::dump_printout, vmec_input::dump_profil1d, vmec_input::dump_profil3d, vmec_input::dump_rbsq, vmec_input::dump_readin_boundary, vmec_input::dump_scale_m1, vmec_input::dump_scalfor_out, vmec_input::dump_scalfor_r, vmec_input::dump_scalfor_z, vmec_input::dump_spectral_constraint, vmec_input::dump_symforce, vmec_input::dump_threed1_axis, vmec_input::dump_threed1_beta, vmec_input::dump_threed1_firsttable, vmec_input::dump_threed1_geomag, vmec_input::dump_threed1_shafrint, vmec_input::dump_threed1_volquant, vmec_input::dump_tomnspa, vmec_input::dump_tomnsps, vmec_input::dump_totzsp_input, vmec_input::dump_vac1n_analyt, vmec_input::dump_vac1n_bextern, vmec_input::dump_vac1n_bsqvac, vmec_input::dump_vac1n_fouri, vmec_input::dump_vac1n_fourp, vmec_input::dump_vac1n_greenf, vmec_input::dump_vac1n_precal, vmec_input::dump_vac1n_solver, vmec_input::dump_vac1n_surface, vmec_input::dump_vac1n_vacuum, vmec_input::dump_vac2_analin, vmec_input::dump_vac2_analyt, vmec_input::dump_vac2_bexmat, vmec_input::dump_vac2_bsqvac, vmec_input::dump_vac2_foumat, vmec_input::dump_vac2_foumat_unreg, vmec_input::dump_vac2_linslv, vmec_input::dump_vac2_linsys, vmec_input::dump_vac2_matrix, vmec_input::dump_vac2_precal, vmec_input::dump_vac2_surface, vmec_input::dump_vac2_vacuum, vmec_input::dump_volume, vmec_input::input_extension, vmec_main::iter2, vmec_input::iter2_to_dump, vmec_dim::ns, vmec_input::num_iter2_to_dump, open_dbg_context(), and skip_dbgout_collison.
Referenced by add_fluxes(), analyt(), bcovar(), bextern(), bss(), calc_fbal(), eqfor(), evolve(), fixaray(), forces(), fouri(), fourp(), freeb_data(), funct3d(), guess_axis(), interp(), jacobian(), jxbforce(), lamcal(), mercier(), open_dbg_context(), precal(), printout(), profil1d(), profil3d(), readin(), residue(), scalfor(), scalpot(), surface(), symforce(), tomnspa(), tomnsps(), vacuum(), and vmec().
Variable Documentation
skip_dbgout_collison
logical dbgout::skip_dbgout_collison = .false.
Definition at line 5 of file dbgout.f90.
Referenced by eqsolve(), and open_dbg_context().