VMEC: src/eqfor.f90 File Reference
eqfor.f90 File Reference
Basis physics analysis and evaluaton of force balance. This is where most of the contents of the threed1 output file is computed.
Functions/Subroutines
subroutine eqfor (br, bz, bsubu, bsubv, tau, rzl_array, ier_flag)
Basis physics analysis and evaluaton of force balance. This is where most of the contents of the threed1 output file is computed.
Detailed Description
Basis physics analysis and evaluaton of force balance. This is where most of the contents of the threed1 output file is computed.
Definition in file eqfor.f90.
Function/Subroutine Documentation
eqfor()
subroutine eqfor (real(rprec), dimension(nrzt), intent(out) br, real(rprec), dimension(nrzt), intent(out) bz, real(rprec), dimension(ns,nznt,0:1), intent(in) bsubu, real(rprec), dimension(ns,nznt,0:1), intent(in) bsubv, real(rprec), dimension(nrzt), intent(out) tau, real(rprec), dimension(ns,0:ntor,0:mpol1,3*ntmax), intent(in), target rzl_array, integer ier_flag)
Basis physics analysis and evaluaton of force balance. This is where most of the contents of the threed1 output file is computed.
Parameters
br cylindrical component of magnetic field \(B^R\)
bz cylindrical component of magnetic field \(B^Z\)
bsubu covariant component of magnetic field \(B_\theta\)
bsubv covariant component of magnetic field \(B_\zeta\)
tau Jacobian \(\sqrt{g} = R \tau\)
rzl_array state vector (all Fourier coefficients) of VMEC
ier_flag error flag
Definition at line 15 of file eqfor.f90.
References vmec_io::aminor_p, vforces::armn, vforces::armn_o, vmec_main::aspect, vforces::azmn, vforces::azmn_e, vforces::azmn_o, vmec_io::b0, vmec_main::bdotb, vmec_main::beta_vol, vmec_io::betapol, vmec_io::betator, vmec_io::betatot, vmec_io::betaxis, bextrema(), vmec_main::bmax, vmec_main::bmin, vmec_main::bpedge, vacmod::bphi, vacmod::bphiv, vmec_main::bredge, vforces::brmn, vforces::brmn_e, vacmod::bsqvac, bss(), vacmod::bsubvvac, vmec_main::buco, vmec_main::bucof, vmec_main::bvco, vmec_main::bvcof, vmec_main::bzedge, vforces::bzmn, vforces::bzmn_e, vforces::bzmn_o, calc_fbal(), vmec_main::chi, vmec_main::chipf, vmec_io::circum_p, vforces::crmn_e, vforces::crmn_o, vmec_io::cross_area_p, vmec_main::ctor, vforces::czmn_e, vforces::czmn_o, elongation(), vmec_main::equif, vmec_main::hs, vmec_io::ionlarmor, vmec_main::iotaf, vmec_main::iotas, vmec_main::ivac, vmec_main::jcuru, vmec_main::jcurv, vmec_main::jdotb, vmec_main::jpar2, vmec_main::jperp2, jxbforce(), vmec_io::kappa_p, vmec_main::lthreed, vmec_params::mscale, stel_constants::mu0, vmec_params::nscale, vmec_params::ntmax, stel_constants::one, dbgout::open_dbg_context(), vmec_main::overr, realspace::phip, vmec_main::phipf, stel_constants::pi, vmec_main::pres, vmec_main::presf, vmec_main::presgrad, vmec_main::psi, vmec_main::r00, realspace::r1, vmec_main::rbtor, vmec_main::rbtor0, vmec_params::rcc, realspace::rcon, vmec_params::rcs, vmec_main::rinner, vmec_io::rmajor_p, vmec_io::rmax_surf, vmec_io::rmin_surf, vmec_main::router, realspace::ru0, realspace::rv, vmec_params::signgs, vmec_main::specw, realspace::sqrts, vmec_io::surf_area_p, stel_constants::twopi, vmec_io::volavgb, vmec_io::volume_p, vmec_main::vp, vmec_main::vpphi, realspace::wint, vmec_main::yellip, vmec_main::ygeo, vmec_main::yinden, vmec_main::yshift, vmec_main::ytrian, realspace::z1, vmec_params::zcc, realspace::zcon, vmec_params::zcs, stel_constants::zero, vmec_io::zmax_surf, vmec_params::zsc, realspace::zu0, and realspace::zv.
Referenced by fileout().