VMEC: vac_persistent Module Reference
vac_persistent Module Reference
Variables
integer, dimension(:), allocatable imirr
real(rprec), dimension(:), allocatable sinper
real(rprec), dimension(:), allocatable cosper
real(rprec), dimension(:), allocatable sinuv
real(rprec), dimension(:), allocatable cosuv
real(rprec), dimension(:), allocatable tanu
real(rprec), dimension(:), allocatable tanv
real(rprec), dimension(:), allocatable tanu_1d
real(rprec), dimension(:), allocatable tanv_1d
real(rprec), dimension(:), allocatable xmpot
real(rprec), dimension(:), allocatable xnpot
real(rprec), dimension(:), allocatable csign
real(rprec), dimension(:,:), allocatable sinu
real(rprec), dimension(:,:), allocatable cosu
real(rprec), dimension(:,:), allocatable sinv
real(rprec), dimension(:,:), allocatable cosv
real(rprec), dimension(:,:), allocatable sinui
real(rprec), dimension(:,:), allocatable cosui
real(rprec), dimension(:,:), allocatable sinu1
real(rprec), dimension(:,:), allocatable cosu1
real(rprec), dimension(:,:), allocatable sinv1
real(rprec), dimension(:,:), allocatable cosv1
real(rprec), dimension(:,:,:), allocatable cmns
real(rprec), dimension(:), allocatable bsubu_sur
real(rprec), dimension(:), allocatable bsubv_sur
real(rprec), dimension(:), allocatable bsupu_sur
real(rprec), dimension(:), allocatable bsupv_sur
Variable Documentation
bsubu_sur
real(rprec), dimension(:), allocatable vac_persistent::bsubu_sur
Definition at line 38 of file vac_persistent.f90.
bsubv_sur
real(rprec), dimension(:), allocatable vac_persistent::bsubv_sur
Definition at line 39 of file vac_persistent.f90.
bsupu_sur
real(rprec), dimension(:), allocatable vac_persistent::bsupu_sur
Definition at line 40 of file vac_persistent.f90.
bsupv_sur
real(rprec), dimension(:), allocatable vac_persistent::bsupv_sur
Definition at line 41 of file vac_persistent.f90.
cmns
real(rprec), dimension(:,:,:), allocatable vac_persistent::cmns
Definition at line 36 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosper
real(rprec), dimension(:), allocatable vac_persistent::cosper
Definition at line 11 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosu
real(rprec), dimension(:,:), allocatable vac_persistent::cosu
Definition at line 26 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosu1
real(rprec), dimension(:,:), allocatable vac_persistent::cosu1
Definition at line 32 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosui
real(rprec), dimension(:,:), allocatable vac_persistent::cosui
Definition at line 30 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosuv
real(rprec), dimension(:), allocatable vac_persistent::cosuv
Definition at line 13 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosv
real(rprec), dimension(:,:), allocatable vac_persistent::cosv
Definition at line 28 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
cosv1
real(rprec), dimension(:,:), allocatable vac_persistent::cosv1
Definition at line 34 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
csign
real(rprec), dimension(:), allocatable vac_persistent::csign
Definition at line 23 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
imirr
integer, dimension(:), allocatable vac_persistent::imirr
Definition at line 8 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinper
real(rprec), dimension(:), allocatable vac_persistent::sinper
Definition at line 10 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinu
real(rprec), dimension(:,:), allocatable vac_persistent::sinu
Definition at line 25 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinu1
real(rprec), dimension(:,:), allocatable vac_persistent::sinu1
Definition at line 31 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinui
real(rprec), dimension(:,:), allocatable vac_persistent::sinui
Definition at line 29 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinuv
real(rprec), dimension(:), allocatable vac_persistent::sinuv
Definition at line 12 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinv
real(rprec), dimension(:,:), allocatable vac_persistent::sinv
Definition at line 27 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
sinv1
real(rprec), dimension(:,:), allocatable vac_persistent::sinv1
Definition at line 33 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
tanu
real(rprec), dimension(:), allocatable vac_persistent::tanu
Definition at line 15 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
tanu_1d
real(rprec), dimension(:), allocatable vac_persistent::tanu_1d
Definition at line 18 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
tanv
real(rprec), dimension(:), allocatable vac_persistent::tanv
Definition at line 16 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
tanv_1d
real(rprec), dimension(:), allocatable vac_persistent::tanv_1d
Definition at line 19 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
xmpot
real(rprec), dimension(:), allocatable vac_persistent::xmpot
Definition at line 21 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().
xnpot
real(rprec), dimension(:), allocatable vac_persistent::xnpot
Definition at line 22 of file vac_persistent.f90.
Referenced by vacmod::allocate_nestor(), and vacmod::free_mem_nestor().