VMEC: vmec_input Module Reference
vmec_input Module Reference
Functions/Subroutines
subroutine read_indata_namelist (iunit, istat)
subroutine write_indata_namelist (iunit, istat)
Variables
integer, parameter mpol_default = 6
integer, parameter ntor_default = 0
integer, parameter ns_default = 31
integer, parameter niter_default = 100
real(rprec), parameter ftol_default = 1.E-10_dp
integer nfp
integer ncurr
integer nstep
integer nvacskip
integer mpol
integer ntor
integer ntheta
integer nzeta
integer mfilter_fbdy
integer nfilter_fbdy
integer, dimension(100) ns_array
integer, dimension(100) niter_array
real(rprec), dimension(100) ftol_array
real(rprec), dimension(-ntord:ntord, 0:mpol1d) rbc
real(rprec), dimension(-ntord:ntord, 0:mpol1d) zbs
real(rprec), dimension(-ntord:ntord, 0:mpol1d) rbs
real(rprec), dimension(-ntord:ntord, 0:mpol1d) zbc
real(rprec) curtor
real(rprec) delt
real(rprec) tcon0
real(rprec) gamma
real(rprec) bloat
real(rprec) pres_scale
real(rprec) spres_ped
value of s beyond which pressure profile is flat (pedestal)
real(rprec) phiedge
value of real toroidal flux at plasma edge (s=1)
real(rprec), dimension(0:20) am
array of coefficients in phi-series for mass (NWT/m**2)
real(rprec), dimension(0:20) ai
array of coefficients in phi-series for iota (ncurr=0)
real(rprec), dimension(0:20) ac
array of coefficients in phi-series for the quantity d(Icurv)/ds = toroidal current density * Vprime, so Icurv(s) = Itor(s) (used for ncurr=1)
real(rprec), dimension(1:20) aphi
character(len=20) pcurr_type
character(len=20) piota_type
character(len=20) pmass_type
real(rprec), dimension(ndatafmax) am_aux_s
real(rprec), dimension(ndatafmax) am_aux_f
real(rprec), dimension(ndatafmax) ai_aux_s
real(rprec), dimension(ndatafmax) ai_aux_f
real(rprec), dimension(ndatafmax) ac_aux_s
real(rprec), dimension(ndatafmax) ac_aux_f
real(rprec), dimension(0:ntord) raxis_cc
real(rprec), dimension(0:ntord) raxis_cs
real(rprec), dimension(0:ntord) zaxis_cc
real(rprec), dimension(0:ntord) zaxis_cs
real(rprec), dimension(nigroup) extcur
logical lfreeb
logical lasym
integer vac_1_2
switch between implementations of NESTOR: vac1 (magnetic scalar potential, both Stellarator and Tokamak) vac2/vac3 (surface current density, Stellarator/Tokamak) Only vac1 is available in educational_VMEC by default.
logical lbsubs
character(len=200) mgrid_file
character(len=100) input_extension
integer max_dump = 2
maximum number of iterations for which to dump data
logical dump_add_fluxes = .false.
individual flags to control debug output loosely related to similarly-named routines (checkpoints along iterations)
logical dump_metric = .false.
logical dump_volume = .false.
logical dump_bcontrav = .false.
logical dump_bcov = .false.
logical dump_lambda_forces = .false.
logical dump_bcov_full = .false.
logical dump_precondn = .false.
logical dump_forcenorms_tcon = .false.
logical dump_lulv_comb = .false.
logical dump_calc_fbal = .false.
logical dump_evolve = .false.
logical dump_fixaray = .false.
logical dump_spectral_constraint = .false.
logical dump_forces = .false.
logical dump_funct3d_geometry = .false.
logical dump_constraint_force = .false.
logical dump_guess_axis = .false.
logical dump_interp = .false.
logical dump_jacobian = .false.
logical dump_lamcal = .false.
logical dump_profil1d = .false.
logical dump_profil3d = .false.
logical dump_readin_boundary = .false.
logical dump_phys_gc = .false.
logical dump_fsq = .false.
logical dump_scale_m1 = .false.
logical dump_scalfor_out = .false.
logical dump_fsq1 = .false.
logical dump_scalfor_r = .false.
logical dump_scalfor_z = .false.
logical dump_symforce = .false.
logical dump_tomnsps = .false.
logical dump_tomnspa = .false.
logical dump_multigrid_result = .false.
logical dump_rbsq = .false.
logical dump_bcovar_fileout = .false.
logical dump_bss = .false.
logical dump_vac1n_vacuum = .false.
logical dump_vac1n_precal = .false.
logical dump_vac1n_surface = .false.
logical dump_vac1n_bextern = .false.
logical dump_vac1n_analyt = .false.
logical dump_vac1n_greenf = .false.
logical dump_vac1n_fourp = .false.
logical dump_vac1n_fouri = .false.
logical dump_vac1n_solver = .false.
logical dump_vac1n_bsqvac = .false.
logical dump_vac2_vacuum = .false.
logical dump_vac2_precal = .false.
logical dump_vac2_surface = .false.
logical dump_vac2_bexmat = .false.
logical dump_vac2_matrix = .false.
logical dump_vac2_foumat_unreg = .false.
logical dump_vac2_analin = .false.
logical dump_vac2_analyt = .false.
logical dump_vac2_foumat = .false.
logical dump_vac2_linsys = .false.
logical dump_vac2_bsqvac = .false.
Function/Subroutine Documentation
read_indata_namelist()
subroutine vmec_input::read_indata_namelist (integer, intent(in) iunit, integer, intent(inout) istat)
Definition at line 267 of file vmec_input.f90.
References ac, ac_aux_s, ai, ai_aux_s, am, am_aux_s, aphi, bloat, curtor, delt, extcur, ftol_array, ftol_default, gamma, lasym, lbsubs, lfreeb, mfilter_fbdy, mgrid_file, mpol, mpol_default, ncurr, nfilter_fbdy, nfp, niter_array, niter_default, ns_array, ns_default, nstep, ntheta, ntor, ntor_default, nvacskip, nzeta, pcurr_type, phiedge, piota_type, pmass_type, pres_scale, raxis_cc, raxis_cs, rbc, rbs, spres_ped, tcon0, vac_1_2, zaxis_cc, zaxis_cs, zbc, and zbs.
Referenced by read_indata().
write_indata_namelist()
subroutine vmec_input::write_indata_namelist (integer, intent(in) iunit, integer, intent(inout) istat)
Definition at line 347 of file vmec_input.f90.
References ac, ac_aux_f, ac_aux_s, ai, ai_aux_f, ai_aux_s, am, am_aux_f, am_aux_s, bloat, curtor, delt, extcur, ftol_array, gamma, lasym, lfreeb, mgrid_file, mpol, ncurr, nfp, niter_array, ns_array, nstep, ntor, nvacskip, nzeta, pcurr_type, phiedge, piota_type, pmass_type, pres_scale, raxis_cc, raxis_cs, rbc, rbs, spres_ped, tcon0, zaxis_cc, zaxis_cs, zbc, and zbs.
Variable Documentation
ac
real(rprec), dimension(0:20) vmec_input::ac
array of coefficients in phi-series for the quantity d(Icurv)/ds = toroidal current density * Vprime, so Icurv(s) = Itor(s) (used for ncurr=1)
Definition at line 44 of file vmec_input.f90.
Referenced by pcurr(), read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
ac_aux_f
real(rprec), dimension(ndatafmax) vmec_input::ac_aux_f
Definition at line 55 of file vmec_input.f90.
Referenced by pcurr(), write_indata_namelist(), and wrout().
ac_aux_s
real(rprec), dimension(ndatafmax) vmec_input::ac_aux_s
Definition at line 54 of file vmec_input.f90.
Referenced by pcurr(), read_indata_namelist(), write_indata_namelist(), and wrout().
ai
real(rprec), dimension(0:20) vmec_input::ai
array of coefficients in phi-series for iota (ncurr=0)
Definition at line 43 of file vmec_input.f90.
Referenced by piota(), read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
ai_aux_f
real(rprec), dimension(ndatafmax) vmec_input::ai_aux_f
Definition at line 53 of file vmec_input.f90.
Referenced by piota(), write_indata_namelist(), and wrout().
ai_aux_s
real(rprec), dimension(ndatafmax) vmec_input::ai_aux_s
Definition at line 52 of file vmec_input.f90.
Referenced by piota(), read_indata_namelist(), write_indata_namelist(), and wrout().
am
real(rprec), dimension(0:20) vmec_input::am
array of coefficients in phi-series for mass (NWT/m**2)
Definition at line 42 of file vmec_input.f90.
Referenced by pmass(), read_indata_namelist(), write_indata_namelist(), and wrout().
am_aux_f
real(rprec), dimension(ndatafmax) vmec_input::am_aux_f
Definition at line 51 of file vmec_input.f90.
Referenced by pmass(), write_indata_namelist(), and wrout().
am_aux_s
real(rprec), dimension(ndatafmax) vmec_input::am_aux_s
Definition at line 50 of file vmec_input.f90.
Referenced by pmass(), read_indata_namelist(), write_indata_namelist(), and wrout().
aphi
real(rprec), dimension(1:20) vmec_input::aphi
Definition at line 46 of file vmec_input.f90.
Referenced by read_indata_namelist(), and torflux_deriv().
bloat
real(rprec) vmec_input::bloat
Definition at line 38 of file vmec_input.f90.
Referenced by pcurr(), pmass(), read_indata(), read_indata_namelist(), and write_indata_namelist().
curtor
real(rprec) vmec_input::curtor
Definition at line 34 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
delt
real(rprec) vmec_input::delt
Definition at line 35 of file vmec_input.f90.
Referenced by read_indata_namelist(), reset_params(), vmec(), and write_indata_namelist().
dump_add_fluxes
logical vmec_input::dump_add_fluxes = .false.
individual flags to control debug output loosely related to similarly-named routines (checkpoints along iterations)
Definition at line 89 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_bcontrav
logical vmec_input::dump_bcontrav = .false.
Definition at line 92 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_bcov
logical vmec_input::dump_bcov = .false.
Definition at line 93 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_bcov_full
logical vmec_input::dump_bcov_full = .false.
Definition at line 95 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_bcovar_fileout
logical vmec_input::dump_bcovar_fileout = .false.
Definition at line 125 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_bss
logical vmec_input::dump_bss = .false.
Definition at line 126 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_calc_fbal
logical vmec_input::dump_calc_fbal = .false.
Definition at line 99 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_constraint_force
logical vmec_input::dump_constraint_force = .false.
Definition at line 105 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_evolve
logical vmec_input::dump_evolve = .false.
Definition at line 100 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_fixaray
logical vmec_input::dump_fixaray = .false.
Definition at line 101 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_forcenorms_tcon
logical vmec_input::dump_forcenorms_tcon = .false.
Definition at line 97 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_forces
logical vmec_input::dump_forces = .false.
Definition at line 103 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_fsq
logical vmec_input::dump_fsq = .false.
Definition at line 114 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_fsq1
logical vmec_input::dump_fsq1 = .false.
Definition at line 117 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_funct3d_geometry
logical vmec_input::dump_funct3d_geometry = .false.
Definition at line 104 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_guess_axis
logical vmec_input::dump_guess_axis = .false.
Definition at line 106 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_interp
logical vmec_input::dump_interp = .false.
Definition at line 107 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_jacobian
logical vmec_input::dump_jacobian = .false.
Definition at line 108 of file vmec_input.f90.
Referenced by jacobian(), and dbgout::open_dbg_context().
dump_lambda_forces
logical vmec_input::dump_lambda_forces = .false.
Definition at line 94 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_lamcal
logical vmec_input::dump_lamcal = .false.
Definition at line 109 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_lulv_comb
logical vmec_input::dump_lulv_comb = .false.
Definition at line 98 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_metric
logical vmec_input::dump_metric = .false.
Definition at line 90 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_multigrid_result
logical vmec_input::dump_multigrid_result = .false.
Definition at line 123 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_phys_gc
logical vmec_input::dump_phys_gc = .false.
Definition at line 113 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_precondn
logical vmec_input::dump_precondn = .false.
Definition at line 96 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_profil1d
logical vmec_input::dump_profil1d = .false.
Definition at line 110 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_profil3d
logical vmec_input::dump_profil3d = .false.
Definition at line 111 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_rbsq
logical vmec_input::dump_rbsq = .false.
Definition at line 124 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_readin_boundary
logical vmec_input::dump_readin_boundary = .false.
Definition at line 112 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_scale_m1
logical vmec_input::dump_scale_m1 = .false.
Definition at line 115 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_scalfor_out
logical vmec_input::dump_scalfor_out = .false.
Definition at line 116 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_scalfor_r
logical vmec_input::dump_scalfor_r = .false.
Definition at line 118 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_scalfor_z
logical vmec_input::dump_scalfor_z = .false.
Definition at line 119 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_spectral_constraint
logical vmec_input::dump_spectral_constraint = .false.
Definition at line 102 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_symforce
logical vmec_input::dump_symforce = .false.
Definition at line 120 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_tomnspa
logical vmec_input::dump_tomnspa = .false.
Definition at line 122 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_tomnsps
logical vmec_input::dump_tomnsps = .false.
Definition at line 121 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_analyt
logical vmec_input::dump_vac1n_analyt = .false.
Definition at line 133 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_bextern
logical vmec_input::dump_vac1n_bextern = .false.
Definition at line 132 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_bsqvac
logical vmec_input::dump_vac1n_bsqvac = .false.
Definition at line 138 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_fouri
logical vmec_input::dump_vac1n_fouri = .false.
Definition at line 136 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_fourp
logical vmec_input::dump_vac1n_fourp = .false.
Definition at line 135 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_greenf
logical vmec_input::dump_vac1n_greenf = .false.
Definition at line 134 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_precal
logical vmec_input::dump_vac1n_precal = .false.
Definition at line 130 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_solver
logical vmec_input::dump_vac1n_solver = .false.
Definition at line 137 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_surface
logical vmec_input::dump_vac1n_surface = .false.
Definition at line 131 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac1n_vacuum
logical vmec_input::dump_vac1n_vacuum = .false.
Definition at line 129 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_analin
logical vmec_input::dump_vac2_analin = .false.
Definition at line 146 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_analyt
logical vmec_input::dump_vac2_analyt = .false.
Definition at line 147 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_bexmat
logical vmec_input::dump_vac2_bexmat = .false.
Definition at line 143 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_bsqvac
logical vmec_input::dump_vac2_bsqvac = .false.
Definition at line 150 of file vmec_input.f90.
dump_vac2_foumat
logical vmec_input::dump_vac2_foumat = .false.
Definition at line 148 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_foumat_unreg
logical vmec_input::dump_vac2_foumat_unreg = .false.
Definition at line 145 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_linsys
logical vmec_input::dump_vac2_linsys = .false.
Definition at line 149 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_matrix
logical vmec_input::dump_vac2_matrix = .false.
Definition at line 144 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_precal
logical vmec_input::dump_vac2_precal = .false.
Definition at line 141 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_surface
logical vmec_input::dump_vac2_surface = .false.
Definition at line 142 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_vac2_vacuum
logical vmec_input::dump_vac2_vacuum = .false.
Definition at line 140 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
dump_volume
logical vmec_input::dump_volume = .false.
Definition at line 91 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
extcur
real(rprec), dimension(nigroup) vmec_input::extcur
Definition at line 61 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
ftol_array
real(rprec), dimension(100) vmec_input::ftol_array
Definition at line 28 of file vmec_input.f90.
Referenced by read_indata_namelist(), vmec(), write_indata_namelist(), and wrout().
ftol_default
real(rprec), parameter vmec_input::ftol_default = 1.E-10_dp
Definition at line 13 of file vmec_input.f90.
Referenced by read_indata_namelist().
gamma
real(rprec) vmec_input::gamma
Definition at line 37 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
input_extension
character(len=100) vmec_input::input_extension
Definition at line 80 of file vmec_input.f90.
Referenced by jacobian(), mercier(), dbgout::open_dbg_context(), vmec(), and wrout().
lasym
logical vmec_input::lasym
Definition at line 63 of file vmec_input.f90.
Referenced by getbsubs(), read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
lbsubs
logical vmec_input::lbsubs
Definition at line 77 of file vmec_input.f90.
Referenced by read_indata_namelist().
lfreeb
logical vmec_input::lfreeb
Definition at line 62 of file vmec_input.f90.
Referenced by read_indata(), read_indata_namelist(), mgrid_mod::read_mgrid(), vmec(), write_indata_namelist(), and wrout().
max_dump
integer vmec_input::max_dump = 2
maximum number of iterations for which to dump data
Definition at line 85 of file vmec_input.f90.
Referenced by dbgout::open_dbg_context().
mfilter_fbdy
integer vmec_input::mfilter_fbdy
Definition at line 23 of file vmec_input.f90.
Referenced by read_indata_namelist().
mgrid_file
character(len=200) vmec_input::mgrid_file
Definition at line 79 of file vmec_input.f90.
Referenced by read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
mpol
integer vmec_input::mpol
Definition at line 19 of file vmec_input.f90.
Referenced by interp(), read_indata(), read_indata_namelist(), vmec(), write_indata_namelist(), and wrout().
mpol_default
integer, parameter vmec_input::mpol_default = 6
Definition at line 9 of file vmec_input.f90.
Referenced by read_indata_namelist().
ncurr
integer vmec_input::ncurr
Definition at line 16 of file vmec_input.f90.
Referenced by read_indata(), read_indata_namelist(), vmec(), and write_indata_namelist().
nfilter_fbdy
integer vmec_input::nfilter_fbdy
Definition at line 24 of file vmec_input.f90.
Referenced by read_indata_namelist().
nfp
integer vmec_input::nfp
Definition at line 15 of file vmec_input.f90.
Referenced by getbsubs(), read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
niter_array
integer, dimension(100) vmec_input::niter_array
Definition at line 27 of file vmec_input.f90.
Referenced by read_indata_namelist(), vmec(), and write_indata_namelist().
niter_default
integer, parameter vmec_input::niter_default = 100
Definition at line 12 of file vmec_input.f90.
Referenced by read_indata_namelist().
ns_array
integer, dimension(100) vmec_input::ns_array
Definition at line 26 of file vmec_input.f90.
Referenced by read_indata_namelist(), vmec(), write_indata_namelist(), and wrout().
ns_default
integer, parameter vmec_input::ns_default = 31
Definition at line 11 of file vmec_input.f90.
Referenced by read_indata_namelist().
nstep
integer vmec_input::nstep
Definition at line 17 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
ntheta
integer vmec_input::ntheta
Definition at line 21 of file vmec_input.f90.
Referenced by read_indata(), and read_indata_namelist().
ntor
integer vmec_input::ntor
Definition at line 20 of file vmec_input.f90.
Referenced by read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
ntor_default
integer, parameter vmec_input::ntor_default = 0
Definition at line 10 of file vmec_input.f90.
Referenced by read_indata_namelist().
nvacskip
integer vmec_input::nvacskip
Definition at line 18 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
nzeta
integer vmec_input::nzeta
Definition at line 22 of file vmec_input.f90.
Referenced by getbsubs(), getcurmid(), jacobian(), read_indata(), read_indata_namelist(), write_indata_namelist(), and wrout().
pcurr_type
character(len=20) vmec_input::pcurr_type
Definition at line 47 of file vmec_input.f90.
Referenced by pcurr(), read_indata_namelist(), write_indata_namelist(), and wrout().
phiedge
real(rprec) vmec_input::phiedge
value of real toroidal flux at plasma edge (s=1)
Definition at line 41 of file vmec_input.f90.
Referenced by read_indata_namelist(), vmec(), and write_indata_namelist().
piota_type
character(len=20) vmec_input::piota_type
Definition at line 48 of file vmec_input.f90.
Referenced by piota(), read_indata_namelist(), write_indata_namelist(), and wrout().
pmass_type
character(len=20) vmec_input::pmass_type
Definition at line 49 of file vmec_input.f90.
Referenced by pmass(), read_indata_namelist(), write_indata_namelist(), and wrout().
pres_scale
real(rprec) vmec_input::pres_scale
Definition at line 39 of file vmec_input.f90.
Referenced by pmass(), read_indata_namelist(), and write_indata_namelist().
raxis_cc
real(rprec), dimension(0:ntord) vmec_input::raxis_cc
Definition at line 57 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
raxis_cs
real(rprec), dimension(0:ntord) vmec_input::raxis_cs
Definition at line 58 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
rbc
real(rprec), dimension(-ntord:ntord,0:mpol1d) vmec_input::rbc
Definition at line 30 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
rbs
real(rprec), dimension(-ntord:ntord,0:mpol1d) vmec_input::rbs
Definition at line 32 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
spres_ped
real(rprec) vmec_input::spres_ped
value of s beyond which pressure profile is flat (pedestal)
Definition at line 40 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
tcon0
real(rprec) vmec_input::tcon0
Definition at line 36 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
vac_1_2
integer vmec_input::vac_1_2
switch between implementations of NESTOR: vac1 (magnetic scalar potential, both Stellarator and Tokamak) vac2/vac3 (surface current density, Stellarator/Tokamak) Only vac1 is available in educational_VMEC by default.
Definition at line 69 of file vmec_input.f90.
Referenced by read_indata_namelist().
zaxis_cc
real(rprec), dimension(0:ntord) vmec_input::zaxis_cc
Definition at line 59 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
zaxis_cs
real(rprec), dimension(0:ntord) vmec_input::zaxis_cs
Definition at line 60 of file vmec_input.f90.
Referenced by read_indata_namelist(), write_indata_namelist(), and wrout().
zbc
real(rprec), dimension(-ntord:ntord,0:mpol1d) vmec_input::zbc
Definition at line 33 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().
zbs
real(rprec), dimension(-ntord:ntord,0:mpol1d) vmec_input::zbs
Definition at line 31 of file vmec_input.f90.
Referenced by read_indata_namelist(), and write_indata_namelist().