VMEC: src/profile_functions.f File Reference
profile_functions.f File Reference
Parameterizations of profiles for rotational transform, toroidal current and pressure/mass.
Functions/Subroutines
real(rprec) function pcurr (xx)
real(rprec) function piota (x)
real(rprec) function pmass (xx)
Detailed Description
Parameterizations of profiles for rotational transform, toroidal current and pressure/mass.
Definition in file profile_functions.f.
Function/Subroutine Documentation
pcurr()
real(rprec) function pcurr (real(rprec) xx)
Definition at line 11 of file profile_functions.f.
References vmec_input::ac, vmec_input::ac_aux_f, vmec_input::ac_aux_s, vmec_input::bloat, line_segment::line_seg(), line_segment::line_seg_int(), stel_constants::one, pcurr(), vmec_input::pcurr_type, stel_constants::pi, spline_akima(), spline_akima_int(), spline_cubic(), spline_cubic_int(), tolower(), and stel_constants::zero.
Referenced by pcurr().
piota()
real(rprec) function piota (real(rprec) x)
Definition at line 341 of file profile_functions.f.
References vmec_input::ai, vmec_input::ai_aux_f, vmec_input::ai_aux_s, line_segment::line_seg(), stel_constants::one, stel_constants::pi, piota(), vmec_input::piota_type, spline_akima(), spline_cubic(), tolower(), and stel_constants::zero.
Referenced by piota(), and polflux_deriv().
pmass()
real(rprec) function pmass (real(rprec) xx)
Definition at line 480 of file profile_functions.f.
References vmec_input::am, vmec_input::am_aux_f, vmec_input::am_aux_s, vmec_input::bloat, line_segment::line_seg(), stel_constants::mu0, stel_constants::one, pmass(), vmec_input::pmass_type, vmec_input::pres_scale, spline_akima(), spline_cubic(), tolower(), and stel_constants::zero.
Referenced by pmass().