VMEC: src/initialize_radial.f90 File Reference
initialize_radial.f90 File Reference
Allocates memory for radial arrays and initializes radial profiles.
Functions/Subroutines
subroutine initialize_radial (nsval, ns_old, delt0)
Allocates memory for radial arrays and initializes radial profiles.
Detailed Description
Allocates memory for radial arrays and initializes radial profiles.
Definition in file initialize_radial.f90.
Function/Subroutine Documentation
initialize_radial()
subroutine initialize_radial (integer, intent(in) nsval, integer, intent(inout) ns_old, real(rprec), intent(out) delt0)
Allocates memory for radial arrays and initializes radial profiles.
Parameters
nsval new number of flux surfaces
ns_old old number of flux surfaces (from previous multi-grid iteration)
delt0 time step to be used in the new multi-grid iteration
Definition at line 9 of file initialize_radial.f90.
References allocate_ns(), vmec_main::fsq, vmec_main::ftolv, xstuff::gc, vmec_main::hs, vmec_main::ijacob, interp(), vmec_main::irst, vmec_main::irzloff, vmec_main::iter1, vmec_main::iter2, vmec_main::neqs, vmec_main::niterv, vmec_params::ntmax, vmec_main::ohs, profil1d(), profil3d(), vmec_main::profil3d_calls, vmec_main::res0, restart_iter(), xstuff::scalxc, xstuff::xc, xstuff::xcdot, and xstuff::xstore.
Referenced by vmec().