VMEC: xstuff Module Reference
xstuff Module Reference
Variables
real(rprec), dimension(:), allocatable gc
stacked array of R, Z, Lambda Spectral force coefficients (see above for stack order)
real(rprec), dimension(:), allocatable gc_con
real(rprec), dimension(:), allocatable gc_mhd
real(rprec), dimension(:), allocatable, target xc
stacked array of scaled R, Z, Lambda Fourier coefficients (see above for stack order)
real(rprec), dimension(:), allocatable xcdot
"velocity": change of Fourier coefficients per time step
real(rprec), dimension(:), allocatable xsave
real(rprec), dimension(:), allocatable xstore
backup copy of last-known-good xc
real(rprec), dimension(:), allocatable scalxc
Variable Documentation
gc
real(rprec), dimension(:), allocatable xstuff::gc
stacked array of R, Z, Lambda Spectral force coefficients (see above for stack order)
Definition at line 37 of file xstuff.f90.
Referenced by allocate_ns(), evolve(), fileout(), free_mem_ns(), funct3d(), initialize_radial(), and printout().
gc_con
real(rprec), dimension(:), allocatable xstuff::gc_con
Definition at line 37 of file xstuff.f90.
Referenced by allocate_ns(), free_mem_ns(), and funct3d().
gc_mhd
real(rprec), dimension(:), allocatable xstuff::gc_mhd
Definition at line 37 of file xstuff.f90.
Referenced by allocate_ns(), free_mem_ns(), and funct3d().
scalxc
real(rprec), dimension(:), allocatable xstuff::scalxc
Definition at line 50 of file xstuff.f90.
Referenced by allocate_ns(), free_mem_ns(), funct3d(), initialize_radial(), profil3d(), and vmec().
xc
real(rprec), dimension(:), allocatable, target xstuff::xc
stacked array of scaled R, Z, Lambda Fourier coefficients (see above for stack order)
Definition at line 40 of file xstuff.f90.
Referenced by allocate_ns(), bcovar(), eqsolve(), evolve(), fileout(), free_mem_ns(), funct3d(), initialize_radial(), restart_iter(), vmec(), and wrout().
xcdot
real(rprec), dimension(:), allocatable xstuff::xcdot
"velocity": change of Fourier coefficients per time step
Definition at line 43 of file xstuff.f90.
Referenced by allocate_ns(), evolve(), free_mem_ns(), initialize_radial(), and restart_iter().
xsave
real(rprec), dimension(:), allocatable xstuff::xsave
Definition at line 45 of file xstuff.f90.
Referenced by allocate_ns(), fileout(), and free_mem_ns().
xstore
real(rprec), dimension(:), allocatable xstuff::xstore
backup copy of last-known-good xc
Definition at line 48 of file xstuff.f90.
Referenced by allocate_ns(), free_mem_ns(), initialize_radial(), printout(), and restart_iter().