VMEC: src/NESTOR/analyt.f90 File Reference
analyt.f90 File Reference
Compute the analytical-and-numerical 4D Fourier integrals over the equivalently-singular functions.
Functions/Subroutines
subroutine analyt (grpmn, bvec, ivacskip, lasym, m_map, n_map, grpmn_m_map, grpmn_n_map)
Compute the analytical-and-numerical 4D Fourier integrals over the equivalently-singular functions.
Detailed Description
Compute the analytical-and-numerical 4D Fourier integrals over the equivalently-singular functions.
Definition in file analyt.f90.
Function/Subroutine Documentation
analyt()
subroutine analyt (real(rprec), dimension(nuv2*mnpd2), intent(out) grpmn, real(rprec), dimension(mnpd2), intent(out) bvec, integer, intent(in) ivacskip, integer, intent(in) lasym, real(rprec), dimension(mnpd2), intent(out) m_map, real(rprec), dimension(mnpd2), intent(out) n_map, real(rprec), dimension(nuv2*mnpd2), intent(out) grpmn_m_map, real(rprec), dimension(nuv2*mnpd2), intent(out) grpmn_n_map)
Compute the analytical-and-numerical 4D Fourier integrals over the equivalently-singular functions.
Parameters
grpmn
bvec
ivacskip
lasym
m_map
n_map
grpmn_m_map
grpmn_n_map
Definition at line 14 of file analyt.f90.
References vacmod::adm, vacmod::adp, vacmod::all_slm, vacmod::all_slp, vacmod::all_tlm, vacmod::all_tlp, analysum(), analysum2(), vacmod::auu, vacmod::auv, vacmod::avv, vacmod::azm1u, vacmod::azp1u, vacmod::cma, vacmod::cma11u, vacmod::delt1u, vacmod::grpmn, vacmod::guu_b, vacmod::guv_b, vacmod::gvv_b, vmec_main::num_eqsolve_retries, dbgout::open_dbg_context(), vacmod::r0m, vacmod::r0p, vacmod::r1m, vacmod::r1p, vacmod::ra1m, vacmod::ra1p, vacmod::slm, vacmod::slp, vacmod::slpm, vacmod::sqad1u, vacmod::sqad2u, vacmod::sqrta, vacmod::sqrtc, vacmod::tlm, vacmod::tlm1, vacmod::tlm2, vacmod::tlp, vacmod::tlp1, vacmod::tlp2, vacmod::tlpm, and vacmod::two.
Referenced by scalpot().