VMEC: stel_constants Module Reference
stel_constants Module Reference
Variables
real(dp), parameter pi =3.14159265358979323846264338328_dp
real(dp), parameter pio2 =pi/2
real(dp), parameter twopi =2*pi
real(dp), parameter sqrt2 =1.41421356237309504880168872_dp
real(dp), parameter degree =twopi / 360
real(dp), parameter one =1
real(dp), parameter zero =0
real(dp), parameter mu0 = 2 * twopi * 1.0e-7_dp
Variable Documentation
degree
real(dp), parameter stel_constants::degree =twopi / 360
Definition at line 16 of file stel_constants.f90.
mu0
real(dp), parameter stel_constants::mu0 = 2 * twopi * 1.0e-7_dp
Definition at line 24 of file stel_constants.f90.
Referenced by read_wout_mod::compute_currents(), and read_wout_mod::read_wout_file::readw_and_open().
one
real(dp), parameter stel_constants::one =1
Definition at line 17 of file stel_constants.f90.
Referenced by pcurr(), piota(), pmass(), and read_wout_mod::tosuvspace().
pi
real(dp), parameter stel_constants::pi =3.14159265358979323846264338328_dp
Definition at line 12 of file stel_constants.f90.
Referenced by eqfor(), pcurr(), and piota().
pio2
real(dp), parameter stel_constants::pio2 =pi/2
Definition at line 13 of file stel_constants.f90.
sqrt2
real(dp), parameter stel_constants::sqrt2 =1.41421356237309504880168872_dp
Definition at line 15 of file stel_constants.f90.
twopi
real(dp), parameter stel_constants::twopi =2*pi
Definition at line 14 of file stel_constants.f90.
zero
real(dp), parameter stel_constants::zero =0
Definition at line 18 of file stel_constants.f90.
Referenced by line_segment::line_seg_int(), pcurr(), piota(), pmass(), reset_params(), and read_wout_mod::tosuvspace().