VMEC: src/wrout.f90 File Reference
wrout.f90 File Reference
Write the output files of VMEC.
Functions/Subroutines
subroutine wrout (bsq, gsqrt, bsubu, bsubv, bsubs, bsupv, bsupu, rzl_array, gc_array, ier_flag)
Write the output files of VMEC.
Detailed Description
Write the output files of VMEC.
Definition in file wrout.f90.
Function/Subroutine Documentation
wrout()
subroutine wrout (real(rprec), dimension(ns,nznt), intent(inout) bsq, real(rprec), dimension(ns,nznt), intent(inout) gsqrt, real(rprec), dimension(ns,nznt), intent(inout) bsubu, real(rprec), dimension(ns,nznt), intent(inout) bsubv, real(rprec), dimension(ns,nznt), intent(inout) bsubs, real(rprec), dimension(ns,nznt), intent(inout) bsupv, real(rprec), dimension(ns,nznt), intent(inout) bsupu, real(rprec), dimension(mnmax,ns,3*max(ntmax/2,1)), intent(inout), target rzl_array, real(rprec), dimension(mnmax,ns,3*max(ntmax/2,1)), intent(inout), target gc_array, integer, intent(in) ier_flag)
Write the output files of VMEC.
Parameters
bsq
gsqrt
bsubu
bsubv
bsubs
bsupv
bsupu
rzl_array
gc_array
ier_flag error flag
Definition at line 16 of file wrout.f90.
References vmec_io::aminor_p, vforces::armn_e, vforces::armn_o, vmec_main::aspect, vforces::azmn_e, vmec_io::b0, vmec_main::bdotgradv, vmec_main::beta_vol, vmec_io::betapol, vmec_io::betator, vmec_io::betatot, vmec_io::betaxis, vforces::brmn_e, vmec_main::buco, vmec_main::bvco, vforces::bzmn_e, vparams::c2p0, vmec_main::chi, vmec_main::chipf, convert(), convert_asym(), convert_sym(), vmec_persistent::cosmui, vmec_persistent::cosnv, vparams::cp5, vmec_main::ctor, mgrid_mod::curlabel, vforces::czmn_o, vmercier::dcurr, vmercier::dgeod, vmercier::dmerc, vmercier::dshear, vmercier::dwell, vmec_main::equif, freeb_data(), vmec_main::fsql, vmec_main::fsqr, vmec_main::fsqz, vmec_input::ftol_array, vmec_io::ionlarmor, vmec_main::iotaf, vmec_main::iotas, vmec_main::irzloff, vmec_main::iter2, vmec_main::jcuru, vmec_main::jcurv, vmec_main::jdotb, vmec_params::lamscale, read_wout_mod::ln_abeta, read_wout_mod::ln_ac, read_wout_mod::ln_ac_aux_f, read_wout_mod::ln_ac_aux_s, read_wout_mod::ln_ai, read_wout_mod::ln_ai_aux_f, read_wout_mod::ln_ai_aux_s, read_wout_mod::ln_am, read_wout_mod::ln_am_aux_f, read_wout_mod::ln_am_aux_s, read_wout_mod::ln_amin, read_wout_mod::ln_aspect, read_wout_mod::ln_asym, read_wout_mod::ln_b0, read_wout_mod::ln_beta, read_wout_mod::ln_betah, read_wout_mod::ln_bgrv, read_wout_mod::ln_bmnc, read_wout_mod::ln_bmns, read_wout_mod::ln_bsubsmnc, read_wout_mod::ln_bsubsmns, read_wout_mod::ln_bsubumnc, read_wout_mod::ln_bsubumns, read_wout_mod::ln_bsubvmnc, read_wout_mod::ln_bsubvmns, read_wout_mod::ln_bsupumnc, read_wout_mod::ln_bsupumns, read_wout_mod::ln_bsupvmnc, read_wout_mod::ln_bsupvmns, read_wout_mod::ln_buco, read_wout_mod::ln_bvco, read_wout_mod::ln_chi, read_wout_mod::ln_chipf, read_wout_mod::ln_ctor, read_wout_mod::ln_curlab, read_wout_mod::ln_equif, read_wout_mod::ln_error, read_wout_mod::ln_extcur, read_wout_mod::ln_extension, read_wout_mod::ln_fp, read_wout_mod::ln_free, read_wout_mod::ln_fsq, read_wout_mod::ln_gam, read_wout_mod::ln_gmnc, read_wout_mod::ln_gmns, read_wout_mod::ln_iotaf, read_wout_mod::ln_iotah, read_wout_mod::ln_jcuru, read_wout_mod::ln_jcurv, read_wout_mod::ln_jdotb, read_wout_mod::ln_lar, read_wout_mod::ln_lmnc, read_wout_mod::ln_lmns, read_wout_mod::ln_magen, read_wout_mod::ln_mass, read_wout_mod::ln_maxit, read_wout_mod::ln_maxmod, read_wout_mod::ln_maxmod_nyq, read_wout_mod::ln_maxr, read_wout_mod::ln_maxz, read_wout_mod::ln_mcurr, read_wout_mod::ln_merc, read_wout_mod::ln_mgeo, read_wout_mod::ln_mgrid, read_wout_mod::ln_minr, read_wout_mod::ln_modb, read_wout_mod::ln_mse, read_wout_mod::ln_mshear, read_wout_mod::ln_mwell, read_wout_mod::ln_pbeta, read_wout_mod::ln_pcurr_type, read_wout_mod::ln_phi, read_wout_mod::ln_phip, read_wout_mod::ln_phipf, read_wout_mod::ln_piota_type, read_wout_mod::ln_pmass_type, read_wout_mod::ln_pmod, read_wout_mod::ln_pmod_nyq, read_wout_mod::ln_polmod, read_wout_mod::ln_potvac, read_wout_mod::ln_presf, read_wout_mod::ln_presh, read_wout_mod::ln_qfact, read_wout_mod::ln_racc, read_wout_mod::ln_racs, read_wout_mod::ln_radnod, read_wout_mod::ln_rbc, read_wout_mod::ln_rbs, read_wout_mod::ln_rbt0, read_wout_mod::ln_rbt1, read_wout_mod::ln_rmaj, read_wout_mod::ln_rmnc, read_wout_mod::ln_rmns, read_wout_mod::ln_sgs, read_wout_mod::ln_specw, read_wout_mod::ln_tbeta, read_wout_mod::ln_therm, read_wout_mod::ln_thom, read_wout_mod::ln_tmod, read_wout_mod::ln_tmod_nyq, read_wout_mod::ln_tormod, read_wout_mod::ln_version, read_wout_mod::ln_vol, read_wout_mod::ln_vp, read_wout_mod::ln_wdot, read_wout_mod::ln_zacc, read_wout_mod::ln_zacs, read_wout_mod::ln_zbc, read_wout_mod::ln_zbs, read_wout_mod::ln_zmnc, read_wout_mod::ln_zmns, vmec_main::lthreed, vmec_main::mass, mgrid_mod::mgrid_mode, vmec_params::mnyq, vmec_params::mscale, vmec_main::neqs, mgrid_mod::nextcur, vmec_params::nnyq, vmec_input::ns_array, vmec_params::nscale, vmec_params::ntmax, vmec_main::overr, vmec_main::phi, realspace::phip, vmec_main::phipf, vmec_main::phips, vacmod::potvac, vmec_main::pres, vmec_main::presf, vmec_main::r0scale, vmec_main::rbtor, vmec_main::rbtor0, vmec_io::rmajor_p, vmec_io::rmax_surf, vmec_io::rmin_surf, vmec_params::rsc, vmec_params::rss, vmec_params::signgs, vmec_persistent::sinmui, vmec_persistent::sinnv, vmec_main::sm, vmec_main::sp, vmec_main::specw, symoutput(), vmec_params::version_, read_wout_mod::vn_abeta, read_wout_mod::vn_ac, read_wout_mod::vn_ac_aux_f, read_wout_mod::vn_ac_aux_s, read_wout_mod::vn_ai, read_wout_mod::vn_ai_aux_f, read_wout_mod::vn_ai_aux_s, read_wout_mod::vn_am, read_wout_mod::vn_am_aux_f, read_wout_mod::vn_am_aux_s, read_wout_mod::vn_amin, read_wout_mod::vn_aspect, read_wout_mod::vn_asym, read_wout_mod::vn_b0, read_wout_mod::vn_beta, read_wout_mod::vn_betah, read_wout_mod::vn_bgrv, read_wout_mod::vn_bmnc, read_wout_mod::vn_bmns, read_wout_mod::vn_bsubsmnc, read_wout_mod::vn_bsubsmns, read_wout_mod::vn_bsubumnc, read_wout_mod::vn_bsubumns, read_wout_mod::vn_bsubvmnc, read_wout_mod::vn_bsubvmns, read_wout_mod::vn_bsupumnc, read_wout_mod::vn_bsupumns, read_wout_mod::vn_bsupvmnc, read_wout_mod::vn_bsupvmns, read_wout_mod::vn_buco, read_wout_mod::vn_bvco, read_wout_mod::vn_chi, read_wout_mod::vn_chipf, read_wout_mod::vn_ctor, read_wout_mod::vn_curlab, read_wout_mod::vn_equif, read_wout_mod::vn_error, read_wout_mod::vn_extcur, read_wout_mod::vn_extension, read_wout_mod::vn_fp, read_wout_mod::vn_free, read_wout_mod::vn_fsq, read_wout_mod::vn_fsql, read_wout_mod::vn_fsqr, read_wout_mod::vn_fsqz, read_wout_mod::vn_ftolv, read_wout_mod::vn_gam, read_wout_mod::vn_gmnc, read_wout_mod::vn_gmns, read_wout_mod::vn_iotaf, read_wout_mod::vn_iotah, read_wout_mod::vn_jcuru, read_wout_mod::vn_jcurv, read_wout_mod::vn_jdotb, read_wout_mod::vn_lar, read_wout_mod::vn_lmnc, read_wout_mod::vn_lmns, read_wout_mod::vn_magen, read_wout_mod::vn_mass, read_wout_mod::vn_maxit, read_wout_mod::vn_maxmod, read_wout_mod::vn_maxmod_nyq, read_wout_mod::vn_maxr, read_wout_mod::vn_maxz, read_wout_mod::vn_mcurr, read_wout_mod::vn_merc, read_wout_mod::vn_mgeo, mgrid_mod::vn_mgmode, read_wout_mod::vn_mgrid, read_wout_mod::vn_minr, read_wout_mod::vn_modb, read_wout_mod::vn_mshear, read_wout_mod::vn_mwell, mgrid_mod::vn_nextcur, read_wout_mod::vn_overr, read_wout_mod::vn_pbeta, read_wout_mod::vn_pcurr_type, read_wout_mod::vn_phi, read_wout_mod::vn_phip, read_wout_mod::vn_phipf, read_wout_mod::vn_piota_type, read_wout_mod::vn_pmass_type, read_wout_mod::vn_pmod, read_wout_mod::vn_pmod_nyq, read_wout_mod::vn_polmod, read_wout_mod::vn_potvac, read_wout_mod::vn_presf, read_wout_mod::vn_presh, read_wout_mod::vn_qfact, read_wout_mod::vn_racc, read_wout_mod::vn_racs, read_wout_mod::vn_radnod, read_wout_mod::vn_rbc, read_wout_mod::vn_rbs, read_wout_mod::vn_rbt0, read_wout_mod::vn_rbt1, read_wout_mod::vn_rmaj, read_wout_mod::vn_rmnc, read_wout_mod::vn_rmns, read_wout_mod::vn_sgs, read_wout_mod::vn_specw, read_wout_mod::vn_tbeta, read_wout_mod::vn_therm, read_wout_mod::vn_tmod, read_wout_mod::vn_tmod_nyq, read_wout_mod::vn_tormod, read_wout_mod::vn_version, read_wout_mod::vn_vol, read_wout_mod::vn_vp, read_wout_mod::vn_wdot, read_wout_mod::vn_zacc, read_wout_mod::vn_zacs, read_wout_mod::vn_zbc, read_wout_mod::vn_zbs, read_wout_mod::vn_zmnc, read_wout_mod::vn_zmns, vmec_io::volavgb, vmec_io::volume_p, vmec_main::vp, vmec_main::wb, vmec_main::wp, xstuff::xc, vmec_persistent::xm, vmec_persistent::xm_nyq, vmec_persistent::xn, vmec_persistent::xn_nyq, realspace::z1, vmec_params::zcc, vmec_params::zcs, and vmec_io::zmax_surf.
Referenced by fileout().