VMEC: vmercier Module Reference
vmercier Module Reference
Variables
real(rprec), dimension(nsd) dshear
real(rprec), dimension(nsd) dwell
real(rprec), dimension(nsd) dcurr
real(rprec), dimension(nsd) dmerc
real(rprec), dimension(nsd) dgeod
Variable Documentation
dcurr
real(rprec), dimension(nsd) vmercier::dcurr
Definition at line 10 of file vmercier.f90.
Referenced by mercier(), and wrout().
dgeod
real(rprec), dimension(nsd) vmercier::dgeod
Definition at line 12 of file vmercier.f90.
Referenced by mercier(), and wrout().
dmerc
real(rprec), dimension(nsd) vmercier::dmerc
Definition at line 11 of file vmercier.f90.
Referenced by mercier(), and wrout().
dshear
real(rprec), dimension(nsd) vmercier::dshear
Definition at line 8 of file vmercier.f90.
Referenced by mercier(), and wrout().
dwell
real(rprec), dimension(nsd) vmercier::dwell
Definition at line 9 of file vmercier.f90.
Referenced by mercier(), and wrout().