VMEC: src/NESTOR/vacuum.f90 File Reference
vacuum.f90 File Reference
Compute the vacuum contribution to the free-boundary energy functional.
Functions/Subroutines
subroutine vacuum (rmnc, rmns, zmns, zmnc, xm, xn, plascur, rbtor, wint, ivac_skip, ivac, mnmax, ier_flag, lasym, signgs, raxis, zaxis)
Compute the vacuum contribution to the free-boundary energy functional.
Detailed Description
Compute the vacuum contribution to the free-boundary energy functional.
Definition in file vacuum.f90.
Function/Subroutine Documentation
vacuum()
subroutine vacuum (real(rprec), dimension(mnmax), intent(in) rmnc, real(rprec), dimension(mnmax), intent(in) rmns, real(rprec), dimension(mnmax), intent(in) zmns, real(rprec), dimension(mnmax), intent(in) zmnc, real(rprec), dimension(mnmax), intent(in) xm, real(rprec), dimension(mnmax), intent(in) xn, real(rprec), intent(in) plascur, real(rprec), intent(in) rbtor, real(rprec), dimension(nuv2), intent(in) wint, integer, intent(in) ivac_skip, integer, intent(inout) ivac, integer, intent(in) mnmax, integer, intent(inout) ier_flag, logical, intent(in) lasym, real(rprec), intent(in) signgs, real(rprec), dimension(nv), intent(in) raxis, real(rprec), dimension(nv), intent(in) zaxis)
Compute the vacuum contribution to the free-boundary energy functional.
Parameters
rmnc
rmns
zmns
zmnc
xm
xn
plascur
rbtor
wint
ivac_skip
ivac
mnmax
ier_flag
lasym
signgs
raxis
zaxis
Definition at line 23 of file vacuum.f90.
References vacmod::amatrix, bextern(), vacmod::bexu, vacmod::bexv, vacmod::bphiv, vacmod::brv, vacmod::bsqvac, vacmod::bsubu, vacmod::bsubv, vacmod::bsubvvac, vacmod::bzv, vacmod::guu_b, vacmod::guv_b, vacmod::gvv_b, vacmod::m_map_wrt, vacmod::n_map_wrt, vmec_params::norm_term_flag, vacmod::p5, vmec_params::phiedge_error_flag, vacmod::pi2, vacmod::potu, vacmod::potv, vacmod::potvac, precal(), vacmod::precal_done, vacmod::r1b, vacmod::raxis_nestor, vacmod::rub, vacmod::rvb, scalpot(), solver(), surface(), vacmod::zaxis_nestor, vacmod::zub, and vacmod::zvb.
Referenced by funct3d(), and nestor().