VMEC: src/residue_con.f90 File Reference
residue_con.f90 File Reference
Compute invariant residuals.
Functions/Subroutines
subroutine residue_con (gcr, gcz, gcl, fsqrz, old_fsqz)
Compute invariant residuals.
Detailed Description
Compute invariant residuals.
Definition in file residue_con.f90.
Function/Subroutine Documentation
residue_con()
subroutine residue_con (real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) gcr, real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) gcz, real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) gcl, real(rprec), intent(in) fsqrz, real(rprec), intent(in) old_fsqz)
Compute invariant residuals.
Parameters
gcr \(R\)-component of forces
gcz \(Z\)-component of forces
gcl \(\lambda\)-component of forces
Definition at line 9 of file residue_con.f90.
References vmec_main::ard, vmec_main::arm, vmec_main::azd, vmec_main::azm, vmec_main::brd, vmec_main::brm, vmec_main::bzd, vmec_main::bzm, constrain_m1(), vmec_main::crd, vmec_main::fnorm, vmec_main::fnorm1, vmec_main::fsqr1_con, vmec_main::fsqr_con, vmec_main::fsqz1_con, vmec_main::fsqz_con, getfsq(), vmec_main::iter1, vmec_main::iter2, vmec_main::lthreed, vmec_params::meven, vmec_params::modd, vmec_params::ntmax, vmec_main::r0scale, vmec_params::rsc, vmec_params::rss, scale_m1(), scalfor(), vmec_params::zcc, and vmec_params::zcs.
Referenced by funct3d().