VMEC: src/readin.f90 File Reference
readin.f90 File Reference
Read the input file.
Functions/Subroutines
subroutine readin (input_file, ier_flag)
Read the input file.
Detailed Description
Read the input file.
Definition in file readin.f90.
Function/Subroutine Documentation
readin()
subroutine readin (character(len=*) input_file, integer, intent(inout) ier_flag)
Read the input file.
Parameters
input_file input file to read from
ier_flag error flag
Definition at line 8 of file readin.f90.
References allocate_nunv(), mgrid_mod::curlabel, vmec_main::currv, theta_flip::flip_theta(), heading(), vmec_main::lconm1, vmec_main::lflip, vmec_main::lthreed, vmec_main::multi_ns_grid, mgrid_mod::nextcur, vmec_params::norm_term_flag, mgrid_mod::np0b, mgrid_mod::nr0b, mgrid_mod::nz0b, dbgout::open_dbg_context(), vmec_params::rcc, vmec_params::rcs, read_indata(), mgrid_mod::read_mgrid(), mgrid_mod::rmaxb, mgrid_mod::rminb, vmec_main::rmn_bdy, vmec_params::rsc, vmec_params::rss, vmec_params::signgs, vmec_params::zcc, vmec_params::zcs, mgrid_mod::zmaxb, mgrid_mod::zminb, vmec_main::zmn_bdy, vmec_params::zsc, and vmec_params::zss.
Referenced by vmec().