VMEC: read_wout_mod::read_wout_file Interface Reference
read_wout_mod::read_wout_file Interface Reference
Public Member Functions
subroutine readw_and_open (file_or_extension, ierr, iopen)
Detailed Description
Definition at line 239 of file read_wout_mod.f.
Member Function/Subroutine Documentation
readw_and_open()
subroutine read_wout_mod::read_wout_file::readw_and_open (character(len=*), intent(in) file_or_extension, integer, intent(out) ierr, integer, optional iopen)
Definition at line 249 of file read_wout_mod.f.
References read_wout_mod::ac, read_wout_mod::ac_aux_f, read_wout_mod::ac_aux_s, read_wout_mod::ai, read_wout_mod::ai_aux_f, read_wout_mod::ai_aux_s, read_wout_mod::am, read_wout_mod::am_aux_f, read_wout_mod::am_aux_s, read_wout_mod::aminor, read_wout_mod::aspect, read_wout_mod::b0, read_wout_mod::bdotgradv, read_wout_mod::beta_vol, read_wout_mod::betapol, read_wout_mod::betator, read_wout_mod::betatot, read_wout_mod::betaxis, read_wout_mod::bmnc, read_wout_mod::bmns, read_wout_mod::bsubsmnc, read_wout_mod::bsubsmns, read_wout_mod::bsubumnc, read_wout_mod::bsubumns, read_wout_mod::bsubvmnc, read_wout_mod::bsubvmns, read_wout_mod::bsupumnc, read_wout_mod::bsupumns, read_wout_mod::bsupvmnc, read_wout_mod::bsupvmns, read_wout_mod::buco, read_wout_mod::bvco, read_wout_mod::chi, read_wout_mod::chipf, read_wout_mod::compute_currents(), mgrid_mod::curlabel, read_wout_mod::dcurr, read_wout_mod::dgeod, read_wout_mod::dmerc, read_wout_mod::dshear, read_wout_mod::dwell, read_wout_mod::equif, read_wout_mod::extcur, read_wout_mod::fsql, read_wout_mod::fsqr, read_wout_mod::fsqt, read_wout_mod::fsqz, read_wout_mod::ftolv, read_wout_mod::gamma, read_wout_mod::gmnc, read_wout_mod::gmns, read_wout_mod::iasym, read_wout_mod::ierr_vmec, read_wout_mod::imse, read_wout_mod::input_extension, read_wout_mod::ionlarmor, read_wout_mod::iotaf, read_wout_mod::iotas, read_wout_mod::isigng, read_wout_mod::itfsq, read_wout_mod::itor, read_wout_mod::jcuru, read_wout_mod::jcurv, read_wout_mod::jdotb, read_wout_mod::lasym, read_wout_mod::lmnc, read_wout_mod::lmns, read_wout_mod::lthreed, read_wout_mod::lwout_opened, read_wout_mod::mass, read_wout_mod::mgrid_file, mgrid_mod::mgrid_mode, read_wout_mod::mnmax, read_wout_mod::mnmax_nyq, read_wout_mod::mnyq, read_wout_mod::mpol, stel_constants::mu0, mgrid_mod::nextcur, read_wout_mod::nfp, read_wout_mod::niter, read_wout_mod::nnyq, read_wout_mod::ns, read_wout_mod::ntor, read_wout_mod::overr, parse_extension(), read_wout_mod::pcurr_type, read_wout_mod::phi, read_wout_mod::phip, read_wout_mod::phipf, read_wout_mod::piota_type, read_wout_mod::pmass_type, read_wout_mod::potvac, read_wout_mod::pres, read_wout_mod::presf, read_wout_mod::qfact, read_wout_mod::raxis, read_wout_mod::rbtor, read_wout_mod::rbtor0, read_wout_mod::read_wout_deallocate(), read_wout_mod::rmajor, read_wout_mod::rmax_surf, read_wout_mod::rmin_surf, read_wout_mod::rmnc, read_wout_mod::rmns, read_wout_mod::specw, read_wout_mod::version_, read_wout_mod::vn_abeta, read_wout_mod::vn_ac, read_wout_mod::vn_ac_aux_f, read_wout_mod::vn_ac_aux_s, read_wout_mod::vn_actit, read_wout_mod::vn_ai, read_wout_mod::vn_ai_aux_f, read_wout_mod::vn_ai_aux_s, read_wout_mod::vn_am, read_wout_mod::vn_am_aux_f, read_wout_mod::vn_am_aux_s, read_wout_mod::vn_amin, read_wout_mod::vn_aspect, read_wout_mod::vn_asym, read_wout_mod::vn_b0, read_wout_mod::vn_beta, read_wout_mod::vn_betah, read_wout_mod::vn_bgrv, read_wout_mod::vn_bmnc, read_wout_mod::vn_bmns, read_wout_mod::vn_bsubsmnc, read_wout_mod::vn_bsubsmns, read_wout_mod::vn_bsubumnc, read_wout_mod::vn_bsubumns, read_wout_mod::vn_bsubvmnc, read_wout_mod::vn_bsubvmns, read_wout_mod::vn_bsupumnc, read_wout_mod::vn_bsupumns, read_wout_mod::vn_bsupvmnc, read_wout_mod::vn_bsupvmns, read_wout_mod::vn_buco, read_wout_mod::vn_bvco, read_wout_mod::vn_chi, read_wout_mod::vn_chipf, read_wout_mod::vn_ctor, read_wout_mod::vn_curlab, read_wout_mod::vn_equif, read_wout_mod::vn_error, read_wout_mod::vn_extcur, read_wout_mod::vn_extension, read_wout_mod::vn_fp, read_wout_mod::vn_free, read_wout_mod::vn_fsq, read_wout_mod::vn_fsql, read_wout_mod::vn_fsqr, read_wout_mod::vn_fsqz, read_wout_mod::vn_ftolv, read_wout_mod::vn_gam, read_wout_mod::vn_gmnc, read_wout_mod::vn_gmns, read_wout_mod::vn_iotaf, read_wout_mod::vn_iotah, read_wout_mod::vn_jcuru, read_wout_mod::vn_jcurv, read_wout_mod::vn_jdotb, read_wout_mod::vn_lar, read_wout_mod::vn_lmnc, read_wout_mod::vn_lmns, read_wout_mod::vn_magen, read_wout_mod::vn_mass, read_wout_mod::vn_maxit, read_wout_mod::vn_maxmod, read_wout_mod::vn_maxmod_nyq, read_wout_mod::vn_maxr, read_wout_mod::vn_maxz, read_wout_mod::vn_mcurr, read_wout_mod::vn_merc, read_wout_mod::vn_mgeo, mgrid_mod::vn_mgmode, read_wout_mod::vn_mgrid, read_wout_mod::vn_minr, read_wout_mod::vn_modb, read_wout_mod::vn_mshear, read_wout_mod::vn_mwell, mgrid_mod::vn_nextcur, read_wout_mod::vn_overr, read_wout_mod::vn_pbeta, read_wout_mod::vn_pcurr_type, read_wout_mod::vn_phi, read_wout_mod::vn_phip, read_wout_mod::vn_phipf, read_wout_mod::vn_piota_type, read_wout_mod::vn_pmass_type, read_wout_mod::vn_pmod, read_wout_mod::vn_pmod_nyq, read_wout_mod::vn_polmod, read_wout_mod::vn_potvac, read_wout_mod::vn_presf, read_wout_mod::vn_presh, read_wout_mod::vn_qfact, read_wout_mod::vn_racc, read_wout_mod::vn_racs, read_wout_mod::vn_radnod, read_wout_mod::vn_rbt0, read_wout_mod::vn_rbt1, read_wout_mod::vn_rmaj, read_wout_mod::vn_rmnc, read_wout_mod::vn_rmns, read_wout_mod::vn_sgs, read_wout_mod::vn_specw, read_wout_mod::vn_tbeta, read_wout_mod::vn_therm, read_wout_mod::vn_tmod, read_wout_mod::vn_tmod_nyq, read_wout_mod::vn_tormod, read_wout_mod::vn_version, read_wout_mod::vn_vol, read_wout_mod::vn_vp, read_wout_mod::vn_wdot, read_wout_mod::vn_zacc, read_wout_mod::vn_zacs, read_wout_mod::vn_zmnc, read_wout_mod::vn_zmns, read_wout_mod::volavgb, read_wout_mod::volume, read_wout_mod::vp, read_wout_mod::wb, read_wout_mod::wdot, read_wout_mod::wp, read_wout_mod::xm, read_wout_mod::xm_nyq, read_wout_mod::xn, read_wout_mod::xn_nyq, read_wout_mod::zaxis, read_wout_mod::zmax_surf, read_wout_mod::zmnc, and read_wout_mod::zmns.