VMEC: src/eqsolve.f90 File Reference
eqsolve.f90 File Reference
Iteratively evolve the Fourier coefficients that specify the equilibrium.
Functions/Subroutines
subroutine eqsolve (ier_flag)
Iteratively evolve the Fourier coefficients that specify the equilibrium.
Detailed Description
Iteratively evolve the Fourier coefficients that specify the equilibrium.
Definition in file eqsolve.f90.
Function/Subroutine Documentation
eqsolve()
subroutine eqsolve (integer, intent(inout) ier_flag)
Iteratively evolve the Fourier coefficients that specify the equilibrium.
Parameters
ier_flag error flag
Definition at line 7 of file eqsolve.f90.
References vmec_params::bad_jacobian_flag, vmec_main::delt0r, evolve(), vmec_main::fsq, vmec_main::fsqr, vmec_main::fsqz, guess_axis(), vmec_main::ijacob, vmec_main::irst, vmec_main::irzloff, vmec_main::iter1, vmec_main::iter2, vmec_main::ivac, vmec_params::jac75_flag, vmec_main::niterv, vmec_params::norm_term_flag, vmec_params::ns4, printout(), profil3d(), realspace::r1, vmec_main::res0, restart_iter(), realspace::ru0, vmec_params::successful_term_flag, vmec_main::wb, vmec_main::wp, xstuff::xc, realspace::z1, and realspace::zu0.
Referenced by vmec().