VMEC: src/spline_cubic.f File Reference
spline_cubic.f File Reference
Functions/Subroutines
subroutine spline_cubic (x, y, xx, yy, n, iflag)
subroutine spline_nr (x, y, n, yp1, ypn, y2)
subroutine splint_nr (xa, ya, y2a, n, x, y)
Function/Subroutine Documentation
spline_cubic()
subroutine spline_cubic (real(rprec), intent(in) x, real(rprec), intent(out) y, real(rprec), dimension(n), intent(in) xx, real(rprec), dimension(n), intent(in) yy, integer, intent(in) n, integer, intent(inout) iflag)
Definition at line 2 of file spline_cubic.f.
References spline_nr(), and splint_nr().
Referenced by pcurr(), piota(), and pmass().
spline_nr()
subroutine spline_cubic::spline_nr (real(rprec), dimension(n), intent(in) x, real(rprec), dimension(n), intent(in) y, integer, intent(in) n, real(rprec), intent(in) yp1, real(rprec), intent(in) ypn, real(rprec), dimension(n), intent(out) y2)
Definition at line 56 of file spline_cubic.f.
Referenced by spline_cubic().
splint_nr()
subroutine spline_cubic::splint_nr (real(rprec), dimension(n), intent(in) xa, real(rprec), dimension(n), intent(in) ya, real(rprec), dimension(n), intent(in) y2a, integer, intent(in) n, real(rprec), intent(in) x, real(rprec), intent(out) y)
Definition at line 105 of file spline_cubic.f.
Referenced by spline_cubic().