VMEC: src/magnetic_fluxes.f90 File Reference
magnetic_fluxes.f90 File Reference
Compute toroidal and poloidal magnetic flux profiles.
Functions/Subroutines
real(rprec) function torflux_deriv (x)
Compute the radial derivative of the enclosed toroidal magnetic flux.
real(rprec) function polflux_deriv (x)
Compute the radial derivative of the enclosed poloidal magnetic flux.
real(rprec) function torflux (x)
Compute the enclosed toroidal magnetic flux.
real(rprec) function polflux (x)
Compute the enclosed poloidal magnetic flux.
Detailed Description
Compute toroidal and poloidal magnetic flux profiles.
Definition in file magnetic_fluxes.f90.
Function/Subroutine Documentation
polflux()
real(rprec) function polflux (real(rprec), intent(in) x)
Compute the enclosed poloidal magnetic flux.
Parameters
x evaluation location; radial flux variable (=TOROIDAL FLUX ONLY IF APHI=1)
Definition at line 77 of file magnetic_fluxes.f90.
References polflux(), and polflux_deriv().
Referenced by polflux().
polflux_deriv()
real(rprec) function polflux_deriv (real(rprec), intent(in) x)
Compute the radial derivative of the enclosed poloidal magnetic flux.
polflux_deriv == d(chi)/dx = iota(TF(x)) * torflux_deriv(x)
Parameters
x evaluation location; radial flux variable (=TOROIDAL FLUX ONLY IF APHI=1)
Definition at line 30 of file magnetic_fluxes.f90.
References piota(), polflux_deriv(), torflux(), and torflux_deriv().
Referenced by polflux(), and polflux_deriv().
torflux()
real(rprec) function torflux (real(rprec), intent(in) x)
Compute the enclosed toroidal magnetic flux.
Parameters
x evaluation location; radial flux variable (=TOROIDAL FLUX ONLY IF APHI=1)
Definition at line 53 of file magnetic_fluxes.f90.
References torflux(), and torflux_deriv().
Referenced by polflux_deriv(), and torflux().
torflux_deriv()
real(rprec) function torflux_deriv (real(rprec), intent(in) x)
Compute the radial derivative of the enclosed toroidal magnetic flux.
Parameters
x evaluation location; radial flux variable (=TOROIDAL FLUX ONLY IF APHI=1)
Definition at line 7 of file magnetic_fluxes.f90.
References vmec_input::aphi, and torflux_deriv().
Referenced by polflux_deriv(), torflux(), and torflux_deriv().