VMEC: vmec_io Module Reference
vmec_io Module Reference
Variables
real(rprec) volavgb
real(rprec) ionlarmor
real(rprec) aminor_p
real(rprec) rmajor_p
real(rprec) betatot
real(rprec) betapol
real(rprec) betator
real(rprec) betaxis
real(rprec) b0
real(rprec) volume_p
real(rprec) cross_area_p
real(rprec) surf_area_p
real(rprec) circum_p
real(rprec) kappa_p
real(rprec) rmax_surf
real(rprec) rmin_surf
real(rprec) zmax_surf
Variable Documentation
aminor_p
real(rprec) vmec_io::aminor_p
Definition at line 10 of file vmec_io.f90.
Referenced by aspectratio(), eqfor(), and wrout().
b0
real(rprec) vmec_io::b0
Definition at line 16 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
betapol
real(rprec) vmec_io::betapol
Definition at line 13 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
betator
real(rprec) vmec_io::betator
Definition at line 14 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
betatot
real(rprec) vmec_io::betatot
Definition at line 12 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
betaxis
real(rprec) vmec_io::betaxis
Definition at line 15 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
circum_p
real(rprec) vmec_io::circum_p
Definition at line 20 of file vmec_io.f90.
Referenced by eqfor().
cross_area_p
real(rprec) vmec_io::cross_area_p
Definition at line 18 of file vmec_io.f90.
Referenced by aspectratio(), and eqfor().
ionlarmor
real(rprec) vmec_io::ionlarmor
Definition at line 9 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
kappa_p
real(rprec) vmec_io::kappa_p
Definition at line 21 of file vmec_io.f90.
Referenced by eqfor().
rmajor_p
real(rprec) vmec_io::rmajor_p
Definition at line 11 of file vmec_io.f90.
Referenced by aspectratio(), eqfor(), and wrout().
rmax_surf
real(rprec) vmec_io::rmax_surf
Definition at line 22 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
rmin_surf
real(rprec) vmec_io::rmin_surf
Definition at line 23 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
surf_area_p
real(rprec) vmec_io::surf_area_p
Definition at line 19 of file vmec_io.f90.
Referenced by eqfor().
volavgb
real(rprec) vmec_io::volavgb
Definition at line 8 of file vmec_io.f90.
Referenced by eqfor(), and wrout().
volume_p
real(rprec) vmec_io::volume_p
Definition at line 17 of file vmec_io.f90.
Referenced by aspectratio(), eqfor(), and wrout().
zmax_surf
real(rprec) vmec_io::zmax_surf
Definition at line 24 of file vmec_io.f90.
Referenced by eqfor(), and wrout().