VMEC: src/bcovar.f90 File Reference
bcovar.f90 File Reference
Compute the covariant components of the magnetic field \(B_\theta\), \(B_\zeta\).
Functions/Subroutines
subroutine bcovar (lu, lv)
Compute the covariant components of the magnetic field \(B_\theta\), \(B_\zeta\).
Detailed Description
Compute the covariant components of the magnetic field \(B_\theta\), \(B_\zeta\).
Definition in file bcovar.f90.
Function/Subroutine Documentation
bcovar()
subroutine bcovar (real(rprec), dimension(nrzt,0:1), intent(inout) lu, real(rprec), dimension(nrzt,0:1), intent(inout) lv)
Compute the covariant components of the magnetic field \(B_\theta\), \(B_\zeta\).
Parameters
lu \(\partial\lambda / \partial\theta\)
lv \(- \partial\lambda / \partial\zeta\)
R12 from RP in force
Norm, unpreconditioned R,Z forces
Norm for preconditioned R,Z forces
Norm for unpreconditioned Lambda force
Definition at line 8 of file bcovar.f90.
References add_fluxes(), vmec_main::ard, vmec_main::arm, vforces::armn_e, vforces::armn_o, vmec_main::azd, vmec_main::azm, vforces::azmn_e, vforces::azmn_o, vmec_main::bdamp, vforces::blmn_e, vforces::blmn_o, vmec_main::brd, vmec_main::brm, vforces::brmn_e, vforces::brmn_o, vmec_main::buco, vmec_main::bvco, vmec_main::bzd, vmec_main::bzm, vforces::bzmn_e, vforces::bzmn_o, calc_fbal(), vforces::clmn_e, vforces::clmn_o, vmec_main::crd, vmec_main::ctor, dbgout::dump_bcontrav, dbgout::dump_bcov, dbgout::dump_bcov_full, dbgout::dump_filename, dbgout::dump_forcenorms_tcon, dbgout::dump_lambda_forces, dbgout::dump_lulv_comb, dbgout::dump_metric, dbgout::dump_precondn, dbgout::dump_volume, realspace::extra1, realspace::extra2, realspace::extra3, realspace::extra4, vmec_main::fnorm, vmec_main::fnorm1, vmec_main::fnorml, fbal::frcc_fac, fbal::fzsc_fac, realspace::guu, realspace::guv, realspace::gvv, vmec_main::hs, vmec_main::iequi, vmec_main::irzloff, vmec_main::iter1, vmec_main::iter2, lamcal(), vmec_params::lamscale, vmec_main::lthreed, vmec_main::mass, dbgout::max_dump, vmec_params::meven, vmec_params::modd, vmec_params::ns4, vmec_params::ntmax, vmec_params::pdamp, vmec_main::phipf, precondn(), vmec_main::pres, vmec_main::r0scale, realspace::r1, vmec_main::rbtor, vmec_main::rbtor0, fbal::rru_fac, realspace::ru, realspace::ru0, realspace::rv, fbal::rzu_fac, realspace::shalf, vmec_params::signgs, realspace::sqrts, vmec_main::tcon, vmec_main::voli, vmec_main::vp, vmec_main::wb, realspace::wint, vmec_main::wp, xstuff::xc, realspace::z1, realspace::zu, realspace::zu0, and realspace::zv.
Referenced by funct3d().