VMEC: src/NESTOR/nestor_main.f90 File Reference
nestor_main.f90 File Reference
Main program of stand-alone version of NESTOR.
Functions/Subroutines
program nestor
Main program of stand-alone version of NESTOR.
Detailed Description
Main program of stand-alone version of NESTOR.
Definition in file nestor_main.f90.
Function/Subroutine Documentation
nestor()
program nestor
Main program of stand-alone version of NESTOR.
Definition at line 5 of file nestor_main.f90.
References vacmod::allocate_nestor(), vacmod::amatsav, nestor_io::amatsav_nestor, vacmod::bsubvvac, nestor_io::bsubvvac_nestor, vacmod::bvecsav, nestor_io::bvecsav_nestor, nestor_io::ctor, stel_kinds::dp, vacmod::free_mem_nestor(), nestor_io::ier_flag, nestor_io::input_extension, nestor_io::ivac, nestor_io::ivacskip, nestor_io::lasym, nestor_io::mnmax, nestor_io::mpol, nestor_io::nfp, nestor_io::ntheta, nestor_io::ntor, nestor_io::nzeta, nestor_io::raxis, nestor_io::rbtor, nestor_io::read_nestor_inputs(), nestor_io::rmnc, nestor_io::rmns, vacmod0::set_nestor_sizes(), nestor_io::signgs, vacuum(), nestor_io::vacuum_calls, nestor_io::wint, nestor_io::write_nestor_outputs(), nestor_io::xm, nestor_io::xn, nestor_io::zaxis, nestor_io::zmnc, and nestor_io::zmns.