VMEC: src/profil3d.f90 File Reference
profil3d.f90 File Reference
Compute three-dimensional profiles of flux-surface geometry etc.
Functions/Subroutines
subroutine profil3d (rmn, zmn, lreset)
Compute three-dimensional profiles of flux-surface geometry etc.
Detailed Description
Compute three-dimensional profiles of flux-surface geometry etc.
Definition in file profil3d.f90.
Function/Subroutine Documentation
profil3d()
subroutine profil3d (real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) rmn, real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) zmn, logical, intent(in) lreset)
Compute three-dimensional profiles of flux-surface geometry etc.
Parameters
rmn Fourier coefficients of \(R\)
zmn Fourier coefficients of \(R\)
lreset flag to indicate the geometry of the LCFS (and axis ?) should be used to interpolate into the plasma volume
Definition at line 9 of file profil3d.f90.
References realspace::chip, vmec_main::chips, vmec_main::faclam, vmec_main::ireflect, vmec_main::irzloff, vmec_params::mscale, vmec_params::nscale, vmec_params::ntmax, dbgout::open_dbg_context(), realspace::phip, vmec_main::phips, vmec_main::profil3d_calls, vmec_params::rcc, vmec_params::rcs, vmec_main::rmn_bdy, xstuff::scalxc, realspace::sqrts, vmec_params::uminus, realspace::wint, vmec_params::zcc, vmec_params::zcs, and vmec_main::zmn_bdy.
Referenced by eqsolve(), and initialize_radial().