#!/bin/bash

### Set the job name
#PBS -N boozxform

### Set the number of nodes that will be used.
#PBS -l mppwidth=24
#PBS -l walltime=00:30:00

### Set the queue to submit this job.
#PBS -q debug

#PBS -V
#PBS -j oe

cd $PBS_O_WORKDIR
aprun -n 1 /global/homes/l/landrema/bin_edison/xbooz_xform in_booz.HSX_QHS_vac

