VMEC: nestor_io Module Reference
nestor_io Module Reference
Input and Output for stand-alone NESTOR.
Functions/Subroutines
subroutine read_nestor_inputs (vac_file)
subroutine write_nestor_outputs (vac_file, lasym, ivac, ier_flag)
Variables
character(len=255) input_extension
character(len=255) mgrid_file
real(dp), dimension(:), allocatable extcur
real(dp), dimension(:), allocatable raxis
real(dp), dimension(:), allocatable zaxis
real(dp), dimension(:), allocatable xm
real(dp), dimension(:), allocatable xn
real(dp), dimension(:), allocatable rmnc
real(dp), dimension(:), allocatable zmns
real(dp), dimension(:), allocatable rmns
real(dp), dimension(:), allocatable zmnc
real(dp), dimension(:), allocatable wint
integer nfp
integer ntor
integer mpol
integer ntheta
integer nzeta
integer nextcur
integer ier_flag
integer ivac
integer ivacskip
integer mnmax
integer vacuum_calls
logical lasym
real(dp) ctor
real(dp) rbtor
real(dp) signgs
integer mnpd2_nestor
real(dp), dimension(:), allocatable amatsav_nestor
real(dp), dimension(:), allocatable bvecsav_nestor
real(dp) bsubvvac_nestor
character(len= *), dimension(1), parameter mn1dim = (/'mn_mode'/)
character(len= *), dimension(1), parameter mnpotdim = (/'mn_mode_pot'/)
character(len= *), dimension(1), parameter nzntdim = (/'nznt'/)
character(len= *), dimension(1), parameter nzetadim = (/'nzeta'/)
character(len= *), dimension(1), parameter nextcurim = (/'nextcur'/)
character(len= *), dimension(1), parameter bvecsavdim =(/'mnpd2'/)
character(len= *), dimension(1), parameter amatsavdim =(/'mnpd2_times_mnpd2'/)
character(len= *), dimension(2), parameter r2dim = (/'mn_mode','radius '/)
character(len= *), parameter vn_vacuum_calls = 'vacuum_calls'
character(len= *), parameter vn_ier_flag = "ier_flag"
character(len= *), parameter vn_mgrid = "mgrid_file"
character(len= *), parameter vn_inputext = "input_extension"
character(len= *), parameter vn_ivacskip = "ivacskip"
character(len= *), parameter vn_ivac = "ivac"
character(len= *), parameter vn_nfp = "nfp"
character(len= *), parameter vn_ntor = "ntor"
character(len= *), parameter vn_mpol = "mpol"
character(len= *), parameter vn_nzeta = "nzeta"
character(len= *), parameter vn_ntheta = "ntheta"
character(len= *), parameter vn_mnmax = "mnmax"
character(len= *), parameter vn_pmod = "xm"
character(len= *), parameter vn_tmod = "xn"
character(len= *), parameter vn_rmnc = "rmnc"
character(len= *), parameter vn_zmns = "zmns"
character(len= *), parameter vn_rmns = "rmns"
character(len= *), parameter vn_zmnc = "zmnc"
character(len= *), parameter vn_rbtor = "rbtor"
character(len= *), parameter vn_ctor = "ctor"
character(len= *), parameter vn_lasym = "lasym"
character(len= *), parameter vn_signgs = "signgs"
character(len= *), parameter vn_extcur = "extcur"
character(len= *), parameter vn_raxis_nestor = "raxis_nestor"
character(len= *), parameter vn_zaxis_nestor = "zaxis_nestor"
character(len= *), parameter vn_wint = "wint"
character(len= *), parameter vn_bsqvac = "bsqvac"
character(len= *), parameter vn_mnpd = "mnpd"
character(len= *), parameter vn_xmpot = "xmpot"
character(len= *), parameter vn_xnpot = "xnpot"
character(len= *), parameter vn_potvac = "potvac"
character(len= *), parameter vn_brv = "brv"
character(len= *), parameter vn_bphiv = "bphiv"
character(len= *), parameter vn_bzv = "bzv"
character(len= *), parameter vn_bsubvvac = "bsubvvac"
character(len= *), parameter vn_amatsav = "amatsav"
character(len= *), parameter vn_bvecsav = "bvecsav"
character(len= *), parameter vn_mnpd2 = "mnpd2"
character(len= *), parameter vn_r1b = "r1b"
character(len= *), parameter vn_rub = "rub"
character(len= *), parameter vn_rvb = "rvb"
character(len= *), parameter vn_z1b = "z1b"
character(len= *), parameter vn_zub = "zub"
character(len= *), parameter vn_zvb = "zvb"
character(len= *), parameter vn_ruu = "ruu"
character(len= *), parameter vn_ruv = "ruv"
character(len= *), parameter vn_rvv = "rvv"
character(len= *), parameter vn_zuu = "zuu"
character(len= *), parameter vn_zuv = "zuv"
character(len= *), parameter vn_zvv = "zvv"
character(len= *), parameter vn_guu_b = "guu_b"
character(len= *), parameter vn_guv_b = "guv_b"
character(len= *), parameter vn_gvv_b = "gvv_b"
character(len= *), parameter vn_rzb2 = "rzb2"
character(len= *), parameter vn_snr = "snr"
character(len= *), parameter vn_snv = "snv"
character(len= *), parameter vn_snz = "snz"
character(len= *), parameter vn_drv = "drv"
character(len= *), parameter vn_auu = "auu"
character(len= *), parameter vn_auv = "auv"
character(len= *), parameter vn_avv = "avv"
character(len= *), parameter vn_rcosuv = "rcosuv"
character(len= *), parameter vn_rsinuv = "rsinuv"
character(len= *), parameter vn_brad = "brad"
character(len= *), parameter vn_bphi = "bphi"
character(len= *), parameter vn_bz = "bz"
character(len= *), parameter vn_bexu = "bexu"
character(len= *), parameter vn_bexv = "bexv"
character(len= *), parameter vn_bexn = "bexn"
character(len= *), parameter vn_bexni = "bexni"
character(len= *), parameter vn_grpmn = "grpmn"
character(len= *), parameter vn_adp = "adp"
character(len= *), parameter vn_adm = "adm"
character(len= *), parameter vn_cma = "cma"
character(len= *), parameter vn_sqrtc = "sqrtc"
character(len= *), parameter vn_sqrta = "sqrta"
character(len= *), parameter vn_delt1u = "delt1u"
character(len= *), parameter vn_azp1u = "azp1u"
character(len= *), parameter vn_azm1u = "azm1u"
character(len= *), parameter vn_cma11u = "cma11u"
character(len= *), parameter vn_r1p = "r1p"
character(len= *), parameter vn_r1m = "r1m"
character(len= *), parameter vn_r0p = "r0p"
character(len= *), parameter vn_r0m = "r0m"
character(len= *), parameter vn_ra1p = "ra1p"
character(len= *), parameter vn_ra1m = "ra1m"
character(len= *), parameter vn_sqad1u = "sqad1u"
character(len= *), parameter vn_sqad2u = "sqad2u"
character(len= *), parameter vn_all_tlp = "all_tlp"
character(len= *), parameter vn_all_tlm = "all_tlm"
character(len= *), parameter vn_all_slp = "all_slp"
character(len= *), parameter vn_all_slm = "all_slm"
character(len= *), parameter vn_m_map = "m_map"
character(len= *), parameter vn_n_map = "n_map"
character(len= *), parameter vn_green = "green"
character(len= *), parameter vn_greenp = "greenp"
character(len= *), parameter vn_tanu = "tanu"
character(len= *), parameter vn_tanv = "tanv"
character(len= *), parameter vn_gstore = "gstore"
character(len= *), parameter vn_grpmn_m_map = "grpmn_m_map"
character(len= *), parameter vn_grpmn_n_map = "grpmn_n_map"
character(len= *), parameter vn_imirr = "imirr"
character(len= *), parameter vn_amatrix = "amatrix"
character(len= *), parameter vn_potu = "potu"
character(len= *), parameter vn_potv = "potv"
character(len= *), parameter vn_bsubu = "bsubu"
character(len= *), parameter vn_bsubv = "bsubv"
Detailed Description
Input and Output for stand-alone NESTOR.
Function/Subroutine Documentation
read_nestor_inputs()
subroutine nestor_io::read_nestor_inputs (character(len=*), intent(in) vac_file)
Definition at line 172 of file nestor_io.f90.
References amatsav_nestor, bsubvvac_nestor, bvecsav_nestor, ctor, stel_kinds::dp, extcur, ier_flag, input_extension, ivac, ivacskip, lasym, mgrid_file, mnmax, mnpd2_nestor, mpol, nfp, ntheta, ntor, nzeta, raxis, rbtor, mgrid_mod::read_mgrid(), rmnc, rmns, signgs, vacuum_calls, vn_amatsav, vn_bsubvvac, vn_bvecsav, vn_ctor, vn_extcur, vn_ier_flag, vn_inputext, vn_ivac, vn_ivacskip, vn_lasym, vn_mgrid, vn_mnmax, vn_mnpd2, vn_mpol, mgrid_mod::vn_nfp, vn_ntheta, vn_ntor, vn_nzeta, vn_pmod, vn_raxis_nestor, vn_rbtor, vn_rmnc, vn_rmns, vn_signgs, vn_tmod, vn_vacuum_calls, vn_wint, vn_zaxis_nestor, vn_zmnc, vn_zmns, wint, xm, xn, zaxis, zmnc, and zmns.
Referenced by nestor().
write_nestor_outputs()
subroutine nestor_io::write_nestor_outputs (character(len=*), intent(in) vac_file, logical, intent(in) lasym, integer, intent(in) ivac, integer, intent(in) ier_flag)
Definition at line 290 of file nestor_io.f90.
References vacmod::adm, vacmod::adp, vacmod::all_slm, vacmod::all_slp, vacmod::all_tlm, vacmod::all_tlp, vacmod::amatrix, vacmod::amatsav, vacmod::auu, vacmod::auv, vacmod::avv, vacmod::azm1u, vacmod::azp1u, vacmod::bexn, vacmod::bexni, vacmod::bexu, vacmod::bexv, vacmod::bphi, vacmod::bphiv, vacmod::brad, vacmod::brv, vacmod::bsqvac, vacmod::bsubu, vacmod::bsubv, vacmod::bsubvvac, vacmod::bvecsav, vacmod::bz, vacmod::bzv, vacmod::cma, vacmod::cma11u, vacmod::delt1u, stel_kinds::dp, vacmod::drv, vacmod::green, vacmod::greenp, vacmod::grpmn, vacmod::grpmn_m_map_wrt, vacmod::grpmn_n_map_wrt, vacmod::gstore, vacmod::guu_b, vacmod::guv_b, vacmod::gvv_b, vacmod::m_map_wrt, vacmod::n_map_wrt, vacmod::potu, vacmod::potv, vacmod::potvac, vacmod::r0m, vacmod::r0p, vacmod::r1b, vacmod::r1m, vacmod::r1p, vacmod::ra1m, vacmod::ra1p, vacmod::rcosuv, vacmod::rsinuv, vacmod::rub, vacmod::ruu, vacmod::ruv, vacmod::rvb, vacmod::rvv, vacmod::rzb2, vacmod::snr, vacmod::snv, vacmod::snz, vacmod::sqad1u, vacmod::sqad2u, vacmod::sqrta, vacmod::sqrtc, vn_adm, vn_adp, vn_all_slm, vn_all_slp, vn_all_tlm, vn_all_tlp, vn_amatrix, vn_amatsav, vn_auu, vn_auv, vn_avv, vn_azm1u, vn_azp1u, vn_bexn, vn_bexni, vn_bexu, vn_bexv, vn_bphi, vn_bphiv, vn_brad, vn_brv, vn_bsqvac, vn_bsubu, vn_bsubv, vn_bsubvvac, vn_bvecsav, vn_bz, vn_bzv, vn_cma, vn_cma11u, vn_delt1u, vn_drv, vn_green, vn_greenp, vn_grpmn, vn_grpmn_m_map, vn_grpmn_n_map, vn_gstore, vn_guu_b, vn_guv_b, vn_gvv_b, vn_ier_flag, vn_imirr, vn_ivac, vn_m_map, vn_mnpd, vn_mnpd2, vn_n_map, vn_potu, vn_potv, vn_potvac, vn_r0m, vn_r0p, vn_r1b, vn_r1m, vn_r1p, vn_ra1m, vn_ra1p, vn_rcosuv, vn_rsinuv, vn_rub, vn_ruu, vn_ruv, vn_rvb, vn_rvv, vn_rzb2, vn_snr, vn_snv, vn_snz, vn_sqad1u, vn_sqad2u, vn_sqrta, vn_sqrtc, vn_tanu, vn_tanv, vn_xmpot, vn_xnpot, vn_z1b, vn_zub, vn_zuu, vn_zuv, vn_zvb, vn_zvv, vacmod::z1b, vacmod::zub, vacmod::zuu, vacmod::zuv, vacmod::zvb, and vacmod::zvv.
Referenced by funct3d(), and nestor().
Variable Documentation
amatsav_nestor
real(dp), dimension(:), allocatable nestor_io::amatsav_nestor
Definition at line 41 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
amatsavdim
character(len=*), dimension(1), parameter nestor_io::amatsavdim =(/'mnpd2_times_mnpd2'/)
Definition at line 51 of file nestor_io.f90.
Referenced by write_nestor_inputs().
bsubvvac_nestor
real(dp) nestor_io::bsubvvac_nestor
Definition at line 43 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
bvecsav_nestor
real(dp), dimension(:), allocatable nestor_io::bvecsav_nestor
Definition at line 42 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
bvecsavdim
character(len=*), dimension(1), parameter nestor_io::bvecsavdim =(/'mnpd2'/)
Definition at line 50 of file nestor_io.f90.
Referenced by write_nestor_inputs().
ctor
real(dp) nestor_io::ctor
Definition at line 36 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
extcur
real(dp), dimension(:), allocatable nestor_io::extcur
Definition at line 11 of file nestor_io.f90.
Referenced by funct3d(), and read_nestor_inputs().
ier_flag
integer nestor_io::ier_flag
Definition at line 28 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
input_extension
character(len=255) nestor_io::input_extension
Definition at line 9 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
ivac
integer nestor_io::ivac
Definition at line 29 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
ivacskip
integer nestor_io::ivacskip
Definition at line 30 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
lasym
logical nestor_io::lasym
Definition at line 34 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
mgrid_file
character(len=255) nestor_io::mgrid_file
Definition at line 10 of file nestor_io.f90.
Referenced by funct3d(), and read_nestor_inputs().
mn1dim
character(len=*), dimension(1), parameter nestor_io::mn1dim = (/'mn_mode'/)
Definition at line 45 of file nestor_io.f90.
Referenced by write_nestor_inputs().
mnmax
integer nestor_io::mnmax
Definition at line 31 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
mnpd2_nestor
integer nestor_io::mnpd2_nestor
Definition at line 40 of file nestor_io.f90.
Referenced by read_nestor_inputs().
mnpotdim
character(len=*), dimension(1), parameter nestor_io::mnpotdim = (/'mn_mode_pot'/)
Definition at line 46 of file nestor_io.f90.
Referenced by write_nestor_inputs().
mpol
integer nestor_io::mpol
Definition at line 24 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
nextcur
integer nestor_io::nextcur
Definition at line 27 of file nestor_io.f90.
nextcurim
character(len=*), dimension(1), parameter nestor_io::nextcurim = (/'nextcur'/)
Definition at line 49 of file nestor_io.f90.
Referenced by write_nestor_inputs().
nfp
integer nestor_io::nfp
Definition at line 22 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
ntheta
integer nestor_io::ntheta
Definition at line 25 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
ntor
integer nestor_io::ntor
Definition at line 23 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
nzeta
integer nestor_io::nzeta
Definition at line 26 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
nzetadim
character(len=*), dimension(1), parameter nestor_io::nzetadim = (/'nzeta'/)
Definition at line 48 of file nestor_io.f90.
Referenced by write_nestor_inputs().
nzntdim
character(len=*), dimension(1), parameter nestor_io::nzntdim = (/'nznt'/)
Definition at line 47 of file nestor_io.f90.
Referenced by write_nestor_inputs().
r2dim
character(len=*), dimension(2), parameter nestor_io::r2dim = (/'mn_mode','radius '/)
Definition at line 53 of file nestor_io.f90.
Referenced by write_nestor_inputs().
raxis
real(dp), dimension(:), allocatable nestor_io::raxis
Definition at line 12 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
rbtor
real(dp) nestor_io::rbtor
Definition at line 37 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
rmnc
real(dp), dimension(:), allocatable nestor_io::rmnc
Definition at line 16 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
rmns
real(dp), dimension(:), allocatable nestor_io::rmns
Definition at line 18 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
signgs
real(dp) nestor_io::signgs
Definition at line 38 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
vacuum_calls
integer nestor_io::vacuum_calls
Definition at line 32 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
vn_adm
character(len=*), parameter nestor_io::vn_adm = "adm"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_adp
character(len=*), parameter nestor_io::vn_adp = "adp"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_all_slm
character(len=*), parameter nestor_io::vn_all_slm = "all_slm"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_all_slp
character(len=*), parameter nestor_io::vn_all_slp = "all_slp"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_all_tlm
character(len=*), parameter nestor_io::vn_all_tlm = "all_tlm"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_all_tlp
character(len=*), parameter nestor_io::vn_all_tlp = "all_tlp"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_amatrix
character(len=*), parameter nestor_io::vn_amatrix = "amatrix"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_amatsav
character(len=*), parameter nestor_io::vn_amatsav = "amatsav"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_auu
character(len=*), parameter nestor_io::vn_auu = "auu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_auv
character(len=*), parameter nestor_io::vn_auv = "auv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_avv
character(len=*), parameter nestor_io::vn_avv = "avv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_azm1u
character(len=*), parameter nestor_io::vn_azm1u = "azm1u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_azp1u
character(len=*), parameter nestor_io::vn_azp1u = "azp1u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bexn
character(len=*), parameter nestor_io::vn_bexn = "bexn"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bexni
character(len=*), parameter nestor_io::vn_bexni = "bexni"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bexu
character(len=*), parameter nestor_io::vn_bexu = "bexu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bexv
character(len=*), parameter nestor_io::vn_bexv = "bexv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bphi
character(len=*), parameter nestor_io::vn_bphi = "bphi"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bphiv
character(len=*), parameter nestor_io::vn_bphiv = "bphiv"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_brad
character(len=*), parameter nestor_io::vn_brad = "brad"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_brv
character(len=*), parameter nestor_io::vn_brv = "brv"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_bsqvac
character(len=*), parameter nestor_io::vn_bsqvac = "bsqvac"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_bsubu
character(len=*), parameter nestor_io::vn_bsubu = "bsubu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bsubv
character(len=*), parameter nestor_io::vn_bsubv = "bsubv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bsubvvac
character(len=*), parameter nestor_io::vn_bsubvvac = "bsubvvac"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_bvecsav
character(len=*), parameter nestor_io::vn_bvecsav = "bvecsav"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_bz
character(len=*), parameter nestor_io::vn_bz = "bz"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_bzv
character(len=*), parameter nestor_io::vn_bzv = "bzv"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_cma
character(len=*), parameter nestor_io::vn_cma = "cma"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_cma11u
character(len=*), parameter nestor_io::vn_cma11u = "cma11u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ctor
character(len=*), parameter nestor_io::vn_ctor = "ctor"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_delt1u
character(len=*), parameter nestor_io::vn_delt1u = "delt1u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_drv
character(len=*), parameter nestor_io::vn_drv = "drv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_extcur
character(len=*), parameter nestor_io::vn_extcur = "extcur"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_green
character(len=*), parameter nestor_io::vn_green = "green"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_greenp
character(len=*), parameter nestor_io::vn_greenp = "greenp"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_grpmn
character(len=*), parameter nestor_io::vn_grpmn = "grpmn"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_grpmn_m_map
character(len=*), parameter nestor_io::vn_grpmn_m_map = "grpmn_m_map"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_grpmn_n_map
character(len=*), parameter nestor_io::vn_grpmn_n_map = "grpmn_n_map"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_gstore
character(len=*), parameter nestor_io::vn_gstore = "gstore"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_guu_b
character(len=*), parameter nestor_io::vn_guu_b = "guu_b"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_guv_b
character(len=*), parameter nestor_io::vn_guv_b = "guv_b"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_gvv_b
character(len=*), parameter nestor_io::vn_gvv_b = "gvv_b"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ier_flag
character(len=*), parameter nestor_io::vn_ier_flag = "ier_flag"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_imirr
character(len=*), parameter nestor_io::vn_imirr = "imirr"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_inputext
character(len=*), parameter nestor_io::vn_inputext = "input_extension"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_ivac
character(len=*), parameter nestor_io::vn_ivac = "ivac"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_ivacskip
character(len=*), parameter nestor_io::vn_ivacskip = "ivacskip"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_lasym
character(len=*), parameter nestor_io::vn_lasym = "lasym"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_m_map
character(len=*), parameter nestor_io::vn_m_map = "m_map"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_mgrid
character(len=*), parameter nestor_io::vn_mgrid = "mgrid_file"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_mnmax
character(len=*), parameter nestor_io::vn_mnmax = "mnmax"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_mnpd
character(len=*), parameter nestor_io::vn_mnpd = "mnpd"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_mnpd2
character(len=*), parameter nestor_io::vn_mnpd2 = "mnpd2"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and write_nestor_outputs().
vn_mpol
character(len=*), parameter nestor_io::vn_mpol = "mpol"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_n_map
character(len=*), parameter nestor_io::vn_n_map = "n_map"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_nfp
character(len=*), parameter nestor_io::vn_nfp = "nfp"
Definition at line 55 of file nestor_io.f90.
vn_ntheta
character(len=*), parameter nestor_io::vn_ntheta = "ntheta"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_ntor
character(len=*), parameter nestor_io::vn_ntor = "ntor"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_nzeta
character(len=*), parameter nestor_io::vn_nzeta = "nzeta"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_pmod
character(len=*), parameter nestor_io::vn_pmod = "xm"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_potu
character(len=*), parameter nestor_io::vn_potu = "potu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_potv
character(len=*), parameter nestor_io::vn_potv = "potv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_potvac
character(len=*), parameter nestor_io::vn_potvac = "potvac"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_r0m
character(len=*), parameter nestor_io::vn_r0m = "r0m"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_r0p
character(len=*), parameter nestor_io::vn_r0p = "r0p"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_r1b
character(len=*), parameter nestor_io::vn_r1b = "r1b"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_r1m
character(len=*), parameter nestor_io::vn_r1m = "r1m"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_r1p
character(len=*), parameter nestor_io::vn_r1p = "r1p"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ra1m
character(len=*), parameter nestor_io::vn_ra1m = "ra1m"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ra1p
character(len=*), parameter nestor_io::vn_ra1p = "ra1p"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_raxis_nestor
character(len=*), parameter nestor_io::vn_raxis_nestor = "raxis_nestor"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_rbtor
character(len=*), parameter nestor_io::vn_rbtor = "rbtor"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_rcosuv
character(len=*), parameter nestor_io::vn_rcosuv = "rcosuv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_rmnc
character(len=*), parameter nestor_io::vn_rmnc = "rmnc"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_rmns
character(len=*), parameter nestor_io::vn_rmns = "rmns"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_rsinuv
character(len=*), parameter nestor_io::vn_rsinuv = "rsinuv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_rub
character(len=*), parameter nestor_io::vn_rub = "rub"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ruu
character(len=*), parameter nestor_io::vn_ruu = "ruu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_ruv
character(len=*), parameter nestor_io::vn_ruv = "ruv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_rvb
character(len=*), parameter nestor_io::vn_rvb = "rvb"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_rvv
character(len=*), parameter nestor_io::vn_rvv = "rvv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_rzb2
character(len=*), parameter nestor_io::vn_rzb2 = "rzb2"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_signgs
character(len=*), parameter nestor_io::vn_signgs = "signgs"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_snr
character(len=*), parameter nestor_io::vn_snr = "snr"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_snv
character(len=*), parameter nestor_io::vn_snv = "snv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_snz
character(len=*), parameter nestor_io::vn_snz = "snz"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_sqad1u
character(len=*), parameter nestor_io::vn_sqad1u = "sqad1u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_sqad2u
character(len=*), parameter nestor_io::vn_sqad2u = "sqad2u"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_sqrta
character(len=*), parameter nestor_io::vn_sqrta = "sqrta"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_sqrtc
character(len=*), parameter nestor_io::vn_sqrtc = "sqrtc"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_tanu
character(len=*), parameter nestor_io::vn_tanu = "tanu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_tanv
character(len=*), parameter nestor_io::vn_tanv = "tanv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_tmod
character(len=*), parameter nestor_io::vn_tmod = "xn"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_vacuum_calls
character(len=*), parameter nestor_io::vn_vacuum_calls = 'vacuum_calls'
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_wint
character(len=*), parameter nestor_io::vn_wint = "wint"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_xmpot
character(len=*), parameter nestor_io::vn_xmpot = "xmpot"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_xnpot
character(len=*), parameter nestor_io::vn_xnpot = "xnpot"
Definition at line 83 of file nestor_io.f90.
Referenced by read_nestor_outputs(), and write_nestor_outputs().
vn_z1b
character(len=*), parameter nestor_io::vn_z1b = "z1b"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_zaxis_nestor
character(len=*), parameter nestor_io::vn_zaxis_nestor = "zaxis_nestor"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_zmnc
character(len=*), parameter nestor_io::vn_zmnc = "zmnc"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_zmns
character(len=*), parameter nestor_io::vn_zmns = "zmns"
Definition at line 55 of file nestor_io.f90.
Referenced by read_nestor_inputs(), and write_nestor_inputs().
vn_zub
character(len=*), parameter nestor_io::vn_zub = "zub"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_zuu
character(len=*), parameter nestor_io::vn_zuu = "zuu"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_zuv
character(len=*), parameter nestor_io::vn_zuv = "zuv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_zvb
character(len=*), parameter nestor_io::vn_zvb = "zvb"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
vn_zvv
character(len=*), parameter nestor_io::vn_zvv = "zvv"
Definition at line 98 of file nestor_io.f90.
Referenced by write_nestor_outputs().
wint
real(dp), dimension(:), allocatable nestor_io::wint
Definition at line 20 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
xm
real(dp), dimension(:), allocatable nestor_io::xm
Definition at line 14 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
xn
real(dp), dimension(:), allocatable nestor_io::xn
Definition at line 15 of file nestor_io.f90.
Referenced by funct3d(), nestor(), and read_nestor_inputs().
zaxis
real(dp), dimension(:), allocatable nestor_io::zaxis
Definition at line 13 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
zmnc
real(dp), dimension(:), allocatable nestor_io::zmnc
Definition at line 19 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().
zmns
real(dp), dimension(:), allocatable nestor_io::zmns
Definition at line 17 of file nestor_io.f90.
Referenced by nestor(), and read_nestor_inputs().