VMEC: src/spectrum.f90 File Reference
spectrum.f90 File Reference
Compute the spectral width of the surface geometry Fourier coefficients.
Functions/Subroutines
subroutine spectrum (rmn, zmn)
Compute the spectral width of the surface geometry Fourier coefficients.
Detailed Description
Compute the spectral width of the surface geometry Fourier coefficients.
Definition in file spectrum.f90.
Function/Subroutine Documentation
spectrum()
subroutine spectrum (real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) rmn, real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) zmn)
Compute the spectral width of the surface geometry Fourier coefficients.
Parameters
rmn Fourier coefficients of \(R\)
zmn Fourier coefficients of \(Z\)
Definition at line 8 of file spectrum.f90.
References convert_asym(), convert_sym(), vmec_main::lthreed, vmec_params::mscale, vmec_params::nscale, vmec_params::ntmax, vmec_params::rsc, vmec_params::rss, vmec_main::specw, vmec_main::xmpq, vmec_params::zcc, and vmec_params::zcs.
Referenced by printout().