VMEC: stel_kinds Module Reference
stel_kinds Module Reference
Variables
integer, parameter rprec = SELECTED_REAL_KIND(12, 100)
integer, parameter iprec = SELECTED_INT_KIND(8)
integer, parameter cprec = KIND((1.0_rprec, 1.0_rprec))
integer, parameter dp = rprec
Variable Documentation
cprec
integer, parameter stel_kinds::cprec = KIND((1.0_rprec, 1.0_rprec))
Definition at line 12 of file stel_kinds.f90.
dp
integer, parameter stel_kinds::dp = rprec
Definition at line 13 of file stel_kinds.f90.
Referenced by calc_fbal(), mercier(), nestor(), nestor_io::read_nestor_inputs(), read_nestor_outputs(), write_nestor_inputs(), and nestor_io::write_nestor_outputs().
iprec
integer, parameter stel_kinds::iprec = SELECTED_INT_KIND(8)
Definition at line 11 of file stel_kinds.f90.
rprec
integer, parameter stel_kinds::rprec = SELECTED_REAL_KIND(12, 100)
Definition at line 10 of file stel_kinds.f90.
Referenced by convert_asym(), convert_sym(), totzspa(), and totzsps().