VMEC: realspace Module Reference
realspace Module Reference
Variables
real(rprec), dimension(:,:), allocatable r1
\(R\)
real(rprec), dimension(:,:), allocatable ru
\(\partial R/\partial \theta\)
real(rprec), dimension(:,:), allocatable rv
\(\partial R/\partial \zeta\)
real(rprec), dimension(:,:), allocatable, target z1
\(Z \)
real(rprec), dimension(:,:), allocatable zu
\(\partial Z/\partial \theta\)
real(rprec), dimension(:,:), allocatable zv
\(\partial Z/\partial \zeta\)
real(rprec), dimension(:,:), allocatable rcon
spectral condensation term in \(R\)
real(rprec), dimension(:,:), allocatable zcon
spectral condensation term in \(Z\)
real(rprec), dimension(:), allocatable rcon0
spectral condensation term in \(R\) at start of current multi-grid iteration
real(rprec), dimension(:), allocatable zcon0
spectral condensation term in \(R\) at start of current multi-grid iteration
real(rprec), dimension(:), allocatable guu
\(g_{\theta, \theta}\) metric element
real(rprec), dimension(:), allocatable guv
\(g_{\theta, \zeta}\) metric element
real(rprec), dimension(:), allocatable gvv
\(g_{\zeta, \zeta}\) metric element
real(rprec), dimension(:), allocatable ru0
\(\partial R/\partial \theta\), even-m and odd-m added together appropriately
real(rprec), dimension(:), allocatable zu0
\(\partial Z/\partial \theta\), even-m and odd-m added together appropriately
real(rprec), dimension(:), allocatable gcon
spectral condensation force; "alias force"
real(rprec), dimension(:), allocatable phip
radial derivative of phi/(2*pi) on half-grid
real(rprec), dimension(:), allocatable chip
radial derivative of chi/(2*pi) on half-grid
real(rprec), dimension(:), allocatable shalf
sqrt(s) ,two-dimensional array on half-grid
real(rprec), dimension(:), allocatable sqrts
sqrt(s), two-dimensional array on full-grid
real(rprec), dimension(:), allocatable wint
two-dimensional array for normalizing angle integrations
real(rprec), dimension(:,:), allocatable, target extra1
real(rprec), dimension(:,:), allocatable, target extra2
real(rprec), dimension(:,:), allocatable, target extra3
real(rprec), dimension(:,:), allocatable, target extra4
Variable Documentation
chip
real(rprec), dimension(:), allocatable realspace::chip
radial derivative of chi/(2*pi) on half-grid
Definition at line 30 of file realspace.f90.
Referenced by add_fluxes(), allocate_ns(), free_mem_ns(), and profil3d().
extra1
real(rprec), dimension(:,:), allocatable, target realspace::extra1
Definition at line 36 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and funct3d().
extra2
real(rprec), dimension(:,:), allocatable, target realspace::extra2
Definition at line 37 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and funct3d().
extra3
real(rprec), dimension(:,:), allocatable, target realspace::extra3
Definition at line 38 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and funct3d().
extra4
real(rprec), dimension(:,:), allocatable, target realspace::extra4
Definition at line 39 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and funct3d().
gcon
real(rprec), dimension(:), allocatable realspace::gcon
spectral condensation force; "alias force"
Definition at line 27 of file realspace.f90.
Referenced by allocate_funct3d(), forces(), free_mem_funct3d(), and funct3d().
guu
real(rprec), dimension(:), allocatable realspace::guu
\(g_{\theta, \theta}\) metric element
Definition at line 20 of file realspace.f90.
Referenced by add_fluxes(), allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and jxbforce().
guv
real(rprec), dimension(:), allocatable realspace::guv
\(g_{\theta, \zeta}\) metric element
Definition at line 21 of file realspace.f90.
Referenced by add_fluxes(), allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and jxbforce().
gvv
real(rprec), dimension(:), allocatable realspace::gvv
\(g_{\zeta, \zeta}\) metric element
Definition at line 22 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), and jxbforce().
phip
real(rprec), dimension(:), allocatable realspace::phip
radial derivative of phi/(2*pi) on half-grid
Definition at line 29 of file realspace.f90.
Referenced by allocate_ns(), eqfor(), fileout(), free_mem_ns(), jxbforce(), profil3d(), and wrout().
r1
real(rprec), dimension(:,:), allocatable realspace::r1
\(R\)
Definition at line 8 of file realspace.f90.
Referenced by allocate_funct3d(), aspectratio(), bcovar(), bss(), eqfor(), eqsolve(), forces(), free_mem_funct3d(), freeb_data(), funct3d(), jacobian(), and jxbforce().
rcon
real(rprec), dimension(:,:), allocatable realspace::rcon
spectral condensation term in \(R\)
Definition at line 15 of file realspace.f90.
Referenced by allocate_funct3d(), eqfor(), fileout(), forces(), free_mem_funct3d(), and funct3d().
rcon0
real(rprec), dimension(:), allocatable realspace::rcon0
spectral condensation term in \(R\) at start of current multi-grid iteration
Definition at line 17 of file realspace.f90.
Referenced by allocate_funct3d(), forces(), free_mem_funct3d(), and funct3d().
ru
real(rprec), dimension(:,:), allocatable realspace::ru
\(\partial R/\partial \theta\)
Definition at line 9 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), forces(), free_mem_funct3d(), funct3d(), jacobian(), and jxbforce().
ru0
real(rprec), dimension(:), allocatable realspace::ru0
\(\partial R/\partial \theta\), even-m and odd-m added together appropriately
Definition at line 24 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), eqsolve(), forces(), free_mem_funct3d(), and funct3d().
rv
real(rprec), dimension(:,:), allocatable realspace::rv
\(\partial R/\partial \zeta\)
Definition at line 10 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), bss(), eqfor(), forces(), free_mem_funct3d(), funct3d(), and jxbforce().
shalf
real(rprec), dimension(:), allocatable realspace::shalf
sqrt(s) ,two-dimensional array on half-grid
Definition at line 31 of file realspace.f90.
Referenced by allocate_ns(), bcovar(), bss(), forces(), free_mem_ns(), jacobian(), jxbforce(), precondn(), and profil1d().
sqrts
real(rprec), dimension(:), allocatable realspace::sqrts
sqrt(s), two-dimensional array on full-grid
Definition at line 32 of file realspace.f90.
Referenced by allocate_ns(), bcovar(), eqfor(), forces(), free_mem_ns(), funct3d(), guess_axis(), lamcal(), profil1d(), and profil3d().
wint
real(rprec), dimension(:), allocatable realspace::wint
two-dimensional array for normalizing angle integrations
Definition at line 34 of file realspace.f90.
Referenced by add_fluxes(), allocate_ns(), aspectratio(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), funct3d(), jxbforce(), precondn(), printout(), and profil3d().
z1
real(rprec), dimension(:,:), allocatable, target realspace::z1
\(Z \)
Definition at line 11 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), bss(), eqfor(), eqsolve(), forces(), free_mem_funct3d(), freeb_data(), funct3d(), jacobian(), and wrout().
zcon
real(rprec), dimension(:,:), allocatable realspace::zcon
spectral condensation term in \(Z\)
Definition at line 16 of file realspace.f90.
Referenced by allocate_funct3d(), eqfor(), forces(), free_mem_funct3d(), and funct3d().
zcon0
real(rprec), dimension(:), allocatable realspace::zcon0
spectral condensation term in \(R\) at start of current multi-grid iteration
Definition at line 18 of file realspace.f90.
Referenced by allocate_funct3d(), forces(), free_mem_funct3d(), and funct3d().
zu
real(rprec), dimension(:,:), allocatable realspace::zu
\(\partial Z/\partial \theta\)
Definition at line 12 of file realspace.f90.
Referenced by allocate_funct3d(), aspectratio(), bcovar(), forces(), free_mem_funct3d(), funct3d(), jacobian(), and jxbforce().
zu0
real(rprec), dimension(:), allocatable realspace::zu0
\(\partial Z/\partial \theta\), even-m and odd-m added together appropriately
Definition at line 25 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), eqfor(), eqsolve(), forces(), free_mem_funct3d(), and funct3d().
zv
real(rprec), dimension(:,:), allocatable realspace::zv
\(\partial Z/\partial \zeta\)
Definition at line 13 of file realspace.f90.
Referenced by allocate_funct3d(), bcovar(), bss(), eqfor(), forces(), free_mem_funct3d(), funct3d(), and jxbforce().