VMEC: src/restart_iter.f90 File Reference
restart_iter.f90 File Reference
Save current or restore previous good state vector and reduce time step.
Functions/Subroutines
subroutine restart_iter (time_step)
Save current or restore previous good state vector and reduce time step.
Detailed Description
Save current or restore previous good state vector and reduce time step.
Definition in file restart_iter.f90.
Function/Subroutine Documentation
restart_iter()
subroutine restart_iter (real(rprec), intent(inout) time_step)
Save current or restore previous good state vector and reduce time step.
Parameters
time_step time step to be modified if convergence is bad
Definition at line 7 of file restart_iter.f90.
References vmec_main::first, vmec_main::ijacob, vmec_main::iter1, vmec_main::iter2, vmec_main::neqs, xstuff::xc, xstuff::xcdot, and xstuff::xstore.
Referenced by eqsolve(), funct3d(), and initialize_radial().