VMEC: src/tomnsp.f90 File Reference
tomnsp.f90 File Reference
Fourier-transform forces from real space to Fourier space.
Functions/Subroutines
subroutine tomnsps (frzl_array, armn, brmn, crmn, azmn, bzmn, czmn, blmn, clmn, arcon, azcon)
Fourier-transform symmetric forces from real space to Fourier space.
subroutine tomnspa (frzl_array, armn, brmn, crmn, azmn, bzmn, czmn, blmn, clmn, arcon, azcon)
Fourier-transform anti-symmetric forces from real space to Fourier space.
Detailed Description
Fourier-transform forces from real space to Fourier space.
Definition in file tomnsp.f90.
Function/Subroutine Documentation
tomnspa()
subroutine tomnspa (real(rprec), dimension(ns,0:ntor,0:mpol1,3*ntmax), intent(inout), target frzl_array, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) armn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) brmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) crmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) azmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) bzmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) czmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) blmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) clmn, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) arcon, real(rprec), dimension(ns*nzeta,ntheta3,0:1), intent(in) azcon)
Fourier-transform anti-symmetric forces from real space to Fourier space.
Parameters
frzl_array
armn
brmn
crmn
azmn
bzmn
czmn
blmn
clmn
arcon
azcon
Definition at line 184 of file tomnsp.f90.
References vmec_main::ivac, vmec_params::jlam, vmec_params::jmin2, vmec_main::lthreed, vmec_params::ntmax, dbgout::open_dbg_context(), vmec_params::rcs, vmec_params::rsc, vmec_main::xmpq, vmec_params::zcc, and vmec_params::zss.
Referenced by funct3d().
tomnsps()
subroutine tomnsps (real(rprec), dimension(ns,0:ntor,0:mpol1,3*ntmax), intent(out), target frzl_array, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) armn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) brmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) crmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) azmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) bzmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) czmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) blmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) clmn, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) arcon, real(rprec), dimension(ns*nzeta*ntheta3,0:1), intent(in) azcon)
Fourier-transform symmetric forces from real space to Fourier space.
Parameters
frzl_array
armn
brmn
crmn
azmn
bzmn
czmn
blmn
clmn
arcon
azcon
Definition at line 17 of file tomnsp.f90.
References vmec_main::ivac, vmec_params::jlam, vmec_params::jmin2, vmec_main::lthreed, vmec_params::ntmax, dbgout::open_dbg_context(), vmec_params::rcc, vmec_params::rss, vmec_main::xmpq, vmec_params::zcs, and vmec_params::zsc.
Referenced by funct3d().