#!/bin/bash

### Set the job name
#PBS -N job

### Set the number of nodes that will be used.
#PBS -l mppwidth=24
#PBS -l walltime=00:30:00

### Set the queue to submit this job.
#PBS -q debug

#PBS -V
#PBS -j oe

cd $PBS_O_WORKDIR
# Default ordering on edison is PORD, which gives mumps error -9.
# We use -mat_mumps_icntl_7 3 to switch to the SCOTCH ordering, which seems more robust.
aprun -n 1 -N 1 /global/homes/l/landrema/bin_edison/xvmec2000 input.d23p4_tm
