VMEC: src/scalfor.f90 File Reference
scalfor.f90 File Reference
Build forces from different contributions.
Functions/Subroutines
subroutine scalfor (gcx, axm, bxm, axd, bxd, cx, iflag, skip_scalfor_dbg)
Build forces from different contributions.
Detailed Description
Build forces from different contributions.
Definition in file scalfor.f90.
Function/Subroutine Documentation
scalfor()
subroutine scalfor (real(rprec), dimension(ns,0:ntor,0:mpol1,ntmax), intent(inout) gcx, real(rprec), dimension(ns+1,2), intent(in) axm, real(rprec), dimension(ns+1,2), intent(in) bxm, real(rprec), dimension(ns+1,2), intent(in) axd, real(rprec), dimension(ns+1,2), intent(in) bxd, real(rprec), dimension(ns), intent(in) cx, integer, intent(in) iflag, logical, intent(in) skip_scalfor_dbg)
Build forces from different contributions.
In below parameter names, x=R or Z.
Parameters
gcx force output
axm force contribution input
bxm force contribution input
axd force contribution input
bxd force contribution input
cx force contribution input
iflag subtract edge instability from preconditioner
Definition at line 15 of file scalfor.f90.
References vmec_main::hs, vmec_main::ivac, vmec_params::jmin2, vmec_dim::mnsize, vmec_dim::mpol1, vmec_dim::ns, vmec_dim::ns1, vmec_params::ntmax, vmec_dim::ntor1, vmec_main::num_eqsolve_retries, dbgout::open_dbg_context(), and tridslv().
Referenced by residue(), residue_con(), and residue_mhd().