VMEC: line_segment Module Reference
line_segment Module Reference
This module containes code to create a profile constructed of line segments. These line segments are assumed to be specified such that \(xx(i) < xx(i + 1)\).
Functions/Subroutines
subroutine, public line_seg (x, y, xx, yy, n)
subroutine, public line_seg_int (x, y, xx, yy, n)
logical function, public line_seg_test ()
Detailed Description
This module containes code to create a profile constructed of line segments. These line segments are assumed to be specified such that \(xx(i) < xx(i + 1)\).
Function/Subroutine Documentation
line_seg()
subroutine, public line_segment::line_seg (real(rprec), intent(in) x, real(rprec), intent(out) y, real(rprec), dimension(n), intent(in) xx, real(rprec), dimension(n), intent(in) yy, integer, intent(in) n)
Definition at line 31 of file line_segment.f.
Referenced by line_seg_test(), pcurr(), piota(), and pmass().
line_seg_int()
subroutine, public line_segment::line_seg_int (real(rprec), intent(in) x, real(rprec), intent(out) y, real(rprec), dimension(n), intent(in) xx, real(rprec), dimension(n), intent(in) yy, integer, intent(in) n)
Definition at line 74 of file line_segment.f.
References stel_constants::zero.
Referenced by line_seg_test(), and pcurr().
line_seg_test()
logical function, public line_segment::line_seg_test
Definition at line 255 of file line_segment.f.
References line_seg(), line_seg_int(), and line_seg_test().
Referenced by line_seg_test().