VMEC: src/NESTOR/bextern.f90 File Reference
bextern.f90 File Reference
Compute the total magnetic field due to external coils and the net toroidal plasma current.
Functions/Subroutines
subroutine bextern (plascur, wint)
Compute the total magnetic field due to external coils and the net toroidal plasma current.
Detailed Description
Compute the total magnetic field due to external coils and the net toroidal plasma current.
Definition in file bextern.f90.
Function/Subroutine Documentation
bextern()
subroutine bextern (real(rprec), intent(in) plascur, real(rprec), dimension(nuv2), intent(in) wint)
Compute the total magnetic field due to external coils and the net toroidal plasma current.
Parameters
plascur
wint
Definition at line 8 of file bextern.f90.
References becoil(), belicu(), vacmod::bexn, vacmod::bexni, vacmod::bexu, vacmod::bexv, vacmod::bphi, vacmod::brad, mgrid_mod::bvac, vacmod::bz, vacmod::icall, dbgout::open_dbg_context(), vacmod::pi2, vacmod::r1b, vacmod::rub, vacmod::rvb, vacmod::snr, vacmod::snv, vacmod::snz, vacmod::z1b, vacmod::zub, and vacmod::zvb.
Referenced by vacuum().