#!/bin/bash

### Set the job name
#PBS -N vmec

### Set the number of nodes that will be used.
#PBS -l mppwidth=24
#PBS -l walltime=00:30:00

### Set the queue to submit this job.
#PBS -q debug

#PBS -V
#PBS -j oe

cd $PBS_O_WORKDIR
aprun -n 1 /global/homes/l/landrema/bin_edison/xvmec2000 input.100_44_64_0.0

