VMEC: vmec_main Module Reference
vmec_main Module Reference
Variables
integer, parameter ndump = 20
dump data for this many timestamps
real(rprec), dimension(:), allocatable blam
real(rprec), dimension(:), allocatable clam
real(rprec), dimension(:), allocatable dlam
real(rprec), dimension(:,:), allocatable ard
real(rprec), dimension(:,:), allocatable arm
real(rprec), dimension(:,:), allocatable brd
real(rprec), dimension(:,:), allocatable brm
real(rprec), dimension(:,:), allocatable azd
real(rprec), dimension(:,:), allocatable azm
real(rprec), dimension(:,:), allocatable bzd
real(rprec), dimension(:,:), allocatable bzm
real(rprec), dimension(:), allocatable crd
real(rprec), dimension(:), allocatable sm
shalf(i)/sfull(i)
real(rprec), dimension(:), allocatable sp
shalf(i+1)/sfull(i)
real(rprec), dimension(:), allocatable bdamp
radial mesh-blending factor
real(rprec), dimension(:,:,:,:), allocatable faclam
real(rprec), dimension(:,:,:,:), allocatable faclam0
real(rprec), dimension(:,:), allocatable bmin
real(rprec), dimension(:,:), allocatable bmax
real(rprec), dimension(:), allocatable iotaf
rotational transform (full grid)
real(rprec), dimension(:), allocatable phipf
radial derivative of toroidal magnetic flux (full grid)
real(rprec), dimension(:), allocatable chipf
radial derivative of poloidal magnetic flux (full grid)
real(rprec), dimension(:), allocatable phi
toroidal magnetic flux
real(rprec), dimension(:), allocatable beta_vol
real(rprec), dimension(:), allocatable jcuru
poloidal current density
real(rprec), dimension(:), allocatable jcurv
toroidal current density
real(rprec), dimension(:), allocatable jdotb
real(rprec), dimension(:), allocatable buco
enclosed toroidal current profile
real(rprec), dimension(:), allocatable bvco
enclosed poloidal current profile
real(rprec), dimension(:), allocatable bdotgradv
real(rprec), dimension(:), allocatable equif
radial force balance error: grad(p) - <j x B>
real(rprec), dimension(:), allocatable specw
spectral width (diagnostic)
real(rprec), dimension(:), allocatable tcon
constraint-force multiplier
real(rprec), dimension(:), allocatable psi
real(rprec), dimension(:), allocatable yellip
real(rprec), dimension(:), allocatable yinden
real(rprec), dimension(:), allocatable ytrian
real(rprec), dimension(:), allocatable yshift
real(rprec), dimension(:), allocatable ygeo
real(rprec), dimension(:), allocatable overr
real(rprec), dimension(:), allocatable pres
pressure profile
real(rprec), dimension(:), allocatable vp
radial derivative of enclosed volume
real(rprec), dimension(:), allocatable jpar2
real(rprec), dimension(:), allocatable jperp2
real(rprec), dimension(:), allocatable bdotb
real(rprec), dimension(:), allocatable vpphi
real(rprec), dimension(:), allocatable presgrad
pressure gradient: dp/ds
real(rprec), dimension(:), allocatable bucof
real(rprec), dimension(:), allocatable bvcof
real(rprec), dimension(:), allocatable chi
poloidal magnetic flux
real(rprec), dimension(:), allocatable presf
pressure profile on full-grid, mass/phip**gamma
real(rprec), dimension(:), allocatable chips
poloidal flux (same as chip), one-dimensional array
real(rprec), dimension(:), allocatable phips
toroidal flux (same as phip), one-dimensional array
real(rprec), dimension(:), allocatable iotas
rotational transform , on half radial mesh
real(rprec), dimension(:), allocatable icurv
(-)toroidal current inside flux surface (vanishes like s)
real(rprec), dimension(:), allocatable mass
mass profile on half-grid
real(rprec), dimension(:,:), allocatable bsqsav
real(rprec), dimension(:), allocatable bredge
real(rprec), dimension(:), allocatable bpedge
real(rprec), dimension(:), allocatable bzedge
real(rprec), dimension(:), allocatable xcl0
real(rprec), dimension(0:mpol1d, 3) xmpq
spectral condensation weighting factors
real(rprec), dimension(0:mpol1d) faccon
factor for spectral constraint
real(rprec) hs
radial mesh size increment
real(rprec) currv
toroidal current (?)
real(rprec) aspect
real(rprec) ohs
real(rprec) voli
total plasma volume in m^3
real(rprec) r00
real(rprec) r0scale
real(rprec) z00
real(rprec) fsqsum0
real(rprec) fnorm
real(rprec) fsqr = 1
real(rprec) fsqz = 1
real(rprec) fsql = 1
real(rprec) fnorm1
real(rprec) fnorml
real(rprec) fsqr1
real(rprec) fsqz1
real(rprec) fsql1
real(rprec) fsq
real(rprec) fedge
real(rprec) wb
magnetic energy: volume integral over B^2/2
real(rprec) wp
kinetic/thermal energy (from pressure)
real(rprec) fsqr_con = 1
real(rprec) fsqz_con = 1
real(rprec) fsqr1_con
real(rprec) fsqz1_con
real(rprec) fsqr_mhd = 1
real(rprec) fsqz_mhd = 1
real(rprec) fsqr1_mhd
real(rprec) fsqz1_mhd
real(rprec) router
real(rprec) rinner
real(rprec) ftolv
real(rprec) otav
time-step algorithm
real(rprec), dimension(ndamp) otau
real(rprec), dimension(:,:,:), allocatable, target rmn_bdy
real(rprec), dimension(:,:,:), allocatable, target zmn_bdy
real(rprec), dimension(:), allocatable bsubu0
real(rprec), dimension(:), allocatable dbsq
real(rprec), dimension(:), allocatable rbsq
real(rprec) rbtor
poloidal current at LCFS
real(rprec) rbtor0
poloidal current at magnetic axis
real(rprec) ctor
toroidal current (?)
real(rprec) delbsq
real(rprec) res0
real(rprec) delt0r
logical lthreed
logical lconm1
logical lflip
from init_geometry
integer, dimension(:), allocatable ireflect
two-dimensional array for computing 2pi-v angle
integer multi_ns_grid
integer niterv
max iterations for current multi-grid iteration
integer first
"counter" monitoring sign of jacobian; resets R, Z, and Lambda when jacobian changes sign and decreases time step (was called irst before)
integer neqs
total number of equations to evolve (size of xc)
integer irzloff
offset in xc array between R,Z,L components
integer iequi
counter used to call -EQFOR- at end of run
integer ijacob
counter for number of times jacobian changes sign
integer iter1
number of iterations at which the currently active evolution was branched off from
integer iter2
total number of iterations
integer ivac
counts number of free-boundary iterations
integer vacuum_calls = 0
integer profil3d_calls = 0
Variable Documentation
ard
real(rprec), dimension(:,:), allocatable vmec_main::ard
Definition at line 19 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), residue_mhd(), and scale_m1().
arm
real(rprec), dimension(:,:), allocatable vmec_main::arm
Definition at line 20 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), and residue_mhd().
aspect
real(rprec) vmec_main::aspect
Definition at line 89 of file vmec_main.f90.
Referenced by eqfor(), and wrout().
azd
real(rprec), dimension(:,:), allocatable vmec_main::azd
Definition at line 23 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), residue_mhd(), and scale_m1().
azm
real(rprec), dimension(:,:), allocatable vmec_main::azm
Definition at line 24 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), and residue_mhd().
bdamp
real(rprec), dimension(:), allocatable vmec_main::bdamp
radial mesh-blending factor
Definition at line 30 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), and profil1d().
bdotb
real(rprec), dimension(:), allocatable vmec_main::bdotb
Definition at line 62 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and jxbforce().
bdotgradv
real(rprec), dimension(:), allocatable vmec_main::bdotgradv
Definition at line 47 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), jxbforce(), and wrout().
beta_vol
real(rprec), dimension(:), allocatable vmec_main::beta_vol
Definition at line 41 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and wrout().
blam
real(rprec), dimension(:), allocatable vmec_main::blam
Definition at line 16 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), and lamcal().
bmax
real(rprec), dimension(:,:), allocatable vmec_main::bmax
Definition at line 35 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
bmin
real(rprec), dimension(:,:), allocatable vmec_main::bmin
Definition at line 34 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
bpedge
real(rprec), dimension(:), allocatable vmec_main::bpedge
Definition at line 79 of file vmec_main.f90.
Referenced by eqfor(), and freeb_data().
brd
real(rprec), dimension(:,:), allocatable vmec_main::brd
Definition at line 21 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), residue_mhd(), and scale_m1().
bredge
real(rprec), dimension(:), allocatable vmec_main::bredge
Definition at line 78 of file vmec_main.f90.
Referenced by eqfor(), and freeb_data().
brm
real(rprec), dimension(:,:), allocatable vmec_main::brm
Definition at line 22 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), and residue_mhd().
bsqsav
real(rprec), dimension(:,:), allocatable vmec_main::bsqsav
Definition at line 76 of file vmec_main.f90.
Referenced by allocate_nunv(), free_mem_nunv(), freeb_data(), funct3d(), and printout().
bsubu0
real(rprec), dimension(:), allocatable vmec_main::bsubu0
Definition at line 134 of file vmec_main.f90.
Referenced by allocate_nunv(), and free_mem_nunv().
buco
real(rprec), dimension(:), allocatable vmec_main::buco
enclosed toroidal current profile
Definition at line 45 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), and wrout().
bucof
real(rprec), dimension(:), allocatable vmec_main::bucof
Definition at line 65 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
bvco
real(rprec), dimension(:), allocatable vmec_main::bvco
enclosed poloidal current profile
Definition at line 46 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), and wrout().
bvcof
real(rprec), dimension(:), allocatable vmec_main::bvcof
Definition at line 66 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
bzd
real(rprec), dimension(:,:), allocatable vmec_main::bzd
Definition at line 25 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), residue_mhd(), and scale_m1().
bzedge
real(rprec), dimension(:), allocatable vmec_main::bzedge
Definition at line 80 of file vmec_main.f90.
Referenced by eqfor(), and freeb_data().
bzm
real(rprec), dimension(:,:), allocatable vmec_main::bzm
Definition at line 26 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), and residue_mhd().
chi
real(rprec), dimension(:), allocatable vmec_main::chi
poloidal magnetic flux
Definition at line 67 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and wrout().
chipf
real(rprec), dimension(:), allocatable vmec_main::chipf
radial derivative of poloidal magnetic flux (full grid)
Definition at line 39 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), calc_fbal(), eqfor(), free_mem_ns(), profil1d(), and wrout().
chips
real(rprec), dimension(:), allocatable vmec_main::chips
poloidal flux (same as chip), one-dimensional array
Definition at line 70 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), free_mem_ns(), profil1d(), profil3d(), and vmec().
clam
real(rprec), dimension(:), allocatable vmec_main::clam
Definition at line 17 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), and lamcal().
crd
real(rprec), dimension(:), allocatable vmec_main::crd
Definition at line 27 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), residue(), residue_con(), and residue_mhd().
ctor
real(rprec) vmec_main::ctor
toroidal current (?)
Definition at line 140 of file vmec_main.f90.
Referenced by bcovar(), eqfor(), funct3d(), and wrout().
currv
real(rprec) vmec_main::currv
toroidal current (?)
Definition at line 88 of file vmec_main.f90.
Referenced by profil1d(), and readin().
dbsq
real(rprec), dimension(:), allocatable vmec_main::dbsq
Definition at line 135 of file vmec_main.f90.
Referenced by allocate_nunv(), free_mem_nunv(), funct3d(), and printout().
delbsq
real(rprec) vmec_main::delbsq
Definition at line 141 of file vmec_main.f90.
Referenced by printout().
delt0r
real(rprec) vmec_main::delt0r
Definition at line 143 of file vmec_main.f90.
Referenced by eqsolve(), reset_params(), and vmec().
dlam
real(rprec), dimension(:), allocatable vmec_main::dlam
Definition at line 18 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), and lamcal().
equif
real(rprec), dimension(:), allocatable vmec_main::equif
radial force balance error: grad(p) - <j x B>
Definition at line 48 of file vmec_main.f90.
Referenced by allocate_ns(), calc_fbal(), eqfor(), free_mem_ns(), and wrout().
faccon
real(rprec), dimension(0:mpol1d) vmec_main::faccon
factor for spectral constraint
Definition at line 85 of file vmec_main.f90.
Referenced by alias(), and fixaray().
faclam
real(rprec), dimension(:,:,:,:), allocatable vmec_main::faclam
Definition at line 31 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), lamcal(), profil3d(), residue(), and residue_mhd().
faclam0
real(rprec), dimension(:,:,:,:), allocatable vmec_main::faclam0
Definition at line 32 of file vmec_main.f90.
fedge
real(rprec) vmec_main::fedge
Definition at line 106 of file vmec_main.f90.
Referenced by printout(), and residue().
first
integer vmec_main::first
"counter" monitoring sign of jacobian; resets R, Z, and Lambda when jacobian changes sign and decreases time step (was called irst before)
Definition at line 155 of file vmec_main.f90.
Referenced by eqsolve(), evolve(), fileout(), funct3d(), initialize_radial(), jacobian(), reset_params(), and restart_iter().
fnorm
real(rprec) vmec_main::fnorm
Definition at line 96 of file vmec_main.f90.
Referenced by bcovar(), residue(), residue_con(), and residue_mhd().
fnorm1
real(rprec) vmec_main::fnorm1
Definition at line 100 of file vmec_main.f90.
Referenced by bcovar(), residue(), residue_con(), and residue_mhd().
fnorml
real(rprec) vmec_main::fnorml
Definition at line 101 of file vmec_main.f90.
Referenced by bcovar(), and residue().
fsq
real(rprec) vmec_main::fsq
Definition at line 105 of file vmec_main.f90.
Referenced by eqsolve(), evolve(), initialize_radial(), and reset_params().
fsql
real(rprec) vmec_main::fsql = 1
Definition at line 99 of file vmec_main.f90.
Referenced by evolve(), funct3d(), printout(), residue(), and wrout().
fsql1
real(rprec) vmec_main::fsql1
Definition at line 104 of file vmec_main.f90.
Referenced by evolve(), printout(), and residue().
fsqr
real(rprec) vmec_main::fsqr = 1
Definition at line 97 of file vmec_main.f90.
Referenced by eqsolve(), evolve(), funct3d(), printout(), reset_params(), residue(), residue_con(), and wrout().
fsqr1
real(rprec) vmec_main::fsqr1
Definition at line 102 of file vmec_main.f90.
Referenced by evolve(), printout(), and residue().
fsqr1_con
real(rprec) vmec_main::fsqr1_con
Definition at line 113 of file vmec_main.f90.
Referenced by printout(), and residue_con().
fsqr1_mhd
real(rprec) vmec_main::fsqr1_mhd
Definition at line 119 of file vmec_main.f90.
Referenced by printout(), and residue_mhd().
fsqr_con
real(rprec) vmec_main::fsqr_con = 1
Definition at line 111 of file vmec_main.f90.
Referenced by printout(), and residue_con().
fsqr_mhd
real(rprec) vmec_main::fsqr_mhd = 1
Definition at line 117 of file vmec_main.f90.
Referenced by printout(), and residue_mhd().
fsqsum0
real(rprec) vmec_main::fsqsum0
Definition at line 95 of file vmec_main.f90.
fsqz
real(rprec) vmec_main::fsqz = 1
Definition at line 98 of file vmec_main.f90.
Referenced by eqsolve(), evolve(), funct3d(), printout(), reset_params(), residue(), residue_con(), and wrout().
fsqz1
real(rprec) vmec_main::fsqz1
Definition at line 103 of file vmec_main.f90.
Referenced by evolve(), printout(), and residue().
fsqz1_con
real(rprec) vmec_main::fsqz1_con
Definition at line 114 of file vmec_main.f90.
Referenced by printout(), and residue_con().
fsqz1_mhd
real(rprec) vmec_main::fsqz1_mhd
Definition at line 120 of file vmec_main.f90.
Referenced by printout(), and residue_mhd().
fsqz_con
real(rprec) vmec_main::fsqz_con = 1
Definition at line 112 of file vmec_main.f90.
Referenced by printout(), and residue_con().
fsqz_mhd
real(rprec) vmec_main::fsqz_mhd = 1
Definition at line 118 of file vmec_main.f90.
Referenced by printout(), and residue_mhd().
ftolv
real(rprec) vmec_main::ftolv
Definition at line 125 of file vmec_main.f90.
Referenced by evolve(), initialize_radial(), reset_params(), and vmec().
hs
real(rprec) vmec_main::hs
radial mesh size increment
Definition at line 87 of file vmec_main.f90.
Referenced by bcovar(), eqfor(), fileout(), funct3d(), guess_axis(), initialize_radial(), precondn(), profil1d(), residue(), and scalfor().
icurv
real(rprec), dimension(:), allocatable vmec_main::icurv
(-)toroidal current inside flux surface (vanishes like s)
Definition at line 73 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), free_mem_ns(), and profil1d().
iequi
integer vmec_main::iequi
counter used to call -EQFOR- at end of run
Definition at line 161 of file vmec_main.f90.
Referenced by bcovar(), fileout(), funct3d(), and vmec().
ijacob
integer vmec_main::ijacob
counter for number of times jacobian changes sign
Definition at line 162 of file vmec_main.f90.
Referenced by eqsolve(), fileout(), initialize_radial(), reset_params(), and restart_iter().
iotaf
real(rprec), dimension(:), allocatable vmec_main::iotaf
rotational transform (full grid)
Definition at line 37 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), eqfor(), free_mem_ns(), profil1d(), and wrout().
iotas
real(rprec), dimension(:), allocatable vmec_main::iotas
rotational transform , on half radial mesh
Definition at line 72 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), eqfor(), free_mem_ns(), jxbforce(), profil1d(), vmec(), and wrout().
ireflect
integer, dimension(:), allocatable vmec_main::ireflect
two-dimensional array for computing 2pi-v angle
Definition at line 150 of file vmec_main.f90.
Referenced by alias(), allocate_ns(), free_mem_ns(), fsym_invfft(), profil3d(), symforce(), symoutput(), and symrzl().
irzloff
integer vmec_main::irzloff
offset in xc array between R,Z,L components
Definition at line 160 of file vmec_main.f90.
Referenced by bcovar(), eqsolve(), funct3d(), initialize_radial(), printout(), profil3d(), and wrout().
iter1
integer vmec_main::iter1
number of iterations at which the currently active evolution was branched off from
Definition at line 163 of file vmec_main.f90.
Referenced by bcovar(), eqsolve(), evolve(), funct3d(), initialize_radial(), reset_params(), residue(), residue_con(), residue_mhd(), and restart_iter().
iter2
integer vmec_main::iter2
total number of iterations
Definition at line 164 of file vmec_main.f90.
Referenced by add_fluxes(), bcovar(), calc_fbal(), constrain_m1(), eqsolve(), evolve(), forces(), funct3d(), initialize_radial(), jacobian(), printout(), reset_params(), residue(), residue_con(), residue_mhd(), restart_iter(), scalfor(), symforce(), tomnspa(), tomnsps(), vmec(), and wrout().
ivac
integer vmec_main::ivac
counts number of free-boundary iterations
Definition at line 165 of file vmec_main.f90.
Referenced by eqfor(), eqsolve(), forces(), freeb_data(), funct3d(), printout(), reset_params(), scalfor(), tomnspa(), tomnspa_con(), tomnsps(), tomnsps_con(), and vmec().
jcuru
real(rprec), dimension(:), allocatable vmec_main::jcuru
poloidal current density
Definition at line 42 of file vmec_main.f90.
Referenced by allocate_ns(), calc_fbal(), eqfor(), free_mem_ns(), and wrout().
jcurv
real(rprec), dimension(:), allocatable vmec_main::jcurv
toroidal current density
Definition at line 43 of file vmec_main.f90.
Referenced by allocate_ns(), calc_fbal(), eqfor(), free_mem_ns(), and wrout().
jdotb
real(rprec), dimension(:), allocatable vmec_main::jdotb
Definition at line 44 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), jxbforce(), and wrout().
jpar2
real(rprec), dimension(:), allocatable vmec_main::jpar2
Definition at line 60 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and jxbforce().
jperp2
real(rprec), dimension(:), allocatable vmec_main::jperp2
Definition at line 61 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and jxbforce().
lconm1
logical vmec_main::lconm1
Definition at line 146 of file vmec_main.f90.
Referenced by constrain_m1(), convert_asym(), convert_sym(), readin(), reset_params(), and scale_m1().
lflip
logical vmec_main::lflip
from init_geometry
Definition at line 148 of file vmec_main.f90.
Referenced by profil1d(), and readin().
lthreed
logical vmec_main::lthreed
Definition at line 145 of file vmec_main.f90.
Referenced by bcovar(), convert(), eqfor(), flip_theta(), forces(), read_indata(), readin(), residue(), residue_con(), residue_mhd(), spectrum(), symforce(), symrzl(), tomnspa(), tomnspa_con(), tomnsps(), tomnsps_con(), totzspa(), totzsps(), and wrout().
mass
real(rprec), dimension(:), allocatable vmec_main::mass
mass profile on half-grid
Definition at line 74 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), free_mem_ns(), profil1d(), and wrout().
multi_ns_grid
integer vmec_main::multi_ns_grid
Definition at line 151 of file vmec_main.f90.
Referenced by readin(), and vmec().
ndump
integer, parameter vmec_main::ndump = 20
dump data for this many timestamps
Definition at line 13 of file vmec_main.f90.
Referenced by evolve().
neqs
integer vmec_main::neqs
total number of equations to evolve (size of xc)
Definition at line 159 of file vmec_main.f90.
Referenced by allocate_ns(), funct3d(), initialize_radial(), restart_iter(), and wrout().
niterv
integer vmec_main::niterv
max iterations for current multi-grid iteration
Definition at line 153 of file vmec_main.f90.
Referenced by eqsolve(), initialize_radial(), and vmec().
ohs
real(rprec) vmec_main::ohs
Definition at line 90 of file vmec_main.f90.
Referenced by calc_fbal(), forces(), funct3d(), initialize_radial(), jacobian(), jxbforce(), and precondn().
otau
real(rprec), dimension(ndamp) vmec_main::otau
Definition at line 129 of file vmec_main.f90.
Referenced by evolve().
otav
real(rprec) vmec_main::otav
time-step algorithm
Definition at line 128 of file vmec_main.f90.
Referenced by evolve().
overr
real(rprec), dimension(:), allocatable vmec_main::overr
Definition at line 57 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and wrout().
phi
real(rprec), dimension(:), allocatable vmec_main::phi
toroidal magnetic flux
Definition at line 40 of file vmec_main.f90.
Referenced by allocate_ns(), fileout(), free_mem_ns(), jxbforce(), and wrout().
phipf
real(rprec), dimension(:), allocatable vmec_main::phipf
radial derivative of toroidal magnetic flux (full grid)
Definition at line 38 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), profil1d(), and wrout().
phips
real(rprec), dimension(:), allocatable vmec_main::phips
toroidal flux (same as phip), one-dimensional array
Definition at line 71 of file vmec_main.f90.
Referenced by add_fluxes(), allocate_ns(), free_mem_ns(), jxbforce(), profil1d(), profil3d(), and wrout().
pres
real(rprec), dimension(:), allocatable vmec_main::pres
pressure profile
Definition at line 58 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), funct3d(), jxbforce(), profil1d(), vmec(), and wrout().
presf
real(rprec), dimension(:), allocatable vmec_main::presf
pressure profile on full-grid, mass/phip**gamma
Definition at line 69 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), and wrout().
presgrad
real(rprec), dimension(:), allocatable vmec_main::presgrad
pressure gradient: dp/ds
Definition at line 64 of file vmec_main.f90.
Referenced by allocate_ns(), calc_fbal(), eqfor(), and free_mem_ns().
profil3d_calls
integer vmec_main::profil3d_calls = 0
Definition at line 168 of file vmec_main.f90.
Referenced by initialize_radial(), and profil3d().
psi
real(rprec), dimension(:), allocatable vmec_main::psi
Definition at line 51 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
r00
real(rprec) vmec_main::r00
Definition at line 92 of file vmec_main.f90.
Referenced by eqfor(), funct3d(), printout(), and profil1d().
r0scale
real(rprec) vmec_main::r0scale
Definition at line 93 of file vmec_main.f90.
Referenced by bcovar(), fixaray(), jxbforce(), lamcal(), precondn(), residue(), residue_con(), residue_mhd(), and wrout().
rbsq
real(rprec), dimension(:), allocatable vmec_main::rbsq
Definition at line 136 of file vmec_main.f90.
Referenced by allocate_nunv(), forces(), free_mem_nunv(), and funct3d().
rbtor
real(rprec) vmec_main::rbtor
poloidal current at LCFS
Definition at line 138 of file vmec_main.f90.
Referenced by bcovar(), eqfor(), funct3d(), and wrout().
rbtor0
real(rprec) vmec_main::rbtor0
poloidal current at magnetic axis
Definition at line 139 of file vmec_main.f90.
Referenced by bcovar(), eqfor(), and wrout().
res0
real(rprec) vmec_main::res0
Definition at line 142 of file vmec_main.f90.
Referenced by eqsolve(), initialize_radial(), and reset_params().
rinner
real(rprec) vmec_main::rinner
Definition at line 123 of file vmec_main.f90.
Referenced by eqfor(), and funct3d().
rmn_bdy
real(rprec), dimension(:,:,:), allocatable, target vmec_main::rmn_bdy
Definition at line 131 of file vmec_main.f90.
Referenced by allocate_nunv(), free_mem_nunv(), profil1d(), profil3d(), and readin().
router
real(rprec) vmec_main::router
Definition at line 122 of file vmec_main.f90.
Referenced by eqfor(), and funct3d().
sm
real(rprec), dimension(:), allocatable vmec_main::sm
shalf(i)/sfull(i)
Definition at line 28 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), precondn(), profil1d(), and wrout().
sp
real(rprec), dimension(:), allocatable vmec_main::sp
shalf(i+1)/sfull(i)
Definition at line 29 of file vmec_main.f90.
Referenced by allocate_ns(), free_mem_ns(), precondn(), profil1d(), and wrout().
specw
real(rprec), dimension(:), allocatable vmec_main::specw
spectral width (diagnostic)
Definition at line 49 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), free_mem_ns(), printout(), spectrum(), and wrout().
tcon
real(rprec), dimension(:), allocatable vmec_main::tcon
constraint-force multiplier
Definition at line 50 of file vmec_main.f90.
Referenced by alias(), allocate_ns(), bcovar(), and free_mem_ns().
vacuum_calls
integer vmec_main::vacuum_calls = 0
Definition at line 167 of file vmec_main.f90.
Referenced by funct3d(), and reset_params().
voli
real(rprec) vmec_main::voli
total plasma volume in m^3
Definition at line 91 of file vmec_main.f90.
Referenced by bcovar().
vp
real(rprec), dimension(:), allocatable vmec_main::vp
radial derivative of enclosed volume
Definition at line 59 of file vmec_main.f90.
Referenced by allocate_ns(), bcovar(), calc_fbal(), eqfor(), free_mem_ns(), jxbforce(), precondn(), printout(), and wrout().
vpphi
real(rprec), dimension(:), allocatable vmec_main::vpphi
Definition at line 63 of file vmec_main.f90.
Referenced by allocate_ns(), calc_fbal(), eqfor(), and free_mem_ns().
wb
real(rprec) vmec_main::wb
magnetic energy: volume integral over B^2/2
Definition at line 107 of file vmec_main.f90.
Referenced by bcovar(), eqsolve(), printout(), and wrout().
wp
real(rprec) vmec_main::wp
kinetic/thermal energy (from pressure)
Definition at line 108 of file vmec_main.f90.
Referenced by bcovar(), eqsolve(), printout(), and wrout().
xcl0
real(rprec), dimension(:), allocatable vmec_main::xcl0
Definition at line 82 of file vmec_main.f90.
xmpq
real(rprec), dimension(0:mpol1d,3) vmec_main::xmpq
spectral condensation weighting factors
Definition at line 84 of file vmec_main.f90.
Referenced by fixaray(), spectrum(), tomnspa(), tomnspa_con(), tomnsps(), tomnsps_con(), totzspa(), and totzsps().
yellip
real(rprec), dimension(:), allocatable vmec_main::yellip
Definition at line 52 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
ygeo
real(rprec), dimension(:), allocatable vmec_main::ygeo
Definition at line 56 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
yinden
real(rprec), dimension(:), allocatable vmec_main::yinden
Definition at line 53 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
yshift
real(rprec), dimension(:), allocatable vmec_main::yshift
Definition at line 55 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
ytrian
real(rprec), dimension(:), allocatable vmec_main::ytrian
Definition at line 54 of file vmec_main.f90.
Referenced by allocate_ns(), eqfor(), and free_mem_ns().
z00
real(rprec) vmec_main::z00
Definition at line 94 of file vmec_main.f90.
Referenced by funct3d(), printout(), and reset_params().
zmn_bdy
real(rprec), dimension(:,:,:), allocatable, target vmec_main::zmn_bdy
Definition at line 132 of file vmec_main.f90.
Referenced by allocate_nunv(), free_mem_nunv(), profil3d(), and readin().