VMEC: vmec_persistent Module Reference
vmec_persistent Module Reference
Variables
integer, dimension(:), allocatable ixm
integer, dimension(:), allocatable jmin3
real(rprec), dimension(:,:), allocatable cosmu
real(rprec), dimension(:,:), allocatable sinmu
real(rprec), dimension(:,:), allocatable cosmum
real(rprec), dimension(:,:), allocatable sinmum
real(rprec), dimension(:,:), allocatable cosmumi
real(rprec), dimension(:,:), allocatable sinmumi
real(rprec), dimension(:,:), allocatable cosnv
real(rprec), dimension(:,:), allocatable sinnv
real(rprec), dimension(:,:), allocatable cosnvn
real(rprec), dimension(:,:), allocatable sinnvn
real(rprec), dimension(:,:), allocatable cosmui
real(rprec), dimension(:,:), allocatable sinmui
real(rprec), dimension(:,:), allocatable cosmui3
real(rprec), dimension(:,:), allocatable cosmumi3
real(rprec), dimension(:), allocatable, target xm
real(rprec), dimension(:), allocatable, target xn
real(rprec), dimension(:), allocatable, target xm_nyq
real(rprec), dimension(:), allocatable, target xn_nyq
real(rprec), dimension(:), allocatable cos01
real(rprec), dimension(:), allocatable sin01
Variable Documentation
cos01
real(rprec), dimension(:), allocatable vmec_persistent::cos01
Definition at line 32 of file vmec_persistent.f90.
cosmu
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmu
Definition at line 11 of file vmec_persistent.f90.
Referenced by getbsubs().
cosmui
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmui
Definition at line 22 of file vmec_persistent.f90.
Referenced by wrout().
cosmui3
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmui3
Definition at line 24 of file vmec_persistent.f90.
cosmum
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmum
Definition at line 13 of file vmec_persistent.f90.
cosmumi
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmumi
Definition at line 15 of file vmec_persistent.f90.
cosmumi3
real(rprec), dimension(:,:), allocatable vmec_persistent::cosmumi3
Definition at line 25 of file vmec_persistent.f90.
cosnv
real(rprec), dimension(:,:), allocatable vmec_persistent::cosnv
Definition at line 17 of file vmec_persistent.f90.
Referenced by getbsubs(), and wrout().
cosnvn
real(rprec), dimension(:,:), allocatable vmec_persistent::cosnvn
Definition at line 19 of file vmec_persistent.f90.
ixm
integer, dimension(:), allocatable vmec_persistent::ixm
Definition at line 8 of file vmec_persistent.f90.
Referenced by interp().
jmin3
integer, dimension(:), allocatable vmec_persistent::jmin3
Definition at line 9 of file vmec_persistent.f90.
sin01
real(rprec), dimension(:), allocatable vmec_persistent::sin01
Definition at line 33 of file vmec_persistent.f90.
sinmu
real(rprec), dimension(:,:), allocatable vmec_persistent::sinmu
Definition at line 12 of file vmec_persistent.f90.
Referenced by getbsubs().
sinmui
real(rprec), dimension(:,:), allocatable vmec_persistent::sinmui
Definition at line 23 of file vmec_persistent.f90.
Referenced by wrout().
sinmum
real(rprec), dimension(:,:), allocatable vmec_persistent::sinmum
Definition at line 14 of file vmec_persistent.f90.
sinmumi
real(rprec), dimension(:,:), allocatable vmec_persistent::sinmumi
Definition at line 16 of file vmec_persistent.f90.
sinnv
real(rprec), dimension(:,:), allocatable vmec_persistent::sinnv
Definition at line 18 of file vmec_persistent.f90.
Referenced by getbsubs(), and wrout().
sinnvn
real(rprec), dimension(:,:), allocatable vmec_persistent::sinnvn
Definition at line 20 of file vmec_persistent.f90.
xm
real(rprec), dimension(:), allocatable, target vmec_persistent::xm
Definition at line 27 of file vmec_persistent.f90.
Referenced by wrout().
xm_nyq
real(rprec), dimension(:), allocatable, target vmec_persistent::xm_nyq
Definition at line 29 of file vmec_persistent.f90.
Referenced by wrout().
xn
real(rprec), dimension(:), allocatable, target vmec_persistent::xn
Definition at line 28 of file vmec_persistent.f90.
Referenced by wrout().
xn_nyq
real(rprec), dimension(:), allocatable, target vmec_persistent::xn_nyq
Definition at line 30 of file vmec_persistent.f90.
Referenced by wrout().